<?php
declare(strict_types=1);require __DIR__.'/app/admin.php';$user=require_nonagon_admin();if($_SERVER['REQUEST_METHOD']!=='POST')redirect('admin');verify_csrf();$action=investment_text($_POST,'action',40);$id=investment_text($_POST,'id',36);
try{
 if($action==='account_state'){$active=($_POST['is_active']??'0')==='1';if($id===$user['id']&&!$active)throw new DomainException('You cannot disable your own admin account.',409);db()->prepare('UPDATE users SET is_active=? WHERE id=?')->execute([(int)$active,$id]);admin_audit($user,$active?'ACCOUNT_ENABLED':'ACCOUNT_DISABLED','user',$id);flash('success','Account access updated.');redirect('admin?view=accounts');}
 if($action==='verify_email'){db()->prepare('UPDATE users SET is_email_verified=1 WHERE id=?')->execute([$id]);admin_audit($user,'EMAIL_VERIFIED_BY_ADMIN','user',$id);flash('success','Email marked verified.');redirect('admin?view=accounts');}
 if($action==='account_role'){$role=investment_text($_POST,'role',30);if(!in_array($role,['OWNER_ADMIN','ADMIN','OPS_MANAGER','SUPERVISOR','OPERATOR'],true))throw new DomainException('Invalid account role.',422);if($id===$user['id']&&$role!=='OWNER_ADMIN')throw new DomainException('The dedicated platform administrator must remain an Owner Administrator.',409);db()->prepare('UPDATE users SET role=? WHERE id=?')->execute([$role,$id]);admin_audit($user,'ACCOUNT_ROLE_CHANGED','user',$id,['role'=>$role]);flash('success','Account role updated.');redirect('admin?view=accounts');}
 if($action==='investor_kyc'){$status=investment_text($_POST,'status',20);if(!in_array($status,['VERIFIED','REJECTED'],true))throw new DomainException('Invalid KYC decision.',422);db()->prepare('UPDATE investment_investor_profiles SET kyc_status=?,verified_by=?,verified_at=UTC_TIMESTAMP() WHERE user_id=?')->execute([$status,$user['id'],$id]);admin_audit($user,'INVESTOR_KYC_'.$status,'investor_profile',$id);flash('success','Investor decision recorded.');redirect('admin?view=investment');}
 if($action==='opportunity_review'){$op=investment_opportunity($user,$id);$area=investment_text($_POST,'review_area',40);$status=investment_text($_POST,'status',20);if(!in_array($area,INVESTMENT_REVIEW_AREAS,true)||!in_array($status,['IN_REVIEW','APPROVED','CONDITIONAL','REJECTED'],true))throw new DomainException('Invalid review decision.',422);if($op['created_by']===$user['id']&&in_array($status,['APPROVED','REJECTED'],true))throw new DomainException('You cannot finally approve a review area for an opportunity you created.',409);db()->prepare("INSERT INTO investment_due_diligence_reviews(id,opportunity_id,review_area,status,reviewer_id,findings,conditions,blockers,reviewed_at) VALUES(?,?,?,?,?,?,?,?,IF(? IN ('APPROVED','CONDITIONAL','REJECTED'),UTC_TIMESTAMP(),NULL)) ON DUPLICATE KEY UPDATE status=VALUES(status),reviewer_id=VALUES(reviewer_id),findings=VALUES(findings),conditions=VALUES(conditions),blockers=VALUES(blockers),reviewed_at=VALUES(reviewed_at)")->execute([uuid(),$id,$area,$status,$user['id'],investment_text($_POST,'findings'),investment_text($_POST,'conditions'),investment_text($_POST,'blockers'),$status]);investment_event($user,$id,'DUE_DILIGENCE_REVIEWED',null,null,['area'=>$area,'decision'=>$status]);admin_audit($user,'OPPORTUNITY_REVIEW_'.$status,'investment_opportunity',$id,['area'=>$area]);flash('success','Review decision recorded.');redirect('admin-investment-review?id='.rawurlencode($id));}
 if($action==='opportunity_transition'){$to=investment_text($_POST,'to_status',30);investment_transition($user,$id,$to);admin_audit($user,'OPPORTUNITY_STATUS_'.$to,'investment_opportunity',$id);flash('success','Opportunity status updated.');redirect('admin-investment-review?id='.rawurlencode($id));}
 throw new DomainException('Unknown admin action.',422);
}catch(DomainException $e){flash('error',$e->getMessage());redirect($id&&str_starts_with($action,'opportunity_')?'admin-investment-review?id='.rawurlencode($id):'admin');}catch(Throwable $e){error_log('Admin action: '.$e->getMessage());flash('error','The administrative action could not be completed.');redirect('admin');}
