<?php
declare(strict_types=1);
require __DIR__.'/app/commercial.php';
$user=require_verified();$id=commercial_text($_GET,'id',36,true);$document=commercial_document($user,$id);
$data=$document['issued_snapshot']?json_decode($document['issued_snapshot'],true,512,JSON_THROW_ON_ERROR):commercial_snapshot($user,$id);
if(!empty($_GET['download'])){$pdf=commercial_pdf($data);header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]/','-',$document['document_number']).'.pdf"');header('Content-Length: '.strlen($pdf));echo $pdf;exit;}
$d=$data['document'];$issuer=$data['issuer'];$bank=$data['bank'];$brand=$data['brand']??null;$artwork=$brand&&$brand['creation_mode']==='ARTWORK';
$asset=static function(?array $brand,string $name):string{if(!$brand||empty($brand[$name.'_data']))return '';return 'data:'.$brand[$name.'_mime'].';base64,'.$brand[$name.'_data'];};
$addresses=$brand&&$brand['creation_mode']==='ELEMENTS'?(array)json_decode((string)($brand['addresses']??'[]'),true):[(string)($issuer['registered_address']??'')];
$emails=$brand&&$brand['creation_mode']==='ELEMENTS'?(array)json_decode((string)($brand['emails']??'[]'),true):[(string)($issuer['email']??'')];
$phones=$brand&&$brand['creation_mode']==='ELEMENTS'?(array)json_decode((string)($brand['phones']??'[]'),true):[(string)($issuer['phone']??'')];
$company=$brand&&$brand['creation_mode']==='ELEMENTS'?$brand['company_name']:$issuer['legal_name'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?= e($d['document_number']) ?></title><link rel="stylesheet" href="assets/css/commercial-document.css?v=<?= filemtime(APP_ROOT.'/assets/css/commercial-document.css') ?>"></head><body><main class="paper <?= $artwork?'has-artwork':'' ?>">
<?php if($artwork):?><div class="brand-artwork brand-artwork-header"><img src="<?= e($asset($brand,'header')) ?>" alt=""></div><?php endif;?>
<header><div class="issuer"><?php if(!$artwork&&$asset($brand,'logo')):?><img class="document-logo" src="<?= e($asset($brand,'logo')) ?>" alt="<?= e($company) ?> logo"><?php endif;?><h1><?= e($company) ?></h1><p><?= implode('<br>',array_map(fn($value)=>e((string)$value),array_filter($addresses))) ?><br><?= e(implode(' · ',array_filter($emails))) ?><?= $emails&&$phones?' · ':'' ?><?= e(implode(' · ',array_filter($phones))) ?><?php if(!$artwork&&!empty($brand['website'])):?><br><?= e($brand['website']) ?><?php endif;?><br>TIN: <?= e($issuer['tin']) ?> · RC: <?= e($issuer['rc_number']) ?></p></div><div class="doc-title"><strong><?= e($d['document_type']) ?></strong><span><?= e($d['document_number']) ?></span><small>Date: <?= e($d['issue_date']) ?><br><?= $d['document_type']==='INVOICE'?'Due':'Valid until' ?>: <?= e($d['due_date']?:$d['valid_until']) ?></small></div></header>
<section class="parties"><div><span>BILL TO</span><h2><?= e($d['customer_name']) ?></h2><p><?= nl2br(e($d['customer_address'])) ?><br>TIN: <?= e($d['customer_tin']) ?></p></div><div><span>REFERENCES</span><p>Customer PO: <?= e($d['customer_po']) ?><br>Customer reference: <?= e($d['customer_reference']) ?><br>RFQ: <?= e($d['rfq_number']) ?></p></div></section>
<table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Duration</th><th>Rate</th><th>Tax</th><th>Total</th></tr></thead><tbody><?php foreach($d['items'] as $item):?><tr><td><?= e($item['description']) ?></td><td><?= e((string)$item['quantity']) ?></td><td><?= e($item['unit']) ?></td><td><?= e((string)$item['duration']) ?></td><td><?= number_format((float)$item['rate'],2) ?></td><td><?= e((string)$item['tax_rate']) ?>%</td><td><?= number_format((float)$item['total_amount'],2) ?></td></tr><?php endforeach;?></tbody></table>
<section class="summary"><div><h3>Payment terms</h3><p><?= nl2br(e($d['payment_terms'])) ?></p><?php if($bank):?><h3>Payment information</h3><p><?= e($bank['bank_name']) ?><br><?= e($bank['account_name']) ?><br><?= e($bank['account_number'].' · '.$bank['currency']) ?></p><?php endif;?></div><dl><dt>Subtotal</dt><dd><?= number_format((float)$d['subtotal'],2) ?></dd><dt>Discount</dt><dd><?= number_format((float)$d['discount_total'],2) ?></dd><dt>Tax</dt><dd><?= number_format((float)$d['tax_total'],2) ?></dd><dt>Total</dt><dd><?= e($d['currency'].' '.number_format((float)$d['grand_total'],2)) ?></dd></dl></section>
<footer><p><?= nl2br(e($d['notes'])) ?></p><?php if(!empty($d['signature_data'])):?><img class="signature-document-image" src="data:<?= e($d['signature_mime']) ?>;base64,<?= e($d['signature_data']) ?>" alt="Authorized signature"><?php endif;?><strong><?= e($d['signatory_name']??'') ?></strong><span><?= e($d['signatory_title']??'') ?><?= !empty($d['signatory_title'])?' · ':'' ?>Authorized signatory</span></footer><?php if($artwork&&$asset($brand,'footer')):?><div class="brand-artwork brand-artwork-footer"><img src="<?= e($asset($brand,'footer')) ?>" alt=""></div><?php endif;?></main><button class="print" onclick="window.print()">Print / Save PDF</button><link rel="stylesheet" href="assets/css/commercial-signatory.css?v=<?= filemtime(APP_ROOT.'/assets/css/commercial-signatory.css') ?>"></body></html>
