<?php
declare(strict_types=1);
require __DIR__.'/app/operations.php';
$user=require_login();$pageTitle='Overview';$active='dashboard';
$state=null;$problem=null;$filters=['site'=>'','unit'=>''];$locations=[];
if(email_access_allowed($user)) {
    try {$filters=operation_filters($user,$_GET);$locations=operation_locations($user);$state=dashboard_state($user,$filters);}
    catch(Throwable $error){http_response_code($error instanceof DomainException?$error->getCode():503);$problem=$error instanceof DomainException?$error->getMessage():'Operational data is temporarily unavailable. Please retry.';if(!$error instanceof DomainException)error_log('Dashboard: '.$error->getMessage());}
}
require __DIR__.'/includes/operations-header.php';
?>
<h1 class="sr-only">Overview</h1>
<?php if(!email_access_allowed($user)):?>
<section class="panel verification"><h2>Verify your email to view operations</h2><p>Verify your email to access equipment, team assignments, and operational risks.</p><form action="resend-verification" method="post"><?= csrf_field() ?><button class="primary">Resend verification email</button></form><?php if(!empty($_SESSION['dev_verification_url'])):?><p><a href="<?= e($_SESSION['dev_verification_url']) ?>">Verify account (local development)</a></p><?php endif;?></section>
<?php elseif($problem):?><div class="notice error" role="alert"><?= e($problem) ?> <a href="dashboard">Retry dashboard</a></div>
<?php else:
$metrics=$state['summary']['metrics'];$risks=$state['summary']['risks'];
$link=fn(string $route,array $extra=[])=>$route.'?'.http_build_query(array_merge(array_filter($filters),$extra));
?>
<section class="kpi-grid" aria-label="Operational summary">
<?php foreach(['total'=>['Total Assets','equipment',[],'equipment'],'active'=>['Active Assets','equipment',['status'=>'OPERATIONAL'],'equipment'],'maintenance'=>['Under Maintenance','equipment',['status'=>'MAINTENANCE'],'maintenance'],'operators'=>['Total Operators','operators',[],'users']] as $key=>$card):$trend=$state['summary']['trends'][$key];?>
<a class="kpi" href="<?= e($link($card[1],$card[2])) ?>"><span class="kpi-icon"><?= operation_icon($card[3]) ?></span><div class="kpi-copy"><span><?= $card[0] ?></span><strong data-metric="<?= $key ?>"><?= number_format($metrics[$key]) ?></strong></div><small data-trend="<?= $key ?>" title="Change from seven days ago"><?= $trend===null?'No history yet':(($trend>0?'↗ +':($trend<0?'↘ ':'→ ')).$trend) ?></small></a>
<?php endforeach;?></section>
<div class="overview-context"><details class="scope-picker" <?= array_filter($filters)?'open':'' ?>><summary><?= operation_icon('settings') ?> Location filters <?= operation_icon('chevron') ?></summary><form class="filterbar" method="get"><div><label for="site-filter">Site</label><select id="site-filter" name="site"><option value="">All accessible sites</option><?php $seen=[];foreach($locations as $l):if(isset($seen[$l['site_id']]))continue;$seen[$l['site_id']]=true;?><option value="<?= e($l['site_id']) ?>" <?= $filters['site']===$l['site_id']?'selected':'' ?>><?= e($l['site_name']) ?></option><?php endforeach;?></select></div><div><label for="unit-filter">Unit</label><select id="unit-filter" name="unit"><option value="">All accessible units</option><?php foreach($locations as $l):?><option data-site="<?= e($l['site_id']) ?>" value="<?= e($l['unit_id']) ?>" <?= $filters['unit']===$l['unit_id']?'selected':'' ?>><?= e($l['site_name'].' / '.$l['unit_name']) ?></option><?php endforeach;?></select></div><button class="secondary">Apply</button><a href="dashboard">Reset</a></form></details><div class="heading-status"><span id="connection" role="status">● Connected</span><small id="freshness">Updated <?= gmdate('H:i:s') ?> UTC</small></div></div>
<div class="notice warning" id="offline-banner" role="status" hidden>Connection interrupted. Showing last-known data; actions require a connection. <button type="button" id="retry-live" class="text-button">Retry</button></div>
<section class="panel equipment-panel"><header class="panel-heading"><h2>Equipment Status</h2><a href="<?= e($link('equipment')) ?>">View register</a></header>
<form class="equipment-toolbar" id="equipment-search-form" role="search"><label class="search-field" for="equipment-search"><?= operation_icon('search') ?><span class="sr-only">Search equipment by name or asset ID</span><input type="search" id="equipment-search" name="q" placeholder="Search Equipment…" maxlength="255" autocomplete="off"></label><label class="sr-only" for="equipment-status">Equipment status</label><select id="equipment-status" name="status"><option value="">All Status</option><option value="OPERATIONAL">Operational</option><option value="MAINTENANCE">Maintenance</option><option value="DOWN">Critical / Down</option></select><noscript><a href="equipment">Search the equipment register</a></noscript></form>
<div class="table-wrap"><table><thead><tr><th>Name / ID</th><th>Status</th><th>Operator</th><th>Last activity</th></tr></thead><tbody id="equipment-body"><?php foreach(array_slice($state['equipment'],0,5) as $item):?><tr><td><a class="record-link" href="equipment?id=<?= e($item['id']) ?>"><?= e($item['name']) ?></a><small><?= e($item['asset_code']) ?></small></td><td><?= operation_badge($item['status']) ?></td><td><?php if($item['operator_name']):?><a href="operators?id=<?= e($item['operator_id']) ?>"><?= e($item['operator_name']) ?></a><?php else:?>Unassigned<?php endif;?></td><td><time datetime="<?= e(str_replace(' ','T',$item['last_activity_at']).'Z') ?>"><?= e($item['last_activity_at']) ?></time></td></tr><?php endforeach;?></tbody></table></div>
<div class="empty-state" id="equipment-empty" <?= $state['equipment']?'hidden':'' ?>><span class="empty-symbol"><?= operation_icon('equipment') ?></span><h3>No equipment in this view</h3><p>Register equipment in an accessible unit to see its operational status here.</p><?php if(operation_can_manage($user)):?><a class="secondary" href="equipment?create=1">Register equipment</a><?php endif;?></div>
<footer class="equipment-pagination"><span id="equipment-page-summary" role="status">Showing <?= min(5,$metrics['total']) ?> of <?= $metrics['total'] ?> assets</span><div><button class="secondary" type="button" id="equipment-previous" disabled>Previous</button><button class="secondary" type="button" id="equipment-next" <?= $metrics['total']<=5?'disabled':'' ?>>Next</button></div></footer></section>
<div class="overview-lower"><details class="panel utilization-panel" open><summary class="widget-heading"><span class="widget-icon"><?= operation_icon('equipment') ?></span><h2>Equipment Utilization</h2><?= operation_icon('chevron') ?></summary><div class="widget-body"><div id="utilization-list"><?php foreach(array_slice($state['equipment'],0,2) as $item):?><article class="utilization-card"><div class="widget-card-heading"><?= operation_icon('equipment') ?><a href="equipment?id=<?= e($item['id']) ?>"><?= e($item['name']) ?></a><a class="record-menu" href="equipment?id=<?= e($item['id']) ?>" aria-label="View <?= e($item['name']) ?> details">⋮</a></div><p><?= operation_icon('clock') ?> Next maintenance: <?= e($item['next_maintenance_at']??'Not scheduled') ?></p><p><?= operation_icon('activity') ?> Utilization and usage: <strong><?= $item['utilization_percent']===null?'Not recorded':e($item['utilization_percent']).'%' ?></strong></p><?= operation_badge($item['status']) ?></article><div class="widget-card-actions"><a href="equipment?id=<?= e($item['id']) ?>"><?= operation_icon('clock') ?> View activity logs</a><a href="equipment?id=<?= e($item['id']) ?>#maintenance-records"><?= operation_icon('maintenance') ?> View maintenance</a></div><?php endforeach;?></div><div class="widget-empty" id="utilization-empty" <?= $state['equipment']?'hidden':'' ?>><?= operation_icon('activity') ?><p>Utilization will appear as equipment activity is recorded.</p></div><a class="widget-view-all" href="<?= e($link('equipment')) ?>">View All</a></div></details>
<details class="panel alerts-panel" open><summary class="widget-heading"><span class="widget-icon"><?= operation_icon('alert') ?></span><h2>Maintenance Alerts <span class="count" data-risk="total"><?= $risks['total'] ?></span></h2><?= operation_icon('chevron') ?></summary><div class="widget-body"><div id="alert-list"><?php foreach($state['alerts'] as $alert):?><article class="alert-card severity-<?= strtolower($alert['severity']) ?>"><div class="widget-card-heading"><?= operation_icon('alert') ?><a href="alert?id=<?= e($alert['id']) ?>"><?= e($alert['equipment_name']) ?></a><a class="record-menu" href="alert?id=<?= e($alert['id']) ?>" aria-label="View alert details">⋮</a></div><h3><?= e($alert['title']) ?></h3><p><?= e($alert['asset_code']) ?> · <time data-triggered="<?= e(str_replace(' ','T',$alert['triggered_at']).'Z') ?>"><?= e($alert['triggered_at']) ?></time></p><?= operation_badge($alert['severity']) ?><div class="alert-actions"><a href="alert?id=<?= e($alert['id']) ?>">View details</a><?php if(operation_can_manage($user)):?><a href="alert?id=<?= e($alert['id']) ?>#assign">Assign</a><?php if(!$alert['acknowledged_at']):?><form action="operations-action" method="post" class="alert-quick"><?= csrf_field() ?><input type="hidden" name="id" value="<?= e($alert['id']) ?>"><input type="hidden" name="action" value="acknowledge"><button class="text-button">Acknowledge</button></form><?php endif;?><a href="alert?id=<?= e($alert['id']) ?>#escalate">Escalate</a><?php endif;?></div></article><?php endforeach;?></div><div class="widget-empty" id="alerts-empty" <?= $state['alerts']?'hidden':'' ?>><?= operation_icon('alert') ?><h3>No active alerts</h3><p>No maintenance, safety, or compliance alerts in your current scope.</p></div><a class="widget-view-all" href="<?= e($link('alerts')) ?>">View All</a></div></details></div>
<section class="health-footer"><span><b data-risk="critical"><?= $risks['critical'] ?></b> critical alerts</span><span><b data-maintenance="overdue"><?= $state['summary']['maintenance']['overdue'] ?></b> overdue work orders</span><span id="load-time">Loaded in <?= $state['meta']['load_ms'] ?> ms</span><span id="event-lag">Data checked every 3 seconds</span></section>
<?php if(development_verification_bypass()):?><p class="development-note">Local development · Email verification bypass enabled</p><?php endif;?>
<script type="application/json" id="dashboard-bootstrap"><?= json_encode(['state'=>$state,'hashes'=>dashboard_hashes($state),'filters'=>$filters,'canManage'=>operation_can_manage($user),'csrf'=>csrf_token(),'session'=>hash('sha256',session_id())],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR) ?></script><script src="assets/js/dashboard.js" defer></script>
<?php endif;require __DIR__.'/includes/operations-footer.php';?>
