<?php
declare(strict_types=1);
require __DIR__.'/app/equipment-catalog.php';
$user=require_verified();$canEdit=operation_can_manage($user);equipment_seed_statuses($user['owner_id']);$catalog=equipment_catalog($user);
$active='equipment';$pageTitle='Equipment Settings';$edit=null;$editKind=null;
try{if(isset($_GET['edit'])){$editKind=equipment_text($_GET,'kind',20,true);$edit=catalog_record($user,$editKind,equipment_text($_GET,'edit',36,true),true);}}catch(DomainException $error){http_response_code($error->getCode());flash('error',$error->getMessage());}
require __DIR__.'/includes/operations-header.php';
function catalog_options(array $entries,?string $selected=null):void {foreach($entries as $entry)echo '<option value="'.e($entry['id']).'" '.($entry['id']===$selected?'selected':'').'>'.e(($entry['industry']??'')?($entry['industry'].' / '.$entry['name']):$entry['name']).'</option>';}
?>
<section class="page-heading"><div><p class="eyebrow">EQUIPMENT DIRECTORY</p><h1>Equipment Settings</h1><p>Shared categories, company additions, reusable assemblies, and location defaults.</p></div><a class="primary" href="equipment?create=1">Register equipment</a></section>
<nav class="section-tabs" aria-label="Equipment settings sections"><a href="#directory">Category directory</a><a href="#standards">Assemblies & parts</a><a href="#locations">Locations</a><?php if($user['role']==='OWNER_ADMIN'):?><a href="#company">Company profile</a><?php endif;?></nav>
<?php if($edit&&$canEdit):?><section class="panel form-panel"><h2>Edit <?= e($edit['name']) ?></h2><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="catalog.edit"><input type="hidden" name="kind" value="<?= e($editKind) ?>"><input type="hidden" name="id" value="<?= e($edit['id']) ?>"><label>Name<input name="name" maxlength="150" value="<?= e($edit['name']) ?>" required></label><?php if($editKind==='category'):?><label>Industry<input name="industry" maxlength="100" value="<?= e($edit['industry']) ?>" required></label><?php endif;?><?php if($editKind==='subcategory'):?><label>Artwork URL (HTTPS)<input name="artwork_url" maxlength="500" value="<?= e($edit['artwork_url']??'') ?>"></label><?php endif;?><?php if(in_array($editKind,['part','template'],true)):?><label class="full">Description<textarea name="description" maxlength="20000"><?= e($edit['description']??'') ?></textarea></label><?php endif;?><div class="full"><button class="primary">Save entry</button> <a href="equipment-settings">Cancel</a></div></form></section><?php endif;?>
<section class="panel settings-section" id="directory"><h2>Category directory</h2><p>Base entries are shared and read-only. New entries are private to your company.</p>
<?php if($canEdit):?><details class="settings-form"><summary>Add a category, subcategory, type, brand, model, or status</summary><div class="settings-grid">
<?php foreach(['category'=>'Category','subcategory'=>'Subcategory','type'=>'Equipment type','brand'=>'Brand / manufacturer','model'=>'Model','status'=>'Company status'] as $kind=>$label):?><form action="equipment-action" method="post" class="stack mini-form"><h3><?= $label ?></h3><?= csrf_field() ?><input type="hidden" name="action" value="catalog.create"><input type="hidden" name="kind" value="<?= $kind ?>"><label>Name<input name="name" maxlength="150" required></label>
<?php if($kind==='category'):?><label>Industry<input name="industry" maxlength="100" list="industries" required></label><?php elseif(in_array($kind,['subcategory','type','model'],true)):[$parent,$field]=['subcategory'=>['category','category_id'],'type'=>['subcategory','subcategory_id'],'model'=>['brand','brand_id']][$kind];?><label><?= e(ucfirst($parent)) ?><select name="<?= $field ?>" required><option value="">Choose parent</option><?php catalog_options($catalog[$parent]);?></select></label><?php endif;?>
<?php if($kind==='subcategory'):?><label>Artwork URL <small>Optional · HTTPS</small><input name="artwork_url" type="url" maxlength="500"></label><?php elseif($kind==='status'):?><label>Operational meaning<select name="operational_state"><option value="OPERATIONAL">Operational</option><option value="MAINTENANCE">Maintenance</option><option value="DOWN">Critical / Down</option></select></label><?php endif;?><button class="secondary">Add <?= e(strtolower($label)) ?></button></form><?php endforeach;?></div></details><?php endif;?>
<datalist id="industries"><?php foreach(array_unique(array_column($catalog['category'],'industry')) as $industry):?><option value="<?= e($industry) ?>"><?php endforeach;?></datalist>
<div class="table-wrap"><table><thead><tr><th>Industry</th><th>Category</th><th>Subcategory</th><th>Scope</th><th></th></tr></thead><tbody><?php $categories=array_column($catalog['category'],null,'id');foreach($catalog['subcategory'] as $sub):$cat=$categories[$sub['category_id']];?><tr><td><?= e($cat['industry']) ?></td><td><?= e($cat['name']) ?></td><td><?= e($sub['name']) ?></td><td><?= $sub['owner_id']?'Company':'Shared base' ?></td><td><?php if($canEdit&&$sub['owner_id']):?><a href="equipment-settings?kind=subcategory&amp;edit=<?= e($sub['id']) ?>">Edit</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
<details class="settings-form"><summary>Categories, types, manufacturers, models, and statuses</summary><?php foreach(['category','type','brand','model','status'] as $kind):?><h3><?= e(ucfirst($kind)) ?></h3><div class="directory-chips"><?php foreach($catalog[$kind] as $entry):?><span><?= e($entry['name']) ?><?php if($canEdit&&$entry['owner_id']):?> <a href="equipment-settings?kind=<?= $kind ?>&amp;edit=<?= e($entry['id']) ?>">Edit</a><?php endif;?></span><?php endforeach;?></div><?php endforeach;?></details></section>
<section class="panel settings-section" id="standards"><h2>Assemblies & parts</h2><p>Templates load automatically when equipment is classified by type. Changing a template never rewrites an existing asset. Company additions are unverified until separately reviewed for global standardization.</p>
<?php if($canEdit):?><details class="settings-form"><summary>Create a reusable part or assembly template</summary><div class="settings-grid"><form action="equipment-action" method="post" class="stack mini-form"><h3>Canonical part</h3><?= csrf_field() ?><input type="hidden" name="action" value="catalog.create"><input type="hidden" name="kind" value="part"><label>Part name<input name="name" maxlength="150" required></label><label>Description<textarea name="description" maxlength="20000"></textarea></label><label>Manufacturer part number<input name="manufacturer_part_number" maxlength="150"></label><label>OEM part number<input name="oem_part_number" maxlength="150"></label><label>Brand<select name="brand_id"><option value="">Any / unspecified</option><?php catalog_options($catalog['brand']);?></select></label><label>Model<select name="model_id"><option value="">Any / unspecified</option><?php catalog_options($catalog['model']);?></select></label><label>Unit of measure<input name="unit_of_measure" value="PCS" maxlength="20"></label><label>Function <small>Optional</small><input name="function_name" maxlength="100" placeholder="e.g. Filtration"></label><label class="check-label"><input type="checkbox" name="is_serviceable"> Serviceable</label><label class="check-label"><input type="checkbox" name="is_consumable"> Consumable</label><button class="primary">Create part</button></form>
<form action="equipment-action" method="post" class="stack mini-form"><h3>Assembly template</h3><?= csrf_field() ?><input type="hidden" name="action" value="catalog.create"><input type="hidden" name="kind" value="template"><label>Name<input name="name" maxlength="150" required></label><label>Description<textarea name="description" maxlength="20000"></textarea></label><label>Equipment type<select name="equipment_type_id" required><option value="">Choose type</option><?php catalog_options($catalog['type']);?></select></label><label>Brand <small>Optional specificity</small><select name="brand_id"><option value="">Any brand</option><?php catalog_options($catalog['brand']);?></select></label><label>Model <small>Optional specificity</small><select name="model_id"><option value="">Any model</option><?php catalog_options($catalog['model']);?></select></label><button class="primary">Create assembly template</button></form></div></details><?php endif;?>
<?php if(!$catalog['template']):?><p class="empty-inline">No assembly templates yet. Create an equipment type, then its assembly template.</p><?php endif;?>
<?php foreach($catalog['template'] as $template):$bom=rows('SELECT i.*,p.name AS part_name,t.name AS subassembly_name FROM assembly_template_items i LEFT JOIN part_master p ON p.id=i.part_id LEFT JOIN assembly_templates t ON t.id=i.subassembly_id WHERE i.assembly_template_id=? ORDER BY i.sequence,i.id',[$template['id']]);?><details class="settings-form"><summary><?= e($template['name']) ?> <span class="muted"><?= $template['owner_id']?'Company template':'Verified shared template' ?></span></summary><p><?= e($template['description']??'') ?></p><table><thead><tr><th>Item</th><th>Quantity</th><th>Required</th></tr></thead><tbody><?php foreach($bom as $item):?><tr><td><?= e($item['part_name']??$item['subassembly_name']??'Custom add-on slot') ?></td><td><?= e($item['quantity']) ?></td><td><?= $item['is_required']?'Yes':'Optional' ?></td></tr><?php endforeach;?></tbody></table>
<?php if($canEdit&&$template['owner_id']):?><p><a href="equipment-settings?kind=template&amp;edit=<?= e($template['id']) ?>">Edit template name / description</a></p><form action="equipment-action" method="post" class="form-grid mini-form"><?= csrf_field() ?><input type="hidden" name="action" value="template.item"><input type="hidden" name="assembly_template_id" value="<?= e($template['id']) ?>"><label>Canonical part<select name="part_id"><option value="">None</option><?php catalog_options($catalog['part']);?></select></label><label>Nested assembly<select name="subassembly_id"><option value="">None</option><?php catalog_options(array_values(array_filter($catalog['template'],fn($t)=>$t['id']!==$template['id']&&$t['equipment_type_id']===$template['equipment_type_id'])));?></select></label><label class="check-label full"><input type="checkbox" name="is_custom_slot"> Custom add-on slot (instead of a part or nested assembly)</label><label>Quantity<input type="number" name="quantity" value="1" min="0.001" step="0.001" required></label><label>Display order<input type="number" name="sequence" value="0"></label><label class="check-label"><input type="checkbox" name="is_required" checked> Required</label><label>Notes<input name="notes" maxlength="500"></label><div class="full"><button class="secondary">Add template item</button></div></form><?php endif;?></details><?php endforeach;?>
<details class="settings-form"><summary>Reusable part definitions (<?= count($catalog['part']) ?>)</summary><?php foreach($catalog['part'] as $part):?><p><strong><?= e($part['name']) ?></strong> · <?= e($part['manufacturer_part_number']??'No manufacturer number') ?> · <?= e($part['unit_of_measure']) ?><?php if($canEdit&&$part['owner_id']):?> <a href="equipment-settings?kind=part&amp;edit=<?= e($part['id']) ?>">Edit</a><?php endif;?></p><?php endforeach;?></details></section>
<section class="panel settings-section" id="locations"><h2>Location hierarchy</h2><p>Company → Block → Site → Plant → Unit → Equipment. Unconfigured levels are created as “Default”; rename them when ready.</p>
<?php if($user['role']==='OWNER_ADMIN'):
$tree=rows('SELECT sp.id AS block_id,sp.name AS block_name,s.id AS site_id,s.name AS site_name,p.id AS plant_id,p.name AS plant_name,u.id AS unit_id,u.name AS unit_name FROM spaces sp LEFT JOIN sites s ON s.space_id=sp.id LEFT JOIN plants p ON p.site_id=s.id LEFT JOIN units u ON u.plant_id=p.id WHERE sp.owner_id=? ORDER BY sp.name,s.name,p.name,u.name',[$user['owner_id']]);
$locationMaps=['block'=>[],'site'=>[],'plant'=>[],'unit'=>[]];foreach($tree as $row)foreach($locationMaps as $kind=>$_)if($row[$kind.'_id'])$locationMaps[$kind][$row[$kind.'_id']]=['id'=>$row[$kind.'_id'],'name'=>$row[$kind.'_name']];
$locationDetails=[];foreach(['block'=>'spaces','site'=>'sites','plant'=>'plants','unit'=>'units'] as $kind=>$table){$ids=array_keys($locationMaps[$kind]);if(!$ids)continue;$marks=implode(',',array_fill(0,count($ids),'?'));$locationDetails[$kind]=array_column(rows("SELECT * FROM {$table} WHERE id IN ({$marks})",$ids),null,'id');}
?><div class="table-wrap"><table><thead><tr><th>Block</th><th>Site</th><th>Plant</th><th>Unit</th></tr></thead><tbody><?php foreach($tree as $row):?><tr><?php foreach(['block','site','plant','unit'] as $kind):?><td><?= e($row[$kind.'_name']??'—') ?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><div class="settings-grid">
<?php foreach(['block','site','plant','unit'] as $kind):?><details class="settings-form"><summary>Create or edit <?= $kind ?></summary><form action="equipment-action" method="post" class="stack mini-form"><?= csrf_field() ?><input type="hidden" name="action" value="location.save"><input type="hidden" name="kind" value="<?= $kind ?>"><label>Existing location<select name="location_id"><option value="">Create new</option><?php catalog_options(array_values($locationMaps[$kind]));?></select></label><?php if($kind!=='block'):$parent=['site'=>'block','plant'=>'site','unit'=>'plant'][$kind];?><label>Parent <?= $parent ?> <small>For new locations</small><select name="parent_id"><option value="">Choose parent</option><?php catalog_options(array_values($locationMaps[$parent]));?></select></label><?php endif;?><label>Name<input name="name" maxlength="255" placeholder="Default"></label><?php if($kind!=='site'):?><label>Description<textarea name="description" maxlength="20000"></textarea></label><?php else:?><label>State<input name="state" maxlength="100"></label><label>LGA<input name="lga" maxlength="100"></label><label>Address<input name="address" maxlength="500"></label><?php endif;?><?php if(in_array($kind,['site','plant'],true)):?><label>Latitude<input name="gps_lat" type="number" step="0.0000001" min="-90" max="90"></label><label>Longitude<input name="gps_lng" type="number" step="0.0000001" min="-180" max="180"></label><?php endif;?><?php if($kind==='unit'):?><label>Department code<input name="department_code" maxlength="100"></label><?php endif;?><p>Select an existing location to load its details before editing. Its parent stays unchanged.</p><button class="secondary">Save <?= $kind ?></button></form></details><?php endforeach;?></div>
<script type="application/json" id="location-details"><?= json_encode($locationDetails,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_THROW_ON_ERROR) ?></script>
<script>
(() => {const data=JSON.parse(document.getElementById('location-details').textContent);document.querySelectorAll('form:has([name="location_id"])').forEach(form=>{form.querySelector('[name="location_id"]').addEventListener('change',event=>{const record=data[form.elements.kind.value]?.[event.target.value]||{};for(const name of ['name','description','state','lga','address','gps_lat','gps_lng','department_code'])if(form.elements[name])form.elements[name].value=record[name]??'';if(form.elements.parent_id){form.elements.parent_id.disabled=!!event.target.value;form.elements.parent_id.value=record.space_id||record.site_id||record.plant_id||'';}});});})();
</script>
<?php else:?><ul><?php foreach(operation_locations($user) as $location):?><li><?= e($location['site_name'].' / '.$location['unit_name']) ?></li><?php endforeach;?></ul><p>Your company owner manages the hierarchy.</p><?php endif;?></section>
<?php if($user['role']==='OWNER_ADMIN'):$company=rows('SELECT * FROM owners WHERE id=?',[$user['owner_id']])[0];?><section class="panel settings-section" id="company"><h2>Company profile</h2><p>All company fields are optional and separate from your sign-in credentials.</p><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="company.save"><?php foreach(['name'=>'Company name','email'=>'Company contact email','phone'=>'Company phone','address'=>'Address'] as $key=>$label):?><label><?= $label ?><input name="<?= $key ?>" type="<?= $key==='email'?'email':'text' ?>" maxlength="<?= ['name'=>255,'email'=>255,'phone'=>30,'address'=>500][$key] ?>" value="<?= e($company[$key]??'') ?>"></label><?php endforeach;?><div class="full"><button class="primary">Save company profile</button></div></form></section><?php endif;?>
<?php require __DIR__.'/includes/operations-footer.php';?>
