<?php
declare(strict_types=1);require __DIR__.'/app/investment-participation.php';$user=require_verified();if($_SERVER['REQUEST_METHOD']!=='POST')redirect('invest');verify_csrf();$action=investment_text($_POST,'action',40);$id=investment_text($_POST,'id',36);
try{
    if($action==='profile'){investor_profile_save($user,$_POST);flash('success','Investor profile submitted for verification.');redirect('investor-profile');}
    if($action==='save'||$action==='follow'){$table=$action==='save'?'investment_saved_opportunities':'investment_followed_opportunities';investable_opportunity($id);$exists=rows("SELECT 1 FROM {$table} WHERE user_id=? AND opportunity_id=?",[$user['id'],$id]);if($exists)db()->prepare("DELETE FROM {$table} WHERE user_id=? AND opportunity_id=?")->execute([$user['id'],$id]);else db()->prepare("INSERT INTO {$table}(user_id,opportunity_id) VALUES(?,?)")->execute([$user['id'],$id]);flash('success',ucfirst($action).' preference updated.');redirect('investment-view?id='.rawurlencode($id));}
    if($action==='participate'){$contribution=investment_participate($user,$id,$_POST);flash('success','Agreement signed and contribution submitted. Funding progress changes only after finance confirms receipt.');redirect('invest-portfolio?contribution='.rawurlencode($contribution));}
    if($action==='verify_profile'){if(!investment_can_review($user))throw new DomainException('Platform authorization required.',403);$status=investment_text($_POST,'kyc_status',20);if(!in_array($status,['VERIFIED','REJECTED'],true))throw new DomainException('Invalid KYC decision.',422);db()->prepare('UPDATE investment_investor_profiles SET kyc_status=?,verified_by=?,verified_at=UTC_TIMESTAMP() WHERE user_id=?')->execute([$status,$user['id'],$id]);flash('success','Investor verification updated.');redirect('investment-funding-admin');}
    if($action==='confirm'){investment_confirm_contribution($user,$id,investment_text($_POST,'provider_reference',255));flash('success','Capital confirmed and economic participation created.');redirect('investment-funding-admin');}
    if($action==='funding_setup'){
        if(!investment_can_review($user))throw new DomainException('Platform authorization required.',403);$op=investment_opportunity($user,$id);if($op['status']!=='PUBLISHED'||$op['publication_mode']!=='INVESTABLE')throw new DomainException('Only published investable opportunities can open funding.',409);
        $minimum=investment_number($_POST,'minimum_participation');if($minimum<=0)throw new DomainException('Enter a positive minimum participation.',422);
        $closes=str_replace('T',' ',investment_text($_POST,'funding_closes_at',19));db()->prepare("UPDATE investment_opportunities SET minimum_participation=?,funding_status='OPEN',funding_opens_at=UTC_TIMESTAMP(),funding_closes_at=? WHERE id=?")->execute([$minimum,$closes?:null,$id]);
        db()->prepare('INSERT INTO investment_funding_instructions(opportunity_id,finance_partner,account_name,bank_name,account_reference,instructions,approved_by) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE finance_partner=VALUES(finance_partner),account_name=VALUES(account_name),bank_name=VALUES(bank_name),account_reference=VALUES(account_reference),instructions=VALUES(instructions),is_active=1,approved_by=VALUES(approved_by),approved_at=UTC_TIMESTAMP()')->execute([$id,investment_text($_POST,'finance_partner',255),investment_text($_POST,'account_name',255),investment_text($_POST,'bank_name',255),investment_text($_POST,'account_reference',255),investment_text($_POST,'instructions'),$user['id']]);
        db()->prepare("INSERT INTO investment_funding_events(opportunity_id,actor_user_id,event_type,event_data) VALUES(?,?,'FUNDING_OPENED',?)")->execute([$id,$user['id'],json_encode(['minimum_participation'=>$minimum],JSON_THROW_ON_ERROR)]);flash('success','Controlled funding window opened.');redirect('investment-funding-admin');
    }
    if($action==='authorize_procurement'){if(!investment_can_review($user))throw new DomainException('Platform authorization required.',403);$op=investment_opportunity($user,$id);if($op['funding_status']!=='TARGET_REACHED')throw new DomainException('Confirmed capital has not reached the target.',409);if(!rows('SELECT 1 FROM investment_funding_instructions WHERE opportunity_id=? AND is_active=1',[$id]))throw new DomainException('Approved controlled-account instructions are required.',422);db()->prepare("UPDATE investment_opportunities SET funding_status='PROCUREMENT_AUTHORIZED' WHERE id=?")->execute([$id]);db()->prepare("INSERT INTO investment_funding_events(opportunity_id,actor_user_id,event_type) VALUES(?,?,'PROCUREMENT_AUTHORIZED')")->execute([$id,$user['id']]);flash('success','Procurement authorized. No physical ERP Asset has been created.');redirect('investment-funding-admin');}
    throw new DomainException('Unknown investment action.',422);
}catch(DomainException $e){flash('error',$e->getMessage());redirect($action==='profile'?'investor-profile':($id?'investment-view?id='.rawurlencode($id):'invest'));}catch(Throwable $e){error_log('Investment participation: '.$e->getMessage());flash('error','The investment request could not be completed.');redirect('invest');}
