<?php
declare(strict_types=1);require __DIR__.'/app/investment-participation.php';$user=require_verified();$active='investment';$pageTitle='Invest';
$where=["o.status='PUBLISHED'","o.publication_mode='INVESTABLE'"];$params=[];
if($q=investment_text($_GET,'q',120)){$where[]='(o.title LIKE ? OR o.industry LIKE ? OR tp.oem_name LIKE ? OR tp.model_name LIKE ?)';for($i=0;$i<4;$i++)$params[]='%'.$q.'%';}
if($type=investment_text($_GET,'equipment_type_id',36)){$where[]='o.equipment_type_id=?';$params[]=$type;}
if($location=investment_text($_GET,'location',120)){$where[]='o.target_geography LIKE ?';$params[]='%'.$location.'%';}
if($status=investment_text($_GET,'funding_status',30)){$where[]='o.funding_status=?';$params[]=$status;}
$items=rows("SELECT o.*,own.name organization_name,tp.oem_name,tp.model_name,tp.equipment_condition,t.name equipment_type_name,(SELECT projected_return_percent FROM investment_financial_scenarios s WHERE s.opportunity_id=o.id AND s.scenario_type='BASE') projected_return,(SELECT COALESCE(SUM(amount),0) FROM investment_capital_contributions cc WHERE cc.opportunity_id=o.id AND cc.status='CONFIRMED') confirmed_funding,EXISTS(SELECT 1 FROM investment_saved_opportunities sv WHERE sv.opportunity_id=o.id AND sv.user_id=?) saved FROM investment_opportunities o JOIN owners own ON own.id=o.organization_id LEFT JOIN investment_technical_profiles tp ON tp.opportunity_id=o.id LEFT JOIN equipment_types t ON t.id=o.equipment_type_id WHERE ".implode(' AND ',$where).' ORDER BY o.published_at DESC',[$user['id'],...$params]);
$types=rows("SELECT DISTINCT t.id,t.name FROM investment_opportunities o JOIN equipment_types t ON t.id=o.equipment_type_id WHERE o.status='PUBLISHED' AND o.publication_mode='INVESTABLE' ORDER BY t.name");require __DIR__.'/includes/operations-header.php';?>
<link rel="stylesheet" href="assets/css/investment-market.css?v=<?= filemtime(APP_ROOT.'/assets/css/investment-market.css') ?>">
<header class="invest-market-head"><div><p>NONAGON EQUIPMENT INVESTMENT</p><h1>Invest in productive equipment</h1><span>Review approved opportunities, risks and scenario-based projections. Returns are never guaranteed.</span></div><nav><a href="invest-portfolio">My investments</a><?php if(investment_can_create($user)):?> <a href="invest-opportunities">Manage opportunities</a><?php endif;?><?php if(investment_can_review($user)):?> <a href="investment-funding-admin">Funding control</a><?php endif;?></nav></header>
<form class="invest-filters"><input name="q" value="<?= e($q) ?>" placeholder="Search equipment, OEM or industry"><select name="equipment_type_id"><option value="">All equipment types</option><?php foreach($types as $option):?><option value="<?= e($option['id']) ?>" <?= $type===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select><input name="location" value="<?= e($location) ?>" placeholder="Location"><select name="funding_status"><option value="">All funding states</option><?php foreach(['OPEN','TARGET_REACHED','CLOSED','PROCUREMENT_AUTHORIZED'] as $option):?><option <?= $status===$option?'selected':'' ?>><?= $option ?></option><?php endforeach;?></select><button>Filter</button></form>
<section class="invest-results"><header><h2>Approved opportunities</h2><span><?= count($items) ?> result(s)</span></header><div class="invest-card-grid"><?php foreach($items as $item):$target=(float)$item['target_funding_amount'];$progress=$target>0?min(100,(float)$item['confirmed_funding']/$target*100):0;?><article><div class="invest-card-top"><span><?= e($item['industry']?:'Equipment') ?></span><form action="investment-participation-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?= e($item['id']) ?>"><button aria-label="Save opportunity"><?= $item['saved']?'★':'☆' ?></button></form></div><h3><a href="investment-view?id=<?= e($item['id']) ?>"><?= e($item['title']) ?></a></h3><p><?= e($item['equipment_type_name']?:'Equipment') ?> · <?= e(trim(($item['oem_name']??'').' '.($item['model_name']??''))?:'OEM/model to be confirmed') ?></p><dl><div><dt>Target</dt><dd><?= e($item['currency']) ?> <?= number_format($target) ?></dd></div><div><dt>Minimum term</dt><dd><?= number_format((int)$item['minimum_term_days']) ?> days</dd></div><div><dt>Target term</dt><dd><?= number_format((int)$item['target_term_days']) ?> days</dd></div><div><dt>Base projection</dt><dd><?= $item['projected_return']===null?'Not stated':number_format((float)$item['projected_return'],2).'%' ?></dd></div><div><dt>Location</dt><dd><?= e($item['target_geography']?:'To be confirmed') ?></dd></div></dl><div class="funding-progress"><span style="width:<?= $progress ?>%"></span></div><small><?= number_format($progress,1) ?>% confirmed · <?= e(str_replace('_',' ',$item['funding_status'])) ?></small></article><?php endforeach;?></div><?php if(!$items):?><div class="invest-empty"><h2>No opportunities match these filters</h2><p>Only approved and publicly eligible opportunities appear here.</p></div><?php endif;?></section>
<?php require __DIR__.'/includes/operations-footer.php';?>
