<?php
declare(strict_types=1);require __DIR__.'/app/investment.php';$user=require_verified();$active='investment';$pageTitle='Equipment Investment';
$reviewer=investment_can_review($user);$items=$reviewer?rows('SELECT o.*,own.name organization_name,(SELECT COUNT(*) FROM investment_due_diligence_reviews r WHERE r.opportunity_id=o.id AND r.status IN (\'APPROVED\',\'CONDITIONAL\',\'REJECTED\')) reviewed_areas FROM investment_opportunities o JOIN owners own ON own.id=o.organization_id ORDER BY o.updated_at DESC'):rows('SELECT o.*,own.name organization_name,(SELECT COUNT(*) FROM investment_due_diligence_reviews r WHERE r.opportunity_id=o.id AND r.status IN (\'APPROVED\',\'CONDITIONAL\',\'REJECTED\')) reviewed_areas FROM investment_opportunities o JOIN owners own ON own.id=o.organization_id WHERE o.organization_id=? ORDER BY o.updated_at DESC',[$user['owner_id']]);
$promoterOrganizations=$reviewer?rows('SELECT o.id,o.name,p.promoter_type,p.status,p.approved_stage FROM owners o LEFT JOIN investment_promoters p ON p.organization_id=o.id ORDER BY o.name'):[];
$counts=['DRAFT'=>0,'IN_REVIEW'=>0,'APPROVED'=>0,'PUBLISHED'=>0];foreach($items as $item){if($item['status']==='DRAFT')$counts['DRAFT']++;if(in_array($item['status'],['SUBMITTED','DUE_DILIGENCE','REVIEW','CONDITIONAL'],true))$counts['IN_REVIEW']++;if($item['status']==='APPROVED')$counts['APPROVED']++;if($item['status']==='PUBLISHED')$counts['PUBLISHED']++;}
require __DIR__.'/includes/operations-header.php';?>
<link rel="stylesheet" href="assets/css/investment.css?v=<?= filemtime(APP_ROOT.'/assets/css/investment.css') ?>">
<header class="investment-head"><div><p class="investment-kicker">CONTROLLED EQUIPMENT INVESTMENT</p><h1>Investment opportunities</h1><p>Propose, diligence and approve equipment opportunities before any capital participation.</p></div><?php if(investment_can_create($user)):?><a class="investment-button" href="invest-opportunity-edit">Create opportunity</a><?php endif;?></header>
<?php if(!investment_can_create($user)&&!$reviewer):?><div class="investment-callout"><strong>Controlled rollout</strong><p>Stage <?= (int)config('investment.opportunity_stage',1) ?> promoter access is active. Your organization is not yet an approved Opportunity Promoter.</p></div><?php endif;?>
<section class="investment-metrics"><?php foreach([['Drafts',$counts['DRAFT']],['In diligence',$counts['IN_REVIEW']],['Approved',$counts['APPROVED']],['Published',$counts['PUBLISHED']]] as $metric):?><article><span><?= e($metric[0]) ?></span><strong><?= number_format($metric[1]) ?></strong></article><?php endforeach;?></section>
<?php if($reviewer):?><section class="investment-table"><header><div><h2>Promoter access</h2><p>Platform-controlled rollout. Promoter verification does not approve an opportunity.</p></div></header><form class="investment-inline-form" method="post" action="investment-action"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="promoter"><label>Organization<select name="organization_id" required><?php foreach($promoterOrganizations as $organization):?><option value="<?= e($organization['id']) ?>"><?= e($organization['name']?:'Unnamed organization') ?></option><?php endforeach;?></select></label><label>Promoter type<select name="promoter_type"><option value="OFISSA">OFISSA</option><option value="VERIFIED_COMPANY">Verified company</option><option value="OPEN_SUBMITTER">Open submitter</option><option value="INTERNAL">Internal platform</option></select></label><label>Status<select name="promoter_status"><option value="VERIFIED">Verified</option><option value="PENDING">Pending</option><option value="SUSPENDED">Suspended</option><option value="REJECTED">Rejected</option></select></label><label>Stage<select name="approved_stage"><option>1</option><option>2</option><option>3</option></select></label><button class="investment-button" type="submit">Update access</button></form></section><?php endif;?>
<section class="investment-table"><header><div><h2>Opportunity register</h2><p><?= $reviewer?'Cross-organization review queue and publication control.':'Your organization’s proposals and review progress.' ?></p></div></header>
<?php if(!$items):?><div class="investment-empty"><h2>No opportunities yet</h2><p>An Opportunity remains separate from equipment assets and marketplace listings until funding and acquisition are complete.</p></div><?php else:?><div class="investment-table-wrap"><table><thead><tr><th>Opportunity</th><th>Promoter</th><th>Funding target</th><th>Review</th><th>Publication</th><th>Updated</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td><a href="invest-opportunity?id=<?= e($item['id']) ?>"><strong><?= e($item['title']) ?></strong></a><small><?= e($item['industry']?:'Industry not set') ?> · <?= (int)$item['quantity'] ?> unit(s)</small></td><td><?= e($item['organization_name']) ?></td><td><?= e($item['currency']) ?> <?= number_format((float)$item['target_funding_amount'],2) ?></td><td><span class="investment-status status-<?= strtolower($item['status']) ?>"><?= e(str_replace('_',' ',$item['status'])) ?></span><small><?= (int)$item['reviewed_areas'] ?>/<?= count(INVESTMENT_REVIEW_AREAS) ?> areas reviewed</small></td><td><?= e(str_replace('_',' ',$item['publication_mode'])) ?></td><td><?= e($item['updated_at']) ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php require __DIR__.'/includes/operations-footer.php';?>
