<?php
declare(strict_types=1);
require __DIR__.'/app/marketplace.php';
$pageTitle='Equipment Marketplace';$marketActive='marketplace';
try{
    [$scope,$params]=marketplace_public_scope($_GET);$page=max(1,min(10000,(int)($_GET['page']??1)));$offset=($page-1)*12;
    $join=" FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN owners own ON own.id=l.organization_id LEFT JOIN equipment_categories c ON c.id=e.category_id LEFT JOIN equipment_types t ON t.id=e.type_id LEFT JOIN marketplace_oems o ON o.id=e.marketplace_oem_id LEFT JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id LEFT JOIN marketplace_lease_terms lt ON lt.listing_id=l.id LEFT JOIN marketplace_sale_terms st ON st.listing_id=l.id";
    $total=(int)rows("SELECT COUNT(*) n{$join} WHERE {$scope}",$params)[0]['n'];
    $listings=rows("SELECT l.*,e.name equipment_name,c.name category_name,t.name type_name,o.brand_name oem_name,m.model_name,own.name owner_name,own.marketplace_verified,lt.daily_rate,lt.monthly_rate,lt.currency lease_currency,lt.negotiable lease_negotiable,lt.operator_included,st.asking_price,st.currency sale_currency,st.negotiable sale_negotiable{$join} WHERE {$scope} ORDER BY (l.marketplace_status='AVAILABLE') DESC,l.published_at DESC,l.id LIMIT 12 OFFSET {$offset}",$params);
    $categories=rows("SELECT DISTINCT c.id,c.name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN equipment_categories c ON c.id=e.category_id WHERE l.listing_status='ACTIVE' AND l.visibility='PUBLIC' ORDER BY c.name");
    $types=rows("SELECT DISTINCT t.id,t.name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN equipment_types t ON t.id=e.type_id WHERE l.listing_status='ACTIVE' AND l.visibility='PUBLIC' ORDER BY t.name");
    $oems=rows("SELECT DISTINCT o.id,o.brand_name name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN marketplace_oems o ON o.id=e.marketplace_oem_id WHERE l.listing_status='ACTIVE' AND l.visibility='PUBLIC' ORDER BY o.brand_name");
    $models=rows("SELECT DISTINCT m.id,m.model_name name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id WHERE l.listing_status='ACTIVE' AND l.visibility='PUBLIC' ORDER BY m.model_name");
}catch(Throwable $error){http_response_code($error instanceof DomainException?$error->getCode():503);$problem=$error instanceof DomainException?$error->getMessage():'Marketplace equipment is temporarily unavailable.';$listings=[];$total=0;$categories=$types=$oems=$models=[];}
$shown=count($listings);$first=$shown?$offset+1:0;$last=$shown?$offset+$shown:0;
require __DIR__.'/includes/marketplace-header.php';
?>
<section class="market-hero"><div><p class="market-kicker">NONAGON EQUIPMENT MARKETPLACE</p><h1>Put your equipment to work.</h1><p>List industrial equipment for lease or sale and reach verified operational teams.</p><a class="market-hero-button" href="marketplace-manage?view=create">List equipment <span>→</span></a></div></section>
<section class="market-heading"><div><p class="market-kicker">LIVE MARKETPLACE</p><h2>Equipment Marketplace</h2></div><form action="marketplace" method="get" class="market-heading-search"><label><span class="sr-only">Search equipment</span><input name="q" value="<?= e((string)($_GET['q']??'')) ?>" placeholder="Search <?= number_format($total) ?> equipment listing<?= $total===1?'':'s' ?>"></label><button aria-label="Search marketplace">Search</button></form></section>
<div class="market-shell" id="results">
<aside class="market-filters" id="filters"><form method="get"><input type="hidden" name="q" value="<?= e((string)($_GET['q']??'')) ?>"><header><div><h2>Filters</h2><p>Showing <?= number_format($first) ?><?= $shown?'–'.number_format($last):'' ?> of <?= number_format($total) ?> results</p></div><a href="marketplace">Clear</a></header>
<details open><summary>Commercial</summary><label>Purpose<select name="purpose"><option value="">Lease or sale</option><?php foreach(['LEASE'=>'For lease','SALE'=>'For sale','LEASE_OR_SALE'=>'Lease or sale'] as $v=>$l):?><option value="<?= $v ?>" <?= ($_GET['purpose']??'')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" name="available_now" value="1" <?= !empty($_GET['available_now'])?'checked':'' ?>> Available now</label><label>Available by<input type="date" name="available_from" value="<?= e((string)($_GET['available_from']??'')) ?>"></label></details>
<details open><summary>Equipment</summary><?php foreach(['category'=>['Category',$categories],'type'=>['Type',$types],'oem'=>['Make / OEM',$oems],'model'=>['Model',$models]] as $name=>[$label,$options]):?><label><?= $label ?><select name="<?= $name ?>"><option value="">All <?= strtolower($label) ?></option><?php foreach($options as $option):?><option value="<?= e($option['id']) ?>" <?= ($_GET[$name]??'')===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select></label><?php endforeach;?></details>
<details open id="location-filters"><summary>Locations</summary><label>Country<input name="country" value="<?= e((string)($_GET['country']??'')) ?>" placeholder="All countries"></label><label>State / region<input name="state" value="<?= e((string)($_GET['state']??'')) ?>" placeholder="All regions"></label><label>City<input name="city" value="<?= e((string)($_GET['city']??'')) ?>" placeholder="All cities"></label></details>
<details><summary>Compliance</summary><label class="check"><input type="checkbox" name="certified" value="1" <?= !empty($_GET['certified'])?'checked':'' ?>> Certification currently valid</label><label>Certification<select name="compliance"><option value="">Any</option><option value="AVAILABLE_ON_REQUEST" <?= ($_GET['compliance']??'')==='AVAILABLE_ON_REQUEST'?'selected':'' ?>>Available on request</option><option value="VALID" <?= ($_GET['compliance']??'')==='VALID'?'selected':'' ?>>Valid</option><option value="EXPIRED" <?= ($_GET['compliance']??'')==='EXPIRED'?'selected':'' ?>>Expired</option></select></label><label>Certification type<input name="certification_type" value="<?= e((string)($_GET['certification_type']??'')) ?>"></label><label class="check"><input type="checkbox" name="recently_inspected" value="1" <?= !empty($_GET['recently_inspected'])?'checked':'' ?>> Inspected in the last 90 days</label></details>
<details><summary>Pricing</summary><label>Maximum daily rate<input type="number" name="max_daily" min="0" value="<?= e((string)($_GET['max_daily']??'')) ?>"></label><label>Maximum monthly rate<input type="number" name="max_monthly" min="0" value="<?= e((string)($_GET['max_monthly']??'')) ?>"></label><label>Maximum sale price<input type="number" name="max_sale" min="0" value="<?= e((string)($_GET['max_sale']??'')) ?>"></label><label class="check"><input type="checkbox" name="request_quote" value="1" <?= !empty($_GET['request_quote'])?'checked':'' ?>> Request quote</label><label class="check"><input type="checkbox" name="negotiable" value="1" <?= !empty($_GET['negotiable'])?'checked':'' ?>> Negotiable</label><label class="check"><input type="checkbox" name="operator_included" value="1" <?= !empty($_GET['operator_included'])?'checked':'' ?>> Operator included</label></details><button class="market-button">Apply filters</button></form></aside>
<section class="market-results"><header><div><p class="market-kicker">AVAILABLE EQUIPMENT</p><h2><?= number_format($total) ?> listing<?= $total===1?'':'s' ?></h2></div></header>
<?php if(isset($problem)):?><div class="market-empty" role="alert"><h2>Marketplace unavailable</h2><p><?= e($problem) ?></p></div><?php elseif(!$listings):?><div class="market-empty"><h2>No equipment matched your search.</h2><p>Try clearing a filter or check back when owners publish new equipment.</p><a href="marketplace">Clear filters</a></div><?php else:?><div class="market-grid"><?php foreach($listings as $listing)require __DIR__.'/includes/marketplace-card.php';?></div><nav class="market-pagination" aria-label="Results pages"><span>Page <?= $page ?> of <?= max(1,(int)ceil($total/12)) ?></span><div><?php if($page>1):?><a href="?<?= e(http_build_query([...$_GET,'page'=>$page-1])) ?>">Previous</a><?php endif;?><?php if($offset+12<$total):?><a href="?<?= e(http_build_query([...$_GET,'page'=>$page+1])) ?>">Next</a><?php endif;?></div></nav><?php endif;?></section></div>
<?php require __DIR__.'/includes/marketplace-footer.php';?>
