<?php
declare(strict_types=1);require __DIR__.'/app/marketplace.php';
try{$id=marketplace_text($_GET,'id',36,true);$listing=marketplace_public_listing($id);db()->prepare('UPDATE marketplace_listings SET views=views+1 WHERE id=?')->execute([$id]);$media=rows("SELECT id,media_type,title,mime_type FROM marketplace_listing_media WHERE listing_id=? AND visibility='PUBLIC' ORDER BY is_primary DESC,sequence,created_at",[$id]);$periods=rows('SELECT start_date,end_date,availability,note FROM marketplace_availability_periods WHERE listing_id=? AND end_date>=UTC_DATE() ORDER BY start_date LIMIT 20',[$id]);$locationRules=marketplace_location_rules($id);$pageTitle=$listing['title'];}
catch(Throwable $error){http_response_code($error instanceof DomainException?$error->getCode():503);$problem=$error instanceof DomainException?$error->getMessage():'This marketplace listing is temporarily unavailable.';$pageTitle='Listing unavailable';}
$marketActive='marketplace';require __DIR__.'/includes/marketplace-header.php';
?>
<?php if(isset($problem)):?><section class="market-empty"><h1>Listing unavailable</h1><p><?= e($problem) ?></p><a class="market-button" href="marketplace">Browse equipment</a></section><?php else:$specs=json_decode($listing['public_specifications']??'{}',true)?:[];?>
<nav class="market-breadcrumbs"><a href="marketplace">Marketplace</a><span>/</span><span><?= e($listing['title']) ?></span></nav>
<section class="listing-head"><div><p class="market-kicker"><?= e(marketplace_purpose_label($listing['purpose'])) ?></p><h1><?= e($listing['title']) ?></h1><p><?= e(implode(' · ',array_filter([$listing['oem_name'],$listing['model_name'],$listing['type_name']]))) ?></p></div><div><?= marketplace_status_badge($listing['marketplace_status']) ?><strong><?= e(marketplace_price($listing)) ?></strong></div></section>
<div class="listing-layout"><div class="listing-main"><section class="listing-gallery"><img id="market-main-image" src="marketplace-media?listing_id=<?= e($id) ?>" alt="<?= e($listing['title']) ?>"><?php $images=array_filter($media,fn($m)=>$m['media_type']==='IMAGE');if(count($images)>1):?><div class="market-thumbnails"><?php foreach($images as $image):?><button type="button" data-market-photo="marketplace-media?id=<?= e($image['id']) ?>"><img src="marketplace-media?id=<?= e($image['id']) ?>" alt=""></button><?php endforeach;?></div><?php endif;?></section>
<section class="market-section"><h2>About this equipment</h2><p><?= nl2br(e($listing['description'])) ?></p></section>
<section class="market-section"><h2>Technical specifications</h2><?php if(!$specs):?><p class="muted">No public specifications supplied.</p><?php else:?><dl class="spec-grid"><?php foreach($specs as $name=>$value):?><dt><?= e($name) ?></dt><dd><?= e($value) ?></dd><?php endforeach;?></dl><?php endif;?></section>
<section class="market-section"><h2>Manufacturer</h2><div class="oem-card"><div><strong><?= e($listing['oem_name']??'Not specified') ?></strong><p><?= e($listing['model_name']??'Model not specified') ?> · <?= e($listing['oem_verification']==='VERIFIED'?'Verified OEM reference':'OEM reference pending verification') ?></p></div><?php if($listing['oem_slug']):?><a href="marketplace?oem=<?= e($listing['marketplace_oem_id']) ?>">View OEM equipment</a><?php endif;?></div><p class="muted">Manufacturer reference information is separate from the asset-specific specifications above.</p></section>
<section class="market-section"><h2>Approved media and documents</h2><div class="document-list"><?php $docs=array_filter($media,fn($m)=>$m['media_type']!=='IMAGE');if(!$docs):?><p>No public documents supplied.</p><?php else:foreach($docs as $document):?><a href="marketplace-media?id=<?= e($document['id']) ?>" target="_blank" rel="noopener"><?= e($document['title']?:str_replace('_',' ',ucwords(strtolower($document['media_type'])))) ?></a><?php endforeach;endif;?></div></section></div>
<aside class="listing-side"><section class="market-section listing-action"><p class="market-kicker">COMMERCIAL TERMS</p><h2><?= e(marketplace_purpose_label($listing['purpose'])) ?></h2><strong class="listing-price"><?= e(marketplace_price($listing)) ?></strong><dl><dt>Availability</dt><dd><?= e(ucfirst(strtolower(str_replace('_',' ',$listing['marketplace_status'])))) ?></dd><dt>Available from</dt><dd><?= e($listing['available_from']?:'Immediately') ?></dd><dt>Location</dt><dd><?= e($listing['city'].', '.$listing['state_region'].', '.$listing['country']) ?></dd><dt>Compliance</dt><dd><?= e(ucfirst(strtolower(str_replace('_',' ',$listing['compliance_status'])))) ?></dd></dl><?php if(current_user()):?><button class="market-button" disabled title="Enquiries begin in Marketplace Sprint 2">Make enquiry</button><p class="muted">Enquiries and offers are included in the next marketplace sprint.</p><?php else:?><a class="market-button" href="login">Sign in to enquire</a><?php endif;?></section>
<section class="market-section"><p class="market-kicker">OWNER</p><h2><a href="marketplace-company?id=<?= e($listing['organization_id']) ?>"><?= e($listing['owner_name']?:'Marketplace owner') ?></a></h2><p><?= $listing['marketplace_verified']?'✓ Verified marketplace company':'Company verification pending' ?></p><p><?= e(implode(', ',array_filter([$listing['owner_city'],$listing['owner_state'],$listing['owner_country']]))) ?></p><a href="marketplace-company?id=<?= e($listing['organization_id']) ?>">View company profile</a></section>
<?php if($listing['purpose']!=='SALE'):?><?php $rate=$listing['lease_rate']??$listing['daily_rate']??$listing['weekly_rate']??$listing['monthly_rate'];$unit=$listing['duration_unit']??($listing['weekly_rate']!==null?'WEEK':($listing['monthly_rate']!==null?'MONTH':'DAY'));?><section class="market-section"><h2>Lease terms</h2><dl><dt>Rate</dt><dd><?= $rate!==null?e(($listing['lease_currency']??'NGN').' '.number_format((float)$rate,2).' / '.ucfirst(strtolower($unit))):'Not specified' ?></dd><dt>Minimum duration</dt><dd><?= e((string)($listing['minimum_duration']??1).' '.strtolower($unit).((int)($listing['minimum_duration']??1)===1?'':'s')) ?></dd><dt>Security deposit</dt><dd><?= $listing['security_deposit']!==null?e(($listing['lease_currency']??'NGN').' '.number_format((float)$listing['security_deposit'],2)):'Not specified' ?></dd><dt>Operator included</dt><dd><?= $listing['operator_included']?'Yes'.($listing['operator_rate']!==null?' · '.e(($listing['lease_currency']??'NGN').' '.number_format((float)$listing['operator_rate'],2).' / '.strtolower($unit)):''):'No' ?></dd><dt>Consumables included</dt><dd><?= $listing['consumables_included']||$listing['fuel_included']?'Yes'.($listing['consumables_details']?' · '.e($listing['consumables_details']):''):'No' ?></dd><dt>Mobilization</dt><dd><?= e(marketplace_option_label('mobilization',$listing['mobilization_option'],$listing['mobilization_terms'])) ?><?= $listing['mobilization_custom']?' · '.e($listing['mobilization_custom']):'' ?></dd><dt>Demobilization</dt><dd><?= e(marketplace_option_label('demobilization',$listing['demobilization_option'],$listing['demobilization_terms'])) ?><?= $listing['demobilization_custom']?' · '.e($listing['demobilization_custom']):'' ?></dd><dt>Maintenance</dt><dd><?= e(marketplace_option_label('maintenance',$listing['maintenance_option'],$listing['maintenance_responsibility'])) ?><?= $listing['maintenance_details']?' · '.e($listing['maintenance_details']):'' ?></dd><dt>Insurance</dt><dd><?= e(marketplace_option_label('insurance',$listing['insurance_option'],$listing['insurance_requirement'])) ?><?= $listing['insurance_details']?' · '.e($listing['insurance_details']):'' ?></dd></dl></section><?php endif;?>
<?php if($listing['purpose']!=='LEASE'):?><section class="market-section"><h2>Sale terms</h2><dl><dt>Asking price</dt><dd><?= $listing['asking_price']!==null?e(($listing['sale_currency']??'NGN').' '.number_format((float)$listing['asking_price'],2)):'Not specified' ?></dd><dt>Payment</dt><dd><?= e(marketplace_option_label('payment',$listing['payment_terms'])) ?><?= $listing['payment_terms_custom']?' · '.e($listing['payment_terms_custom']):'' ?></dd><dt>Condition</dt><dd><?= e(marketplace_option_label('sale_condition',$listing['sale_condition'],ucfirst(strtolower(str_replace('_',' ',$listing['sale_condition']??''))))) ?></dd><dt>Inspection required</dt><dd><?= $listing['inspection_allowed']?'Yes':'No' ?></dd><dt>Taxes / fees</dt><dd><?= e(marketplace_option_label('taxes',$listing['taxes_fees'])) ?></dd><dt>Negotiable</dt><dd><?= $listing['sale_negotiable']?'Yes':'No' ?></dd><?php if($listing['sale_notes']):?><dt>Additional terms</dt><dd><?= nl2br(e($listing['sale_notes'])) ?></dd><?php endif;?></dl></section><?php endif;?>
<section class="market-section"><h2>Geographic availability</h2><?php if(!$locationRules):?><p>No geographic restrictions — this equipment can be mobilized anywhere.</p><?php else:?><div class="location-chips"><?php foreach($locationRules as $rule):?><span class="location-chip <?= $rule['rule']==='ALLOW'?'allow':'restrict' ?>"><?= $rule['rule']==='ALLOW'?'+':'−' ?> <?= e($rule['name']) ?></span><?php endforeach;?></div><p class="muted">Allowed locations include their regions and cities, except locations explicitly restricted.</p><?php endif;?></section></aside></div>
<script type="application/json" id="listing-public-data"><?= json_encode(['asset_code'=>$listing['public_asset_code']?$listing['asset_code']:null,'certification_type'=>$listing['certification_type'],'certification_valid_until'=>$listing['certification_valid_until'],'last_inspected_on'=>$listing['last_inspected_on'],'periods'=>$periods],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script><script>document.querySelectorAll('[data-market-photo]').forEach(button=>button.addEventListener('click',()=>document.querySelector('#market-main-image').src=button.dataset.marketPhoto));const d=JSON.parse(document.querySelector('#listing-public-data').textContent),dl=document.querySelector('.listing-action dl');for(const [label,value] of [['Public asset ID',d.asset_code],['Certification type',d.certification_type],['Valid until',d.certification_valid_until],['Last inspected',d.last_inspected_on]])if(value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;dl.append(dt,dd);}if(d.periods.length){const section=document.createElement('section');section.className='market-section';section.innerHTML='<h2>Availability calendar</h2>';const list=document.createElement('div');list.className='document-list';for(const p of d.periods){const row=document.createElement('span');row.textContent=`${p.start_date} – ${p.end_date}: ${p.availability.toLowerCase()}${p.note?' · '+p.note:''}`;list.append(row);}section.append(list);document.querySelector('.listing-side').append(section);}</script>
<?php endif;require __DIR__.'/includes/marketplace-footer.php';?>
