<?php
declare(strict_types=1);
require __DIR__.'/app/request-supply.php';
$pageTitle='Equipment Marketplace';$marketActive='marketplace';$requestedMarketView=(string)($_GET['view']??'all');$marketView=in_array($requestedMarketView,['all','equipment','requests'],true)?$requestedMarketView:'all';
try{
    [$scope,$params]=marketplace_public_scope($_GET);$page=max(1,min(10000,(int)($_GET['page']??1)));$offset=($page-1)*12;
    $join=" FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN units u ON u.id=e.unit_id JOIN plants p ON p.id=u.plant_id JOIN sites s ON s.id=p.site_id JOIN owners own ON own.id=l.organization_id LEFT JOIN equipment_categories c ON c.id=e.category_id LEFT JOIN equipment_types t ON t.id=e.type_id LEFT JOIN marketplace_oems o ON o.id=e.marketplace_oem_id LEFT JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id LEFT JOIN marketplace_lease_terms lt ON lt.listing_id=l.id LEFT JOIN marketplace_sale_terms st ON st.listing_id=l.id";
    $total=(int)rows("SELECT COUNT(*) n{$join} WHERE {$scope}",$params)[0]['n'];
    $listings=rows("SELECT l.*,e.name title,e.name equipment_name,COALESCE(NULLIF(e.long_description,''),NULLIF(e.short_description,''),l.description) description,e.marketplace_specifications public_specifications,COALESCE(NULLIF(s.state,''),l.state_region) state_region,COALESCE(NULLIF(s.name,''),l.city) city,c.name category_name,t.name type_name,o.brand_name oem_name,m.model_name,own.name owner_name,own.marketplace_verified,lt.daily_rate,lt.monthly_rate,lt.currency lease_currency,lt.negotiable lease_negotiable,lt.operator_included,st.asking_price,st.currency sale_currency,st.negotiable sale_negotiable{$join} WHERE {$scope} ORDER BY (l.marketplace_status='AVAILABLE') DESC,l.published_at DESC,l.id LIMIT 12 OFFSET {$offset}",$params);
    $categories=rows("SELECT DISTINCT c.id,c.name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN equipment_categories c ON c.id=e.category_id WHERE l.listing_status IN ('ACTIVE','RESERVED') AND l.visibility='PUBLIC' ORDER BY c.name");
    $types=rows("SELECT DISTINCT t.id,t.name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN equipment_types t ON t.id=e.type_id WHERE l.listing_status IN ('ACTIVE','RESERVED') AND l.visibility='PUBLIC' ORDER BY t.name");
    $oems=rows("SELECT DISTINCT o.id,o.brand_name name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN marketplace_oems o ON o.id=e.marketplace_oem_id WHERE l.listing_status IN ('ACTIVE','RESERVED') AND l.visibility='PUBLIC' ORDER BY o.brand_name");
    $models=rows("SELECT DISTINCT m.id,m.model_name name FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id WHERE l.listing_status IN ('ACTIVE','RESERVED') AND l.visibility='PUBLIC' ORDER BY m.model_name");
    request_expire();$requestSql="SELECT r.*,ro.name requester_name,ro.marketplace_verified,rt.name equipment_type,rl.canonical_name location_name,rl.country_name,COALESCE(NULLIF(rsc.artwork_url,''),NULLIF(tsc.artwork_url,''),'assets/images/equipment-placeholder.svg') request_image FROM marketplace_requests r JOIN owners ro ON ro.id=r.organization_id JOIN equipment_types rt ON rt.id=r.equipment_type_id LEFT JOIN equipment_subcategories rsc ON rsc.id=r.subcategory_id LEFT JOIN equipment_subcategories tsc ON tsc.id=rt.subcategory_id JOIN marketplace_locations rl ON rl.id=r.required_location_id WHERE r.status IN ('OPEN','RESPONSES_RECEIVED') AND r.visibility='PUBLIC' AND r.response_deadline>UTC_TIMESTAMP()";$requestParams=[];$requestQuery=trim((string)($_GET['q']??''));if($requestQuery!==''){$requestSql.=' AND (r.title LIKE ? OR r.description LIKE ? OR rt.name LIKE ?)';$requestParams=array_merge($requestParams,array_fill(0,3,'%'.$requestQuery.'%'));}if(!empty($_GET['type'])){$requestSql.=' AND r.equipment_type_id=?';$requestParams[]=$_GET['type'];}if(!empty($_GET['category'])){$requestSql.=' AND r.category_id=?';$requestParams[]=$_GET['category'];}if(!empty($_GET['purpose'])){$requestIntent=$_GET['purpose']==='SALE'?'PURCHASE':($_GET['purpose']==='LEASE'?'LEASE':'EITHER');$requestSql.=" AND r.intent IN (?,'EITHER')";$requestParams[]=$requestIntent;}if(!empty($_GET['country'])){$requestSql.=' AND rl.country_name LIKE ?';$requestParams[]='%'.$_GET['country'].'%';}if(!empty($_GET['state'])||!empty($_GET['city'])){$requestLocation=trim((string)($_GET['city']??'').' '.(string)($_GET['state']??''));$requestSql.=' AND rl.canonical_name LIKE ?';$requestParams[]='%'.$requestLocation.'%';}$requests=$page===1?rows($requestSql.' ORDER BY r.response_deadline,r.published_at DESC LIMIT 6',$requestParams):[];
    if($marketView==='equipment')$requests=[];elseif($marketView==='requests'){$listings=[];$total=0;}
}catch(Throwable $error){http_response_code($error instanceof DomainException?$error->getCode():503);$problem=$error instanceof DomainException?$error->getMessage():'Marketplace equipment is temporarily unavailable.';$listings=$requests=[];$total=0;$categories=$types=$oems=$models=[];}
$marketItems=[];foreach($listings as $listing)$marketItems[]=['kind'=>'listing','published_at'=>$listing['published_at']??'','item'=>$listing];foreach($requests as $request)$marketItems[]=['kind'=>'request','published_at'=>$request['published_at']??'','item'=>$request];usort($marketItems,static fn(array $a,array $b):int=>strcmp((string)$b['published_at'],(string)$a['published_at']));
$shown=count($listings);$first=$shown?$offset+1:0;$last=$shown?$offset+$shown:0;
require __DIR__.'/includes/marketplace-header.php';
?>
<section class="market-hero"><div><p class="market-kicker">NONAGON EQUIPMENT MARKETPLACE</p><h1>Put your equipment to work.</h1><p>List industrial equipment for lease or sale and reach verified operational teams.</p><div class="market-hero-actions"><a class="market-hero-button" href="marketplace-manage?view=equipment">List equipment <span>→</span></a><a class="market-hero-button market-hero-button-secondary" href="requests?view=create">Request equipment <span>→</span></a></div></div></section>
<nav class="marketplace-mode-tabs"><a href="marketplace" <?= $marketView==='all'?'aria-current="page"':'' ?>>All Marketplace</a><a href="marketplace?view=equipment" <?= $marketView==='equipment'?'aria-current="page"':'' ?>>Equipment Available</a><a href="marketplace?view=requests" <?= $marketView==='requests'?'aria-current="page"':'' ?>>Equipment Required</a></nav>
<section class="market-heading"><div><p class="market-kicker">LIVE MARKETPLACE</p><h2><?= $marketView==='requests'?'Equipment Requests':($marketView==='equipment'?'Available Equipment':'Equipment Marketplace') ?></h2></div><form action="marketplace" method="get" class="market-heading-search"><?php if($marketView!=='all'):?><input type="hidden" name="view" value="<?= e($marketView) ?>"><?php endif;?><label><span class="sr-only">Search marketplace</span><input name="q" value="<?= e((string)($_GET['q']??'')) ?>" placeholder="Search marketplace"></label><button aria-label="Search marketplace">Search</button></form></section>
<div class="market-shell" id="results">
<aside class="market-filters" id="filters"><form method="get"><input type="hidden" name="q" value="<?= e((string)($_GET['q']??'')) ?>"><header><div><h2>Filters</h2><p>Showing <?= number_format($first) ?><?= $shown?'–'.number_format($last):'' ?> of <?= number_format($total) ?> results</p></div><a href="marketplace">Clear</a></header>
<details open><summary>Commercial</summary><label>Purpose<select name="purpose"><option value="">Lease or sale</option><?php foreach(['LEASE'=>'For lease','SALE'=>'For sale','LEASE_OR_SALE'=>'Lease or sale'] as $v=>$l):?><option value="<?= $v ?>" <?= ($_GET['purpose']??'')===$v?'selected':'' ?>><?= $l ?></option><?php endforeach;?></select></label><label class="check"><input type="checkbox" name="available_now" value="1" <?= !empty($_GET['available_now'])?'checked':'' ?>> Available now</label><label>Available by<input type="date" name="available_from" value="<?= e((string)($_GET['available_from']??'')) ?>"></label></details>
<details open><summary>Equipment</summary><?php foreach(['category'=>['Category',$categories],'type'=>['Type',$types],'oem'=>['Make / OEM',$oems],'model'=>['Model',$models]] as $name=>[$label,$options]):?><label><?= $label ?><select name="<?= $name ?>"><option value="">All <?= strtolower($label) ?></option><?php foreach($options as $option):?><option value="<?= e($option['id']) ?>" <?= ($_GET[$name]??'')===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select></label><?php endforeach;?></details>
<details open id="location-filters"><summary>Locations</summary><label>Country<input name="country" value="<?= e((string)($_GET['country']??'')) ?>" placeholder="All countries"></label><label>State / region<input name="state" value="<?= e((string)($_GET['state']??'')) ?>" placeholder="All regions"></label><label>City<input name="city" value="<?= e((string)($_GET['city']??'')) ?>" placeholder="All cities"></label></details>
<details><summary>Compliance</summary><label class="check"><input type="checkbox" name="certified" value="1" <?= !empty($_GET['certified'])?'checked':'' ?>> Certification currently valid</label><label>Certification<select name="compliance"><option value="">Any</option><option value="AVAILABLE_ON_REQUEST" <?= ($_GET['compliance']??'')==='AVAILABLE_ON_REQUEST'?'selected':'' ?>>Available on request</option><option value="VALID" <?= ($_GET['compliance']??'')==='VALID'?'selected':'' ?>>Valid</option><option value="EXPIRED" <?= ($_GET['compliance']??'')==='EXPIRED'?'selected':'' ?>>Expired</option></select></label><label>Certification type<input name="certification_type" value="<?= e((string)($_GET['certification_type']??'')) ?>"></label><label class="check"><input type="checkbox" name="recently_inspected" value="1" <?= !empty($_GET['recently_inspected'])?'checked':'' ?>> Inspected in the last 90 days</label></details>
<details><summary>Pricing</summary><label>Maximum daily rate<input type="number" name="max_daily" min="0" value="<?= e((string)($_GET['max_daily']??'')) ?>"></label><label>Maximum monthly rate<input type="number" name="max_monthly" min="0" value="<?= e((string)($_GET['max_monthly']??'')) ?>"></label><label>Maximum sale price<input type="number" name="max_sale" min="0" value="<?= e((string)($_GET['max_sale']??'')) ?>"></label><label class="check"><input type="checkbox" name="request_quote" value="1" <?= !empty($_GET['request_quote'])?'checked':'' ?>> Request quote</label><label class="check"><input type="checkbox" name="negotiable" value="1" <?= !empty($_GET['negotiable'])?'checked':'' ?>> Negotiable</label><label class="check"><input type="checkbox" name="operator_included" value="1" <?= !empty($_GET['operator_included'])?'checked':'' ?>> Operator included</label></details><button class="market-button">Apply filters</button></form></aside>
<section class="market-results"><header><div><p class="market-kicker"><?= $marketView==='requests'?'EQUIPMENT REQUIRED':($marketView==='equipment'?'AVAILABLE EQUIPMENT':'LIVE MARKETPLACE') ?></p><h2><?= count($marketItems) ?> marketplace item<?= count($marketItems)===1?'':'s' ?></h2></div></header>
<?php if(isset($problem)):?><div class="market-empty" role="alert"><h2>Marketplace unavailable</h2><p><?= e($problem) ?></p></div><?php elseif(!$marketItems):?><div class="market-empty"><h2>No equipment or requests matched your search.</h2><p>Try clearing a filter or check back when new marketplace items are published.</p><a href="marketplace">Clear filters</a></div><?php else:?><div class="market-grid"><?php foreach($marketItems as $marketItem):?><?php if($marketItem['kind']==='request'){$request=$marketItem['item'];require __DIR__.'/includes/request-card.php';}else{$listing=$marketItem['item'];require __DIR__.'/includes/marketplace-card.php';}?><?php endforeach;?></div><nav class="market-pagination" aria-label="Results pages"><span>Page <?= $page ?> of <?= max(1,(int)ceil($total/12)) ?></span><div><?php if($page>1):?><a href="?<?= e(http_build_query([...$_GET,'page'=>$page-1])) ?>">Previous</a><?php endif;?><?php if($offset+12<$total):?><a href="?<?= e(http_build_query([...$_GET,'page'=>$page+1])) ?>">Next</a><?php endif;?></div></nav><?php endif;?></section></div>
<?php require __DIR__.'/includes/marketplace-footer.php';?>
