<?php
declare(strict_types=1);require __DIR__.'/app/marketplace.php';require_once __DIR__.'/app/xinng.php';header('Cache-Control: no-store, private');
$destination='marketplace-manage?view=listings';$successMessage='Marketplace changes saved.';
try{
 if($_SERVER['REQUEST_METHOD']!=='POST'){header('Allow: POST');throw new DomainException('Use POST for marketplace changes.',405);}
 $user=require_verified();verify_csrf();if(!marketplace_can_publish($user))throw new DomainException('Your role cannot manage marketplace listings.',403);
 $action=(string)($_POST['action']??'');$pdo=db();$pdo->beginTransaction();
 if($action==='listing.start'){
  $assetId=marketplace_text($_POST,'asset_id',36,true);$id=marketplace_start_listing($user,$assetId);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
}elseif(in_array($action,['listing.create','listing.update'],true)){
  $destination=$action==='listing.update'?'marketplace-manage?view=edit&id='.rawurlencode((string)($_POST['id']??'')):'marketplace-manage?view=create';
  $id=$action==='listing.update'?marketplace_text($_POST,'id',36,true):uuid();$before=$action==='listing.update'?marketplace_owned_listing($user,$id,true):null;
  if($before){$asset=operation_equipment($user,$before['asset_id']);$assetId=$asset['id'];$classification=equipment_inline_catalog($user,$_POST);}
  else{
   $mode=marketplace_enum($_POST,'asset_mode',['EXISTING','NEW']);
   if($mode==='EXISTING'){$asset=operation_equipment($user,marketplace_text($_POST,'asset_id',36,true));$assetId=$asset['id'];$classification=equipment_inline_catalog($user,$_POST);}
   else{
    $assetId=uuid();$unit=equipment_unit($user,marketplace_text($_POST,'unit_id',36));$name=marketplace_text($_POST,'equipment_name',255,true);$aid=marketplace_text($_POST,'asset_code',100,true);
    $existing=rows('SELECT id FROM equipment WHERE owner_id=? AND asset_code=? AND archived_at IS NULL FOR UPDATE',[$user['owner_id'],$aid])[0]??null;
    if($existing){
     $asset=operation_equipment($user,$existing['id']);$assetId=$asset['id'];$classification=equipment_inline_catalog($user,$_POST);
     operation_audit($user,'marketplace.existing_asset_reused','equipment',$assetId,null,['asset_code'=>$aid,'submitted_name'=>$name]);
    }else{
     $assetId=marketplace_create_standard_asset($user,$unit,$aid,$name);
     $metadata=equipment_inline_catalog($user,$_POST);$classification=$metadata;equipment_apply_metadata($user,$assetId,$metadata);
    }
   }
  }
  if(!$before){$pdo->prepare('SELECT id FROM equipment WHERE id=? AND owner_id=? FOR UPDATE')->execute([$assetId,$user['owner_id']]);$existingListing=rows("SELECT id,listing_status FROM marketplace_listings WHERE asset_id=? AND organization_id=? AND listing_status<>'CLOSED' FOR UPDATE",[$assetId,$user['owner_id']])[0]??null;if($existingListing)throw new DomainException('This equipment is already listed. Continue or manage its existing '.strtolower($existingListing['listing_status']).' listing instead.',409);}
  $pdo->prepare('UPDATE equipment SET marketplace_only=0 WHERE id=? AND owner_id=?')->execute([$assetId,$user['owner_id']]);
  if(!empty($classification['type_id'])||!empty($classification['category_id']))equipment_apply_metadata($user,$assetId,$classification,false);
  $equipment=operation_equipment($user,$assetId);$submittedDescription=marketplace_text($_POST,'description',10000);if($submittedDescription!==null&&$submittedDescription!==trim((string)($equipment['long_description']??''))){$pdo->prepare('UPDATE equipment SET long_description=? WHERE id=? AND owner_id=?')->execute([$submittedDescription,$assetId,$user['owner_id']]);$equipment=operation_equipment($user,$assetId);}$oem=marketplace_oem($user,$_POST);$model=marketplace_model($user,$_POST,$oem,$equipment['type_id']);$specs=marketplace_specs(marketplace_text($_POST,'specifications',10000));$canonicalDescription=trim((string)($equipment['long_description']?:$equipment['short_description']?:''));
  $pdo->prepare('UPDATE equipment SET marketplace_oem_id=?,marketplace_oem_model_id=?,marketplace_specifications=? WHERE id=?')->execute([$oem,$model,json_encode($specs,JSON_THROW_ON_ERROR),$assetId]);
  $purpose=marketplace_enum($_POST,'purpose',['LEASE','SALE','LEASE_OR_SALE']);$status=marketplace_enum($_POST,'marketplace_status',['AVAILABLE','RESERVED','MOBILIZING','IN_USE','MAINTENANCE','OFFLINE','BLOCKED'],'AVAILABLE');
  $visibility=marketplace_enum($_POST,'visibility',['PUBLIC','NETWORK','PRIVATE'],'PUBLIC');$price=marketplace_enum($_POST,'price_visibility',['PUBLIC','REQUEST_QUOTE'],'REQUEST_QUOTE');$compliance=marketplace_enum($_POST,'compliance_status',['NOT_PROVIDED','AVAILABLE_ON_REQUEST','VALID','EXPIRED'],'NOT_PROVIDED');
  $fields=[$equipment['name'],$canonicalDescription,$purpose,$status,$visibility,(int)!empty($_POST['public_asset_code']),marketplace_text($_POST,'country',100,true),marketplace_text($_POST,'state_region',100,true),marketplace_text($_POST,'city',100,true),marketplace_text($_POST,'available_from',10),$price,$compliance,marketplace_text($_POST,'certification_type',150),marketplace_text($_POST,'certification_valid_until',10),marketplace_text($_POST,'last_inspected_on',10),json_encode($specs,JSON_THROW_ON_ERROR)];
  if($before)$pdo->prepare('UPDATE marketplace_listings SET title=?,description=?,purpose=?,marketplace_status=?,visibility=?,public_asset_code=?,country=?,state_region=?,city=?,available_from=?,price_visibility=?,compliance_status=?,certification_type=?,certification_valid_until=?,last_inspected_on=?,public_specifications=? WHERE id=?')->execute([...$fields,$id]);
  else $pdo->prepare('INSERT INTO marketplace_listings(id,asset_id,organization_id,created_by,title,description,purpose,marketplace_status,visibility,public_asset_code,country,state_region,city,available_from,price_visibility,compliance_status,certification_type,certification_valid_until,last_inspected_on,public_specifications) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$assetId,$user['owner_id'],$user['id'],...$fields]);
  $equipmentPhoto=marketplace_text($_POST,'equipment_photo_id',36);
  if($equipmentPhoto&&!rows('SELECT id FROM marketplace_listing_media WHERE listing_id=? AND equipment_photo_id=?',[$id,$equipmentPhoto])){
   $photo=rows('SELECT id FROM equipment_photos WHERE id=? AND equipment_id=?',[$equipmentPhoto,$assetId])[0]??null;if(!$photo)throw new DomainException('Choose a photo belonging to this equipment.',422);
   $primary=!rows("SELECT id FROM marketplace_listing_media WHERE listing_id=? AND media_type='IMAGE' AND is_primary=1",[$id]);
   $pdo->prepare("INSERT INTO marketplace_listing_media(id,listing_id,equipment_photo_id,media_type,title,visibility,is_primary) VALUES(?,?,?,'IMAGE','Equipment photo','PUBLIC',?)")->execute([uuid(),$id,$equipmentPhoto,(int)$primary]);
  }
  if(in_array($purpose,['LEASE','LEASE_OR_SALE'],true)){
   $currency=strtoupper(marketplace_text($_POST,'lease_currency',3)??'NGN');if(!preg_match('/^[A-Z]{3}$/',$currency))throw new DomainException('Use a three-letter lease currency.',422);
   $duration=marketplace_enum($_POST,'duration_unit',['HOUR','DAY','WEEK','MONTH'],'DAY');$rate=marketplace_number($_POST,'lease_rate');$minimum=max(1,marketplace_integer($_POST,'minimum_duration',1));$operator=(int)!empty($_POST['operator_included']);$consumables=(int)!empty($_POST['consumables_included']);
   $mobilization=marketplace_option($_POST,'mobilization_option','mobilization','TO_BE_AGREED');$demobilization=marketplace_option($_POST,'demobilization_option','demobilization','TO_BE_AGREED');$maintenance=marketplace_option($_POST,'maintenance_option','maintenance','CASE_BY_CASE');$insurance=marketplace_option($_POST,'insurance_option','insurance','TO_BE_AGREED');
   foreach([['mobilization',$mobilization],['demobilization',$demobilization],['maintenance',$maintenance],['insurance',$insurance]] as [$term,$choice])if($choice==='CUSTOM'&&!marketplace_text($_POST,$term.'_details',5000))throw new DomainException('Enter the custom '.$term.' terms.',422);
   $legacy=['daily_rate'=>null,'weekly_rate'=>null,'monthly_rate'=>null];if($rate!==null&&isset($legacy[strtolower($duration).'_rate']))$legacy[strtolower($duration).'_rate']=$rate;
   $lease=[$legacy['daily_rate'],$legacy['weekly_rate'],$legacy['monthly_rate'],null,$currency,$rate,$minimum,null,$duration,marketplace_number($_POST,'security_deposit'),(int)!empty($_POST['lease_negotiable']),$operator,marketplace_number($_POST,'operator_rate'),$consumables,$consumables,marketplace_text($_POST,'consumables_details',500),0,0,$maintenance,marketplace_text($_POST,'maintenance_details',5000),$insurance,marketplace_text($_POST,'insurance_details',5000),null,$mobilization,marketplace_text($_POST,'mobilization_details',5000),$demobilization,marketplace_text($_POST,'demobilization_details',5000)];
   $pdo->prepare('INSERT INTO marketplace_lease_terms(listing_id,daily_rate,weekly_rate,monthly_rate,project_rate,currency,rate,minimum_duration,maximum_duration,duration_unit,security_deposit,negotiable,operator_included,operator_rate,fuel_included,consumables_included,consumables_details,mobilization_included,demobilization_included,maintenance_option,maintenance_details,insurance_option,insurance_details,geographic_restrictions,mobilization_option,mobilization_custom,demobilization_option,demobilization_custom) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE daily_rate=VALUES(daily_rate),weekly_rate=VALUES(weekly_rate),monthly_rate=VALUES(monthly_rate),project_rate=NULL,currency=VALUES(currency),rate=VALUES(rate),minimum_duration=VALUES(minimum_duration),maximum_duration=NULL,duration_unit=VALUES(duration_unit),security_deposit=VALUES(security_deposit),negotiable=VALUES(negotiable),operator_included=VALUES(operator_included),operator_rate=VALUES(operator_rate),fuel_included=VALUES(fuel_included),consumables_included=VALUES(consumables_included),consumables_details=VALUES(consumables_details),mobilization_included=0,demobilization_included=0,maintenance_option=VALUES(maintenance_option),maintenance_details=VALUES(maintenance_details),insurance_option=VALUES(insurance_option),insurance_details=VALUES(insurance_details),mobilization_option=VALUES(mobilization_option),mobilization_custom=VALUES(mobilization_custom),demobilization_option=VALUES(demobilization_option),demobilization_custom=VALUES(demobilization_custom)')->execute([$id,...$lease]);
  }else $pdo->prepare('DELETE FROM marketplace_lease_terms WHERE listing_id=?')->execute([$id]);
  if(in_array($purpose,['SALE','LEASE_OR_SALE'],true)){
   $currency=strtoupper(marketplace_text($_POST,'sale_currency',3)??'NGN');if(!preg_match('/^[A-Z]{3}$/',$currency))throw new DomainException('Use a three-letter sale currency.',422);
   $payment=marketplace_option($_POST,'payment_terms','payment','TO_BE_AGREED');if($payment==='CUSTOM'&&!marketplace_text($_POST,'payment_terms_custom',5000))throw new DomainException('Enter the custom payment terms.',422);
   $sale=[marketplace_number($_POST,'asking_price'),$currency,(int)!empty($_POST['sale_negotiable']),$payment,marketplace_text($_POST,'payment_terms_custom',5000),(int)!empty($_POST['inspection_required']),marketplace_option($_POST,'sale_condition','sale_condition','AS_IS'),marketplace_option($_POST,'taxes_fees','taxes','TO_BE_AGREED'),marketplace_text($_POST,'sale_notes',5000)];
   $pdo->prepare('INSERT INTO marketplace_sale_terms(listing_id,asking_price,currency,negotiable,payment_terms,payment_terms_custom,inspection_allowed,`condition`,taxes_fees,sale_notes) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE asking_price=VALUES(asking_price),currency=VALUES(currency),negotiable=VALUES(negotiable),payment_terms=VALUES(payment_terms),payment_terms_custom=VALUES(payment_terms_custom),inspection_allowed=VALUES(inspection_allowed),`condition`=VALUES(`condition`),taxes_fees=VALUES(taxes_fees),sale_notes=VALUES(sale_notes)')->execute([$id,...$sale]);
  }else $pdo->prepare('DELETE FROM marketplace_sale_terms WHERE listing_id=?')->execute([$id]);
  marketplace_save_location_rules($user,$id,(string)($_POST['location_rules']??''));
  if(($_FILES['media']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)marketplace_media_upload($user,$id,$_FILES['media'],$_POST);
  operation_audit($user,$action,'listing',$id,$before,marketplace_owned_listing($user,$id));if(($_POST['workflow_action']??'review')==='draft'){$destination='marketplace-manage?view=listings';$successMessage='Listing saved as a draft. It has not been published.';}else{$issues=marketplace_publish_issues($user,$id);if($issues){$destination='marketplace-manage?view=edit&id='.rawurlencode($id);$warningMessage='Complete the required publishing information before preview: '.implode(' ',$issues);}else{$destination='marketplace-manage?view=preview&id='.rawurlencode($id);$successMessage='Draft saved. Review the listing before final publication.';}}
 }elseif($action==='media.add'){$id=marketplace_text($_POST,'id',36,true);marketplace_media_upload($user,$id,$_FILES['media']??[],$_POST);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
 }elseif($action==='media.external'){$id=marketplace_text($_POST,'id',36,true);marketplace_external_media($user,$id,$_POST);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
 }elseif($action==='media.link'){
  $id=marketplace_text($_POST,'id',36,true);$listing=marketplace_owned_listing($user,$id);$photoId=marketplace_text($_POST,'equipment_photo_id',36,true);
  if(!rows('SELECT id FROM equipment_photos WHERE id=? AND equipment_id=?',[$photoId,$listing['asset_id']]))throw new DomainException('Choose a photo belonging to this equipment.',422);
  $primary=!rows("SELECT id FROM marketplace_listing_media WHERE listing_id=? AND media_type='IMAGE' AND is_primary=1",[$id]);
  $pdo->prepare("INSERT IGNORE INTO marketplace_listing_media(id,listing_id,equipment_photo_id,media_type,title,visibility,is_primary) VALUES(?,?,?,'IMAGE','Equipment photo','PUBLIC',?)")->execute([uuid(),$id,$photoId,(int)$primary]);
  operation_audit($user,'marketplace.media_published','listing',$id,null,['equipment_photo_id'=>$photoId]);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
 }elseif($action==='availability.add'){
  $id=marketplace_text($_POST,'id',36,true);marketplace_owned_listing($user,$id);$start=marketplace_text($_POST,'start_date',10,true);$end=marketplace_text($_POST,'end_date',10,true);if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end)||$end<$start)throw new DomainException('Choose a valid availability date range.',422);$availability=marketplace_enum($_POST,'availability',['AVAILABLE','UNAVAILABLE']);$period=uuid();$pdo->prepare('INSERT INTO marketplace_availability_periods(id,listing_id,start_date,end_date,availability,note) VALUES(?,?,?,?,?,?)')->execute([$period,$id,$start,$end,$availability,marketplace_text($_POST,'note',255)]);operation_audit($user,'marketplace.availability_added','listing',$id,null,['period_id'=>$period,'start_date'=>$start,'end_date'=>$end,'availability'=>$availability]);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
 }elseif($action==='availability.delete'){
  $id=marketplace_text($_POST,'id',36,true);marketplace_owned_listing($user,$id);$period=marketplace_text($_POST,'period_id',36,true);$before=rows('SELECT * FROM marketplace_availability_periods WHERE id=? AND listing_id=?',[$period,$id])[0]??null;if(!$before)throw new DomainException('Availability period not found.',404);$pdo->prepare('DELETE FROM marketplace_availability_periods WHERE id=?')->execute([$period]);operation_audit($user,'marketplace.availability_removed','listing',$id,$before,['removed'=>true]);$destination='marketplace-manage?view=edit&id='.rawurlencode($id);
 }elseif($action==='listing.publish'){$id=marketplace_text($_POST,'id',36,true);marketplace_publish($user,$id);$createOpportunityQr=$id;$destination='marketplace-listing?id='.rawurlencode($id);
 }elseif(in_array($action,['listing.pause','listing.close'],true)){
  $id=marketplace_text($_POST,'id',36,true);$target=$action==='listing.pause'?'PAUSED':'CLOSED';marketplace_transition($user,$id,$target);$destination='marketplace-manage?view=listings';
 }elseif($action==='company.public'){
  if($user['role']!=='OWNER_ADMIN')throw new DomainException('Only the company owner can update the public profile.',403);
  $before=rows('SELECT * FROM owners WHERE id=?',[$user['owner_id']])[0];$values=[marketplace_text($_POST,'public_description',5000),marketplace_text($_POST,'public_country',100),marketplace_text($_POST,'public_state',100),marketplace_text($_POST,'public_city',100)];
  $pdo->prepare('UPDATE owners SET public_description=?,public_country=?,public_state=?,public_city=? WHERE id=?')->execute([...$values,$user['owner_id']]);operation_audit($user,$action,'owner',$user['owner_id'],$before,['public_description'=>$values[0],'public_country'=>$values[1],'public_state'=>$values[2],'public_city'=>$values[3]]);$destination='marketplace-company?id='.$user['owner_id'];
 }else throw new DomainException('Unknown marketplace action.',422);
 $pdo->commit();if(isset($createOpportunityQr)){try{xinng_opportunity_link($user,$createOpportunityQr);$successMessage='Marketplace opportunity published and its xin.ng QR is ready.';}catch(Throwable $qrError){error_log('Marketplace opportunity QR creation: '.$qrError->getMessage());$successMessage='Opportunity published, but its xin.ng QR could not be created: '.($qrError instanceof DomainException?$qrError->getMessage():'xin.ng is temporarily unavailable.');}}flash(isset($warningMessage)?'error':'success',$warningMessage??$successMessage);redirect($destination);
}catch(Throwable $error){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$code=$error instanceof DomainException?$error->getCode():500;if($error instanceof PDOException&&($error->errorInfo[1]??null)===1062){$code=409;$message=str_contains($error->getMessage(),'equipment_code')?'That Asset ID already belongs to equipment in your company. Select the existing equipment and try again.':'That marketplace record already exists.';}else $message=$error instanceof DomainException?$error->getMessage():'The marketplace change could not be saved.';if($message==='')$message='Check the listing fields and try again.';http_response_code($code);error_log('Marketplace action '.get_class($error).': '.$error->getMessage());flash('error',$message.' Nothing was published.');redirect($destination);}
