<?php
declare(strict_types=1);
require __DIR__.'/app/commercial.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    if(empty($_POST['terms_accepted']))throw new DomainException('Accept the Terms and Conditions to continue.',422);
    $items=commercial_items($_POST);$subtotal=array_sum(array_column($items,'base_amount'));$discountRate=max(0,min(100,(float)($_POST['document_discount_rate']??0)));$taxRate=max(0,min(100,(float)($_POST['document_tax_rate']??0)));$discount=round($subtotal*$discountRate/100,2);$tax=round(($subtotal-$discount)*$taxRate/100,2);$adjustment=(float)($_POST['adjustment_total']??0);
    $type=in_array($_POST['document_type']??'',['QUOTATION','INVOICE'],true)?$_POST['document_type']:'QUOTATION';
    $document=['document_type'=>$type,'document_number'=>commercial_text($_POST,'document_number',80,true),'issue_date'=>commercial_text($_POST,'issue_date',10,true),'due_date'=>$type==='INVOICE'?commercial_text($_POST,'end_date',10):null,'valid_until'=>$type==='QUOTATION'?commercial_text($_POST,'end_date',10):null,'currency'=>strtoupper(commercial_text($_POST,'currency',3,true)),'customer_po'=>commercial_text($_POST,'customer_po',150),'customer_reference'=>commercial_text($_POST,'customer_reference',150),'rfq_number'=>commercial_text($_POST,'rfq_number',150),'customer_name'=>commercial_text($_POST,'customer_name',255,true),'customer_address'=>commercial_text($_POST,'customer_address'),'customer_email'=>commercial_text($_POST,'customer_email',255),'customer_phone'=>commercial_text($_POST,'customer_phone',50),'customer_tin'=>'','payment_terms'=>commercial_text($_POST,'payment_terms'),'notes'=>commercial_text($_POST,'notes'),'subtotal'=>$subtotal,'discount_total'=>$discount,'tax_total'=>$tax,'adjustment_total'=>$adjustment,'grand_total'=>$subtotal-$discount+$tax+$adjustment,'items'=>$items];
    $signatoryName=commercial_text($_POST,'signatory_name',255);$signatoryTitle=commercial_text($_POST,'signatory_title',255);
    $issuer=['legal_name'=>commercial_text($_POST,'issuer_name',255,true),'registered_address'=>commercial_text($_POST,'issuer_address'),'email'=>commercial_text($_POST,'issuer_email',255),'phone'=>commercial_text($_POST,'issuer_phone',50),'website'=>commercial_text($_POST,'issuer_website',255),'tin'=>'','rc_number'=>'','authorized_signatory'=>$signatoryName,'authorized_signatory_title'=>$signatoryTitle];
    $bank=['bank_name'=>'Payment information','account_name'=>'','account_number'=>commercial_text($_POST,'bank_details'),'currency'=>$document['currency']];
    $logoMime=null;$logoData=null;$logoInput=(string)($_POST['brand_logo_data']??'');
    if($logoInput&&preg_match('#^data:(image/(?:png|jpeg));base64,(.+)$#s',$logoInput,$match)){$decoded=base64_decode($match[2],true);if($decoded!==false&&strlen($decoded)<=5*1024*1024){$logoMime=$match[1];$logoData=$decoded;$issuer['logo_data']=$logoInput;}}
    [$signatureMime,$signatureData]=commercial_brand_file($_FILES['signature']??[],'Signature');
    if($signatureData)$issuer['signature_data']='data:'.$signatureMime.';base64,'.base64_encode($signatureData);
    $payload=$_POST;unset($payload['csrf'],$payload['brand_logo_data']);$payload['items']=$items;$termsVersion='2026-09-28';$ip=(string)($_SERVER['REMOTE_ADDR']??'');
    db()->prepare('INSERT INTO public_commercial_submissions(id,session_reference,document_type,document_number,issuer_name,issuer_email,customer_name,customer_email,payload,logo_mime,logo_data,signature_mime,signature_data,terms_version,terms_accepted_at,marketing_consent,ip_hash,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),1,?,?)')->execute([uuid(),hash('sha256',session_id()),$type,$document['document_number'],$issuer['legal_name'],$issuer['email'],$document['customer_name'],$document['customer_email'],json_encode($payload,JSON_THROW_ON_ERROR),$logoMime,$logoData,$signatureMime,$signatureData,$termsVersion,$ip!==''?hash('sha256',$ip.'|public-commercial'):null,mb_substr((string)($_SERVER['HTTP_USER_AGENT']??''),0,500)]);
    $_SESSION['public_commercial_draft']=['document'=>$document,'issuer'=>$issuer,'bank'=>$bank,'brand'=>null,'saved_at'=>time()];
    redirect('public-commercial-document');
}
$data=$_SESSION['public_commercial_draft']??null;if(!$data)redirect('quote-invoice-generator');
if(!empty($_GET['download'])){$pdf=commercial_pdf($data);header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]/','-',$data['document']['document_number']).'.pdf"');echo $pdf;exit;}
$d=$data['document'];$issuer=$data['issuer'];$bank=$data['bank'];
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title><?= e($d['document_number']) ?></title><link rel="stylesheet" href="assets/css/commercial-document.css?v=<?= filemtime(APP_ROOT.'/assets/css/commercial-document.css') ?>"><link rel="stylesheet" href="assets/css/commercial-signatory.css?v=<?= filemtime(APP_ROOT.'/assets/css/commercial-signatory.css') ?>"></head>
<body><main class="paper">
<header><div class="issuer"><?php if(!empty($issuer['logo_data'])):?><img class="document-logo" src="<?= e($issuer['logo_data']) ?>" alt=""><?php endif;?><h1><?= e($issuer['legal_name']) ?></h1><p><?= nl2br(e($issuer['registered_address'])) ?><br><?= e($issuer['email'].' · '.$issuer['phone']) ?><br><?= e($issuer['website']) ?></p></div><div class="doc-title"><strong><?= e($d['document_type']) ?></strong><span><?= e($d['document_number']) ?></span><small>Date: <?= e($d['issue_date']) ?><br><?= $d['document_type']==='INVOICE'?'Due':'Valid until' ?>: <?= e($d['due_date']?:$d['valid_until']) ?></small></div></header>
<section class="parties"><div><span>BILL TO</span><h2><?= e($d['customer_name']) ?></h2><p><?= nl2br(e($d['customer_address'])) ?></p></div><div><span>REFERENCES</span><p>PO Number: <?= e($d['customer_po']) ?><br>Customer Reference No.: <?= e($d['customer_reference']) ?><br>RFQ Number: <?= e($d['rfq_number']) ?></p></div></section>
<table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Duration</th><th>Rate</th><th>Tax</th><th>Total</th></tr></thead><tbody><?php foreach($d['items'] as $item):?><tr><td><?= e($item['description']) ?></td><td><?= e((string)$item['quantity']) ?></td><td><?= e($item['unit']) ?></td><td><?= e((string)$item['duration']) ?></td><td><?= number_format((float)$item['rate'],2) ?></td><td><?= e((string)$item['tax_rate']) ?>%</td><td><?= number_format((float)$item['total_amount'],2) ?></td></tr><?php endforeach;?></tbody></table>
<section class="summary"><div><h3>Payment terms</h3><p><?= nl2br(e($d['payment_terms'])) ?></p><h3>Payment information</h3><p><?= nl2br(e($bank['account_number'])) ?></p></div><dl><dt>Subtotal</dt><dd><?= number_format((float)$d['subtotal'],2) ?></dd><dt>Discount</dt><dd><?= number_format((float)$d['discount_total'],2) ?></dd><dt>Tax</dt><dd><?= number_format((float)$d['tax_total'],2) ?></dd><dt>Total</dt><dd><?= e($d['currency'].' '.number_format((float)$d['grand_total'],2)) ?></dd></dl></section>
<footer><p><?= nl2br(e($d['notes'])) ?></p><?php if(!empty($issuer['signature_data'])):?><img class="signature-document-image" src="<?= e($issuer['signature_data']) ?>" alt="Authorized signature"><?php endif;?><strong><?= e($issuer['authorized_signatory']) ?></strong><span><?= e($issuer['authorized_signatory_title']) ?><?= $issuer['authorized_signatory_title']?' · ':'' ?>Authorized signatory</span></footer>
</main><div class="public-document-actions"><a href="public-commercial-document?download=1">Download PDF</a><button onclick="window.print()">Print</button><a href="commercial-import-public">Sign in & save</a><a href="quote-invoice-generator">Edit / start again</a></div><style>.public-document-actions{position:fixed;right:22px;top:22px;display:grid;gap:8px}.public-document-actions a,.public-document-actions button{padding:10px 14px;border:0;border-radius:5px;background:#173b64;color:#fff;text-decoration:none;text-align:center;font:700 12px Arial}@media print{.public-document-actions{display:none}}</style></body></html>
