<?php
declare(strict_types=1);
require __DIR__.'/app/qhse.php';
$token=trim((string)($_GET['token']??''));$record=null;
if(preg_match('/^[a-f0-9]{32}$/',$token))$record=rows("SELECT c.*,o.name company_name,cu.name customer_name,GROUP_CONCAT(e.name ORDER BY e.name SEPARATOR ', ') equipment_names FROM qhse_certificates c JOIN owners o ON o.id=c.owner_id JOIN commercial_customers cu ON cu.id=c.customer_id LEFT JOIN qhse_certificate_equipment ce ON ce.certificate_id=c.id LEFT JOIN equipment e ON e.id=ce.equipment_id WHERE c.verification_token=? AND c.status IN ('ISSUED','REVOKED','SUPERSEDED') GROUP BY c.id",[$token])[0]??null;
$status=$record?qhse_certificate_display_status($record):null;$expiryMoment=$record&&!empty($record['expiry_date'])?(new DateTimeImmutable($record['expiry_date'],new DateTimeZone('UTC')))->modify('+1 day')->format(DateTimeInterface::ATOM):null;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Certificate verification · Nonagon</title><link rel="stylesheet" href="assets/css/operations.css"><link rel="stylesheet" href="assets/css/qhse-certificates.css"><link rel="stylesheet" href="assets/css/certificate-print.css"></head><body class="verification-page"><main>
<?php if(!$record):?><span class="verify-symbol invalid">!</span><h1>Certificate not verified</h1><p>The verification code is invalid or the certificate has not been issued.</p><?php else:?>
<span class="verify-symbol <?= $status==='REVOKED'?'invalid':'valid' ?>">✓</span><span class="eyebrow">Nonagon certificate verification</span><h1><?= e($record['certificate_number']) ?></h1><p>This record was issued by <strong><?= e($record['company_name']) ?></strong>.</p>
<?php if($expiryMoment):?><section class="certificate-countdown" data-certificate-countdown data-expiry="<?= e($expiryMoment) ?>" data-status="<?= e($status) ?>" aria-live="polite" style="display:grid;gap:5px;margin:18px 0;padding:16px;border:1px solid #b7e2c8;border-radius:8px;background:#eef8f2;color:#075d3a"><span style="font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase">Time until certificate expires</span><strong data-countdown-value style="font-size:24px">Calculating…</strong><small>Expires <?= e($record['expiry_date']) ?></small></section><?php endif;?>
<dl><div><dt>Status</dt><dd><?= qhse_status_badge($status) ?></dd></div><div><dt>Certificate type</dt><dd><?= e(qhse_certificate_type_label($record['certificate_type'])) ?></dd></div><div><dt>Customer</dt><dd><?= e($record['customer_name']) ?></dd></div><div><dt>Equipment</dt><dd><?= e($record['equipment_names']) ?></dd></div><div><dt>Issue date</dt><dd><?= e($record['issue_date']) ?></dd></div><div><dt>Expiry</dt><dd><?= e($record['expiry_date']?:'No expiry') ?></dd></div><div><dt>Result</dt><dd><?= e($record['result']) ?></dd></div></dl><small>Verification confirms the platform record and its current status. It does not independently certify technical suitability.</small><?php endif;?></main>
<script>(()=>{const box=document.querySelector('[data-certificate-countdown]');if(!box)return;const value=box.querySelector('[data-countdown-value]'),target=new Date(box.dataset.expiry).getTime(),status=box.dataset.status;const expiredStyle=()=>{box.style.background='#fff1f0';box.style.borderColor='#f2b8b5';box.style.color='#9f201a'};const render=()=>{if(status==='REVOKED'||status==='SUPERSEDED'){value.textContent=status==='REVOKED'?'Certificate revoked':'Certificate superseded';expiredStyle();return}const difference=target-Date.now(),absolute=Math.abs(difference),days=Math.floor(absolute/86400000),hours=Math.floor(absolute%86400000/3600000);value.textContent=difference<=0?`Expired ${days} days ${hours} hours ago`:`${days} days ${hours} hours`;if(difference<=0)expiredStyle()};render();setInterval(render,60000)})();</script>
</body></html>
