<?php
declare(strict_types=1);
require __DIR__.'/app/qhse.php';
$user=require_verified();$live=qhse_certificate($user,qhse_text($_GET,'id',36,true));
$snapshot=$live['issued_snapshot']?json_decode($live['issued_snapshot'],true):qhse_certificate_snapshot($user,$live);$c=$snapshot['certificate']??$live;$brand=$snapshot['brand']??null;$signatories=$snapshot['signatories']??[];$technical=json_decode((string)$c['technical_data'],true)?:[];
$items=$c['pressure_items']??$live['pressure_items']??[];if(!$items)$items=$c['equipment']??$live['equipment'];$references=$c['references']??$live['references'];$reference=$references[0]??[];$trace=json_decode((string)($reference['traceability_data']??'{}'),true)?:[];$sign=[];foreach($signatories as $entry)$sign[$entry['signatory_role']]=$entry;$measure=fn(string $key):string=>qhse_technical_value($technical[$key]??'');$durationUnit=['DAY'=>'day','WEEK'=>'week','MONTH'=>'month','YEAR'=>'year'][$c['validity_unit']??'']??null;$dueDate=!empty($c['test_date'])&&$durationUnit&&(int)($c['validity_duration']??0)>0?(new DateTimeImmutable($c['test_date'],new DateTimeZone('UTC')))->modify('+'.(int)$c['validity_duration'].' '.$durationUnit)->format('Y-m-d'):'—';
$signatureDate=substr((string)($c['created_at']??$live['created_at']??''),0,10);
$verificationUrl=base_url('qhse-certificate-verify?token='.$c['verification_token']);$shortUrl=(string)($live['xinng_short_url']??'');$qrCodeUrl='https://api.qrserver.com/v1/create-qr-code/?size=180x180&margin=0&data='.rawurlencode($verificationUrl);
$signatureImages=static function(array $entry,string $label):string{$usage=$entry['asset_usage']??'BOTH';$html='';if(in_array($usage,['SIGNATURE','BOTH'],true)&&!empty($entry['signature_data']))$html.='<img src="data:'.e($entry['signature_mime']).';base64,'.e($entry['signature_data']).'" alt="'.e($label).' signature">';if(in_array($usage,['STAMP','BOTH'],true)&&!empty($entry['stamp_data']))$html.='<img src="data:'.e($entry['stamp_mime']).';base64,'.e($entry['stamp_data']).'" alt="'.e($label).' stamp">';return $html;};
$technicianSign=$sign['TECHNICIAN']??[];$clientSign=$sign['CLIENT_REPRESENTATIVE']??[];$signatureSection='<section class="pc-signatures"><div><b>FOR '.e(strtoupper($brand['company_name']??$user['company_name'])).'</b><p>Name: '.e($c['technician_name']??$technicianSign['signatory_name']??'').'</p>'.$signatureImages($technicianSign,'Inspector').'<p>Date: '.e($technicianSign['signed_at']??$signatureDate).'</p></div><div><b>CLIENT\'S REPRESENTATIVE</b><p>Name: '.e($c['client_representative']??'').'</p>'.$signatureImages($clientSign,'Client').'<p>Date: '.e($clientSign['signed_at']??$signatureDate).'</p></div></section><p class="pc-note">';
ob_start(static fn(string $html):string=>preg_replace('/<section class="pc-signatures">.*?<\/section><p class="pc-note">/s',$signatureSection,$html,1)??$html);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($c['certificate_number']) ?></title><link rel="stylesheet" href="assets/css/certificate-print.css"><style>
.pressure-certificate{font-family:Georgia,"Times New Roman",serif;color:#182235}.pc-border{border:1.5px solid #4b5563}.pc-head{display:grid;grid-template-columns:1fr 2fr 1fr;align-items:center;border-bottom:1px solid #6b7280;min-height:105px}.pc-head>div{padding:12px}.pc-head img{max-height:78px;max-width:100%}.pc-brand{text-align:center;font-family:Arial,sans-serif}.pc-brand strong{display:block;font-size:24px;color:#087cb5}.pc-brand span{font-weight:700;color:#e11d2e}.pc-reg{text-align:right;font-size:11px;display:flex;align-items:center;justify-content:flex-end;gap:8px}.pc-reg span{overflow-wrap:anywhere}.pc-reg .pc-qr{width:64px;height:64px;max-height:none;border:1px solid #9ca3af;padding:3px;background:#fff;flex:0 0 auto}.pc-meta{display:grid;grid-template-columns:1fr 1fr}.pc-meta div{display:grid;grid-template-columns:115px 1fr;border-bottom:1px solid #9ca3af}.pc-meta div:nth-child(odd){border-right:1px solid #9ca3af}.pc-meta span,.pc-meta strong{padding:5px 8px}.pc-title{text-align:center;font-size:19px;border-bottom:1px solid #9ca3af;padding:7px;margin:0}.pc-body{padding:16px}.pc-line{display:grid;grid-template-columns:245px 1fr;margin:8px 0}.pc-line b{font-weight:700}.pc-table{width:100%;border-collapse:collapse;margin:10px 0}.pc-table th,.pc-table td{border:1px solid #9ca3af;padding:6px;text-align:left}.pc-section{font-weight:700;margin:14px 0 5px;text-transform:uppercase}.pc-result{border:2px solid #182235;padding:9px;margin-top:12px}.pc-signatures{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-top:18px}.pc-signatures>div{min-height:95px}.pc-signatures img{display:block;max-height:48px;max-width:150px}.pc-note{font-size:11px;color:#4b5563;margin-top:12px}@media print{.print-action{display:none}.pressure-certificate{margin:0}.pc-border{break-inside:avoid}.pc-qr{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body><main class="print-certificate pressure-certificate"><div class="pc-border"><section class="pc-head"><div><?php if(!empty($brand['logo_data'])):?><img src="data:<?= e($brand['logo_mime']) ?>;base64,<?= e($brand['logo_data']) ?>" alt="Logo"><?php endif;?></div><div class="pc-brand"><strong><?= e($brand['company_name']??$user['company_name']) ?></strong><span>QUALITY &amp; INSPECTION SERVICES</span></div><div class="pc-reg"><span><?= e($c['nuprc_number']??'') ?></span><img class="pc-qr" src="<?= e($qrCodeUrl) ?>" alt="Scan to verify certificate"></div></section>
<section class="pc-meta"><div><span>COMPANY</span><strong><?= e($c['customer_name']) ?></strong></div><div><span>REPORT NO.</span><strong><?= e($c['certificate_number']) ?></strong></div><div><span>LOCATION</span><strong><?= e($c['location']?:'—') ?></strong></div><div><span>TEST DATE</span><strong><?= e($c['test_date']?:'—') ?></strong></div><div><span>PROCEDURE</span><strong><?= e($c['procedure_reference']?:'—') ?></strong></div><div><span>DUE DATE</span><strong><?= e($dueDate) ?></strong></div><div><span>STANDARD</span><strong><?= e($c['standard_reference']?:'—') ?></strong></div></section><h1 class="pc-title">PRESSURE TEST CERTIFICATE</h1>
<section class="pc-body"><div class="pc-line"><b>TYPE OF INSPECTION</b><strong>: <?= e($c['inspection_test_type']?:'Hydrostatic Pressure Test') ?></strong></div><div class="pc-line"><span>Equipment Tested</span><strong>: <?= e(implode(', ',array_map(fn($item)=>(string)($item['item_name']??$item['name']??$item['description']??'—'),$items))) ?></strong></div><p class="pc-section">Tested items</p><table class="pc-table"><thead><tr><th>Description</th><th>ID Number</th><th>Range</th><th>Test pressure</th></tr></thead><tbody><?php foreach($items as $item):?><tr><td><?= e($item['item_name']??$item['name']??$item['description']??'—') ?></td><td><?= e($item['asset_code']??$item['aid']??'—') ?></td><td><?= e($item['range_text']??$item['range']??'—') ?></td><td><?= e($item['test_pressure']??'—') ?></td></tr><?php endforeach;?></tbody></table>
<p class="pc-section">Reference equipment</p><table class="pc-table"><thead><tr><th>Description</th><th>ID Number</th><th>Range</th><th>Calibration certificate number</th></tr></thead><tbody><?php foreach($references as $reference):$refTrace=json_decode((string)($reference['traceability_data']??'{}'),true)?:[];?><tr><td><?= e($reference['name']??$refTrace['description']??'—') ?></td><td><?= e($reference['asset_code']??'—') ?></td><td><?= e(trim(($refTrace['lower_value']??'').' - '.($refTrace['upper_value']??'').' '.($refTrace['unit']??''),' -')?:'—') ?></td><td><?= e($refTrace['calibration_certificate_number']??'—') ?></td></tr><?php endforeach;?></tbody></table>
<p class="pc-section">Test conditions</p><div class="pc-line"><span>Test medium</span><strong>: <?= e((string)($technical['test_medium']??'—')) ?></strong></div><div class="pc-line"><span>Proof test pressure</span><strong>: <?= e($measure('proof_pressure')?:'—') ?></strong></div><div class="pc-line"><span>Ram pressure</span><strong>: <?= e($measure('ram_pressure')?:'—') ?></strong></div><div class="pc-line"><span>Final hold time</span><strong>: <?= e($measure('final_hold_time')?:'—') ?></strong></div><div class="pc-result"><b>TEST RESULT: <?= e((string)($technical['overall_result']??$c['result']??'—')) ?></b><p><?= nl2br(e((string)($technical['result_statement']??'No result narrative recorded.'))) ?></p></div>
<section class="pc-signatures"><div><b>FOR <?= e(strtoupper($brand['company_name']??$user['company_name'])) ?></b><p>Name: <?= e($c['technician_name']??$sign['TECHNICIAN']['signatory_name']??'—') ?></p><?php if(!empty($sign['TECHNICIAN']['signature_data'])):?><img src="data:<?= e($sign['TECHNICIAN']['signature_mime']) ?>;base64,<?= e($sign['TECHNICIAN']['signature_data']) ?>" alt="Inspector signature"><?php endif;?><p>Date: <?= e($c['signoff_date']?:'—') ?></p></div><div><b>CLIENT'S REPRESENTATIVE</b><p>Name: <?= e($c['client_representative']?:'—') ?></p><?php if(!empty($sign['CLIENT_REPRESENTATIVE']['signature_data'])):?><img src="data:<?= e($sign['CLIENT_REPRESENTATIVE']['signature_mime']) ?>;base64,<?= e($sign['CLIENT_REPRESENTATIVE']['signature_data']) ?>" alt="Client signature"><?php endif;?><p>Date: <?= e($c['signoff_date']?:'—') ?></p></div></section><p class="pc-note">Verification: <?= e($verificationUrl) ?><?php if($shortUrl!==''):?> · Short link: <a href="<?= e($shortUrl) ?>"><?= e($shortUrl) ?></a><?php endif;?></p></section></div></main><button class="print-action" onclick="window.print()">Print / Save PDF</button></body></html>
