<?php
declare(strict_types=1);
require __DIR__.'/app/qhse.php';
$user=require_verified();
$live=qhse_certificate($user,qhse_text($_GET,'id',36,true));
$snapshot=$live['issued_snapshot']?json_decode($live['issued_snapshot'],true):qhse_certificate_snapshot($user,$live);
$certificate=$snapshot['certificate']??$live;
$brand=$snapshot['brand']??null;
$signatories=$snapshot['signatories']??[];
$equipment=$certificate['equipment']??$live['equipment'];
$technical=json_decode((string)$certificate['technical_data'],true)?:[];
$overall=(string)($technical['overall_result']??$certificate['result']);
$comments=(string)($technical['comments']??$technical['remarks']??$certificate['remarks']??$certificate['observations']??'No additional comments.');
$tech=array_map('qhse_technical_value',array_filter($technical,fn($key)=>!in_array($key,['overall_result','comments','remarks'],true),ARRAY_FILTER_USE_KEY));
$approval=null;foreach($signatories as $signatory)if(($signatory['signatory_role']??'')==='APPROVER'){$approval=$signatory;break;}
$verifyUrl=base_url('qhse-certificate-verify?token='.$certificate['verification_token']);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($certificate['certificate_number']) ?></title><link rel="stylesheet" href="assets/css/certificate-print.css"></head><body><main class="print-certificate">
<section class="brand-header"><?php if(!empty($brand['header_data'])):?><img class="header-art" src="data:<?= e($brand['header_mime']) ?>;base64,<?= e($brand['header_data']) ?>" alt="Brand header"><?php else:?><header><div><?php if(!empty($brand['logo_data'])):?><img src="data:<?= e($brand['logo_mime']) ?>;base64,<?= e($brand['logo_data']) ?>" alt="Logo"><?php endif;?><strong><?= e($brand['company_name']??$user['company_name']) ?></strong></div><span>QUALITY CERTIFICATE</span></header><?php endif;?></section>
<section class="title"><p><?= e($certificate['certificate_number']) ?> · Revision <?= (int)($certificate['revision_number']??1) ?></p><h1><?= e($certificate['template_name']) ?></h1><h2><?= e($certificate['inspection_test_type']) ?></h2></section>
<section class="facts"><div><span>Customer</span><strong><?= e($certificate['customer_name']) ?></strong></div><div><span>Project / job</span><strong><?= e($certificate['project_job']?:'—') ?></strong></div><div><span>Test date / location</span><strong><?= e(($certificate['test_date']?:'—').' · '.($certificate['location']?:'—')) ?></strong></div><div><span>Issue / expiry</span><strong><?= e(($certificate['issue_date']?:'Draft').' / '.($certificate['expiry_date']?:'On issue')) ?></strong></div></section>
<h3>Equipment examined</h3><section class="equipment-and-stamp"><div class="equipment-table"><table><thead><tr><th>AID</th><th>Type</th><th>Manufacturer / Model</th><th>Serial / Connection</th></tr></thead><tbody><?php foreach($equipment as $asset):?><tr><td><?= e($asset['asset_code']??$asset['aid']??'—') ?></td><td><?= e($asset['type_name']??$asset['equipment_type']??'—') ?></td><td><?= e(trim(($asset['brand_name']??$asset['manufacturer']??'').' '.($asset['model_name']??$asset['model']??''))?:'—') ?></td><td><?= e(($asset['serial_no']??$asset['serial_number']??'—').' / '.($asset['connection_detail']??'—')) ?></td></tr><?php endforeach;?></tbody></table></div><aside class="approval-stamp"><span>Approval stamp</span><?php if(!empty($approval['stamp_data'])):?><img src="data:<?= e($approval['stamp_mime']) ?>;base64,<?= e($approval['stamp_data']) ?>" alt="Approval stamp"><?php else:?><small>No approval stamp</small><?php endif;?></aside></section>
<section class="outcome-and-verify"><div class="outcome"><div class="result"><span>Overall result</span><strong><?= e($overall) ?></strong></div><div class="outcome-copy"><div><h3>Procedure / standard</h3><p><?= e(($certificate['procedure_reference']?:'—').' · '.($certificate['standard_reference']?:'—')) ?></p></div><div><h3>Comments</h3><p><?= nl2br(e($comments)) ?></p></div></div></div><aside class="verification"><div class="verification-qr" aria-hidden="true"></div><span>VERIFY</span><strong><?= e(substr($certificate['verification_token'],0,8)) ?></strong><small><?= e($verifyUrl) ?></small></aside></section>
<h3>Test / calibration data</h3><dl><?php foreach($tech as $key=>$value):?><div><dt><?= e(ucwords(str_replace('_',' ',$key))) ?></dt><dd><?= e($value?:'—') ?></dd></div><?php endforeach;?></dl>
<section class="signatures"><?php foreach($signatories as $signatory):$role=($signatory['signatory_role']??'')==='APPROVER'?'Approval':ucwords(strtolower(str_replace('_',' ',$signatory['signatory_role'])));?><div><span><?= e($role) ?></span><?php if(!empty($signatory['signature_data'])):?><img class="saved-signature" src="data:<?= e($signatory['signature_mime']) ?>;base64,<?= e($signatory['signature_data']) ?>" alt="Signature"><?php endif;?><strong><?= e($signatory['library_name']??$signatory['signatory_name']??'—') ?></strong></div><?php endforeach;?></section>
<p class="legal"><?= e($certificate['legal_statement']) ?></p><?php if(!empty($brand['footer_data'])):?><img class="footer-art" src="data:<?= e($brand['footer_mime']) ?>;base64,<?= e($brand['footer_data']) ?>" alt="Brand footer"><?php endif;?></main><button class="print-action" onclick="window.print()">Print / Save PDF</button></body></html>
