<?php
declare(strict_types=1);
require __DIR__.'/app/qhse.php';
$user=require_verified();$pageTitle='QHSE';$active='qms';$problem=null;$state=null;
try{$state=qhse_overview($user);}catch(Throwable $error){$problem=$error instanceof DomainException?$error->getMessage():'QHSE information is temporarily unavailable.';if(!$error instanceof DomainException)error_log('QHSE: '.$error->getMessage());}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$problem){verify_csrf();$allowed=['summary','attention','quality','activity','kpi'];$prompt=in_array($_POST['prompt']??'',$allowed,true)?$_POST['prompt']:'summary';$_SESSION['qhse_assistant']=qhse_assistant_answer($state,$prompt);redirect('qms#assistant');}
$assistant=$_SESSION['qhse_assistant']??null;unset($_SESSION['qhse_assistant']);
require __DIR__.'/includes/operations-header.php';
?>
<header class="qhse-hero"><div><span class="eyebrow">Quality, Health, Safety &amp; Environment</span><h1>Management-system health</h1><p>A tenant-scoped view of compliance, operational evidence, risk and action. Totals are deterministic and source records remain in their owning modules.</p></div><div class="qhse-role"><span>Access</span><strong><?= e(implode(' · ',array_map(fn($r)=>ucwords(strtolower(str_replace('_',' ',$r))),$state['roles']??[]))) ?></strong></div></header>
<nav class="qhse-sections" aria-label="QHSE sections"><a aria-current="page" href="qms">Overview</a><a href="qhse-certificates">Certificates</a><a href="qhse-signatures">QHSE Settings</a><span>Quality</span><span>HSE</span><span>Environment</span><span>Audits</span><span>NCR &amp; CAPA</span><span>Risk &amp; MOC</span><span>Competence</span><span>Management Review</span></nav>
<?php if($problem):?><div class="notice error" role="alert"><?= e($problem) ?> <a href="qms">Retry</a></div><?php else:$m=$state['metrics'];$primary=['open_ncrs'=>['Open NCRs','Quality'],'capas_due'=>['CAPAs Due','Quality'],'certificates_expiring'=>['Certificates Expiring','Compliance'],'calibration_due'=>['Calibration Due','Assets'],'open_incidents'=>['Open Incidents','HSE'],'open_audit_findings'=>['Open Audit Findings','Audit'],'high_risks'=>['High Risks','Risk'],'pending_approvals'=>['Pending Approvals','Governance']];?>
<section aria-labelledby="qhse-position"><div class="section-heading"><div><span class="eyebrow">Live position</span><h2 id="qhse-position">QHSE overview</h2></div><small>As of <?= e(gmdate('d M Y, H:i')) ?> UTC</small></div><div class="qhse-kpis"><?php foreach($primary as $key=>$card):?><article class="qhse-kpi <?= in_array($key,['high_risks','open_incidents'],true)&&$m[$key]?'needs-attention':'' ?>"><span><?= e($card[1]) ?></span><strong><?= number_format((int)$m[$key]) ?></strong><h3><?= e($card[0]) ?></h3><small><?= $m[$key]?'Requires review':'No open records' ?></small></article><?php endforeach;?></div></section>
<div class="qhse-layout"><section class="panel qhse-attention"><div class="section-heading"><div><span class="eyebrow">Deterministic rules</span><h2>Requires attention</h2></div><span class="count-pill"><?= count($state['attention']) ?></span></div><?php if(!$state['attention']):?><div class="qhse-empty"><?= operation_icon('check') ?><h3>No urgent QHSE exceptions</h3><p>No current due-date, approval, or high-risk rule is triggered.</p></div><?php else:?><div class="attention-list"><?php foreach($state['attention'] as $item):?><article class="attention-item severity-<?= e($item['severity']) ?>"><strong><?= number_format($item['count']) ?></strong><div><h3><?= e($item['title']) ?></h3><p><?= e($item['copy']) ?></p><small><?= e($item['area']) ?></small></div></article><?php endforeach;?></div><?php endif;?></section>
<section class="panel qhse-activity"><div class="section-heading"><div><span class="eyebrow">Traceability</span><h2>QHSE activity</h2></div></div><?php if(!$state['activity']):?><div class="qhse-empty"><?= operation_icon('activity') ?><h3>No QHSE activity yet</h3><p>Issued, approved, closed and reported events will appear here.</p></div><?php else:?><ol class="activity-feed"><?php foreach($state['activity'] as $event):?><li><span class="activity-dot"></span><div><div><span class="domain-tag"><?= e(ucfirst(strtolower($event['domain']))) ?></span><time><?= e(gmdate('d M Y · H:i',strtotime($event['occurred_at']))) ?></time></div><h3><?php if($event['source_url']):?><a href="<?= e($event['source_url']) ?>"><?= e(ucwords($event['title'])) ?></a><?php else:?><?= e(ucwords($event['title'])) ?><?php endif;?></h3><p><?= e($event['summary']?:($event['actor_name']?'By '.$event['actor_name']:'Linked operational record')) ?></p></div></li><?php endforeach;?></ol><?php endif;?></section></div>
<section class="panel operational-health"><div class="section-heading"><div><span class="eyebrow">Operational indicators</span><h2>Supporting QHSE signals</h2></div></div><div class="signal-grid"><?php foreach(['inspections_due'=>'Inspections Due','certificates_issued'=>'Certificates Issued','calibration_compliance'=>'Calibration Compliance','open_customer_quality_issues'=>'Open Customer Quality Issues','hse_events'=>'HSE Events This Month','environmental_events'=>'Environmental Events'] as $key=>$label):?><div><span><?= e($label) ?></span><strong><?= $m[$key]===null?'—':number_format((int)$m[$key]).($key==='calibration_compliance'?'%':'') ?></strong><small><?= $m[$key]===null?'Awaiting calibration register':'From linked records' ?></small></div><?php endforeach;?></div></section>
<section class="panel standards-panel"><div class="section-heading"><div><span class="eyebrow">Standards foundation</span><h2>Controls map to standards</h2><p>One control can support several requirements; evidence remains linked to its source.</p></div></div><div class="standards-grid"><?php foreach($state['standards'] as $standard):?><article><span><?= e($standard['focus_area']) ?></span><h3><?= e($standard['code']) ?></h3><strong><?= e($standard['title']) ?></strong><p><?= e($standard['description']) ?></p><footer><span><?= number_format((int)$standard['control_count']) ?> controls</span><span><?= number_format((int)$standard['evidence_count']) ?> evidence links</span></footer></article><?php endforeach;?></div></section>
<section class="panel assistant-panel" id="assistant"><div class="assistant-intro"><span class="assistant-mark"><?= operation_icon('activity') ?></span><div><span class="eyebrow">Read-only</span><h2>QHSE Assistant</h2><p>Ask for a grounded explanation of this overview. KPI arithmetic and due-date rules remain deterministic.</p></div></div><form method="post" class="assistant-prompts"><?= csrf_field() ?><?php foreach(['summary'=>'Summarize our current QHSE position','attention'=>'What requires attention?','quality'=>'Show recurring quality problems','activity'=>'Summarize QHSE activity this month','kpi'=>'Explain why a KPI changed'] as $value=>$label):?><button name="prompt" value="<?= e($value) ?>" class="secondary"><?= e($label) ?></button><?php endforeach;?></form><?php if($assistant):?><article class="assistant-answer" aria-live="polite"><span>Assistant response</span><h3><?= e($assistant['title']) ?></h3><p><?= e($assistant['answer']) ?></p><small>Based only on records visible to your organization.</small></article><?php endif;?></section>
<?php endif;require __DIR__.'/includes/operations-footer.php';?>
