<?php
declare(strict_types=1);
require_once __DIR__.'/marketplace-negotiation.php';

function marketplace_transaction(array $user,string $id,bool $lock=false):array
{
    $row=rows("SELECT t.*,l.title listing_title,e.name equipment_name,e.status equipment_status,e.archived_at,so.name supplier_name,co.name customer_name,ml.id lease_id,ml.status lease_status,ml.contracted_start,ml.contracted_end,ml.actual_start_at,ml.actual_return_at FROM marketplace_transactions t JOIN marketplace_listings l ON l.id=t.listing_id JOIN equipment e ON e.id=t.asset_id JOIN owners so ON so.id=t.supplier_organization_id JOIN owners co ON co.id=t.customer_organization_id LEFT JOIN marketplace_leases ml ON ml.transaction_id=t.id WHERE t.id=?".($lock?' FOR UPDATE':''),[$id])[0]??null;
    if(!$row)throw new DomainException('Marketplace transaction not found.',404);
    if(!in_array($user['owner_id'],[$row['supplier_organization_id'],$row['customer_organization_id']],true))throw new DomainException('You do not have access to this transaction.',403);
    if(!marketplace_negotiation_manager($user))throw new DomainException('Your role cannot manage commercial transactions.',403);
    return $row;
}
function marketplace_transaction_activity(array $user,string $transactionId,string $event,array $data=[]):void
{
    db()->prepare('INSERT INTO marketplace_transaction_activity(transaction_id,actor_user_id,actor_organization_id,event_type,event_data) VALUES(?,?,?,?,?)')->execute([$transactionId,$user['id'],$user['owner_id'],$event,$data?json_encode($data,JSON_THROW_ON_ERROR):null]);
    marketplace_commercial_audit($transactionId,$user['id'],$event,$data);
    if(!in_array($event,['LEASE_ISSUE_REPORTED','SALE_COMPLETED'],true)){$parties=rows('SELECT supplier_organization_id,customer_organization_id FROM marketplace_transactions WHERE id=?',[$transactionId])[0]??null;if($parties){$other=$user['owner_id']===$parties['supplier_organization_id']?$parties['customer_organization_id']:$parties['supplier_organization_id'];marketplace_notify_organization($other,$event,'transaction',$transactionId,ucwords(strtolower(str_replace('_',' ',$event))),'Transaction activity requires your attention.',$user['id']);}}
    operation_audit($user,'marketplace.transaction_'.strtolower($event),'transaction',$transactionId,null,$data);
}
function marketplace_commercial_audit(string $transactionId,?string $actor,string $event,array $data=[]):void
{
    $last=rows('SELECT sequence_number,event_hash FROM marketplace_commercial_audit WHERE transaction_id=? ORDER BY sequence_number DESC LIMIT 1 FOR UPDATE',[$transactionId])[0]??null;$sequence=(int)($last['sequence_number']??0)+1;$payload=json_encode($data,JSON_THROW_ON_ERROR);$hash=hash('sha256',$transactionId.'|'.$sequence.'|'.$actor.'|'.$event.'|'.$payload.'|'.($last['event_hash']??''));db()->prepare('INSERT INTO marketplace_commercial_audit(transaction_id,sequence_number,actor_user_id,event_type,event_data,previous_hash,event_hash) VALUES(?,?,?,?,?,?,?)')->execute([$transactionId,$sequence,$actor,$event,$payload,$last['event_hash']??null,$hash]);
}
function marketplace_add_document(array $user,string $transactionId,string $type,string $title,string $content):void
{
    $version=(int)(rows('SELECT COALESCE(MAX(version),0)+1 n FROM marketplace_transaction_documents WHERE transaction_id=? AND document_type=?',[$transactionId,$type])[0]['n']??1);db()->prepare('INSERT INTO marketplace_transaction_documents(id,transaction_id,document_type,title,version,content,created_by) VALUES(?,?,?,?,?,?,?)')->execute([uuid(),$transactionId,$type,$title,$version,$content,$user['id']]);
}
function marketplace_transaction_agreement(array $user,string $transactionId):?array
{
    marketplace_transaction($user,$transactionId);return rows('SELECT * FROM marketplace_agreements WHERE transaction_id=? AND status<>\'VOID\' ORDER BY generated_at DESC LIMIT 1',[$transactionId])[0]??null;
}
function marketplace_generate_agreement(array $user,string $transactionId):string
{
    $transaction=marketplace_transaction($user,$transactionId,true);if($transaction['status']==='CANCELLED')throw new DomainException('A cancelled transaction cannot generate an agreement.',409);
    $current=marketplace_transaction_agreement($user,$transactionId);$terms=json_decode($transaction['frozen_terms'],true,64,JSON_THROW_ON_ERROR);$version=$current?(int)$current['current_version']+1:1;$template=rows('SELECT * FROM marketplace_agreement_templates WHERE agreement_type=? AND is_active=1 AND (organization_id=? OR organization_id IS NULL) ORDER BY organization_id IS NOT NULL DESC,created_at DESC LIMIT 1',[$transaction['transaction_type'],$transaction['supplier_organization_id']])[0]??null;
    $fallback="NONAGON {{agreement_name}} AGREEMENT\n\nEquipment: {{equipment}}\nSupplier: {{supplier}}\nCustomer: {{customer}}\nValue: {{value}}\n\nThis agreement incorporates the accepted offer terms and the recorded mobilization, insurance, payment, handover and return obligations.";$body=strtr($template['body_template']??$fallback,['{{agreement_name}}'=>$transaction['transaction_type']==='LEASE'?'EQUIPMENT LEASE':'EQUIPMENT SALE','{{equipment}}'=>$transaction['equipment_name'],'{{supplier}}'=>$transaction['supplier_name'],'{{customer}}'=>$transaction['customer_name'],'{{value}}'=>$transaction['currency'].' '.number_format((float)$transaction['gross_value'],2)]);
    if(!$current){$agreement=uuid();db()->prepare("INSERT INTO marketplace_agreements(id,transaction_id,agreement_type,template_id,template_version,current_version,status,created_by) VALUES(?,?,?,?,?,1,'REVIEW',?)")->execute([$agreement,$transactionId,$transaction['transaction_type'],$template['id']??null,$template['version']??'system-1',$user['id']]);}
    else{$agreement=$current['id'];db()->prepare("UPDATE marketplace_agreements SET current_version=?,status='REVIEW',signed_at=NULL WHERE id=?")->execute([$version,$agreement]);db()->prepare('DELETE FROM marketplace_agreement_signatures WHERE agreement_id=?')->execute([$agreement]);}
    db()->prepare('INSERT INTO marketplace_agreement_versions(id,agreement_id,version_number,body,terms_snapshot,created_by) VALUES(?,?,?,?,?,?)')->execute([uuid(),$agreement,$version,$body,json_encode($terms,JSON_THROW_ON_ERROR),$user['id']]);
    marketplace_add_document($user,$transactionId,$transaction['transaction_type']==='LEASE'?'AGREEMENT':'AGREEMENT',$transaction['transaction_type'].' agreement',$body);
    db()->prepare("UPDATE marketplace_transactions SET status='AGREEMENT' WHERE id=? AND status='OFFER_ACCEPTED'")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'AGREEMENT_GENERATED',['agreement_id'=>$agreement,'version'=>$version]);return $agreement;
}
function marketplace_send_agreement(array $user,string $transactionId):void
{
    $agreement=marketplace_transaction_agreement($user,$transactionId);if(!$agreement||!in_array($agreement['status'],['DRAFT','REVIEW'],true))throw new DomainException('Generate or revise the agreement before sending it.',409);
    db()->prepare("UPDATE marketplace_agreements SET status='SENT' WHERE id=?")->execute([$agreement['id']]);marketplace_transaction_activity($user,$transactionId,'AGREEMENT_SENT',['agreement_id'=>$agreement['id'],'version'=>$agreement['current_version']]);
}
function marketplace_sign_agreement(array $user,string $transactionId,string $signer):void
{
    $transaction=marketplace_transaction($user,$transactionId,true);$agreement=marketplace_transaction_agreement($user,$transactionId);if(!$agreement||!in_array($agreement['status'],['SENT','PARTIALLY_SIGNED'],true))throw new DomainException('This agreement is not available for signature.',409);
    $version=rows('SELECT id FROM marketplace_agreement_versions WHERE agreement_id=? AND version_number=?',[$agreement['id'],$agreement['current_version']])[0]['id'];
    try{db()->prepare('INSERT INTO marketplace_agreement_signatures(id,agreement_id,agreement_version_id,organization_id,signed_by,signer_name) VALUES(?,?,?,?,?,?)')->execute([uuid(),$agreement['id'],$version,$user['owner_id'],$user['id'],$signer]);}catch(PDOException $e){if(($e->errorInfo[1]??0)===1062)throw new DomainException('Your organization has already signed this agreement version.',409);throw $e;}
    $count=(int)rows('SELECT COUNT(DISTINCT organization_id) n FROM marketplace_agreement_signatures WHERE agreement_id=?',[$agreement['id']])[0]['n'];$status=$count>=2?'SIGNED':'PARTIALLY_SIGNED';db()->prepare('UPDATE marketplace_agreements SET status=?,signed_at=IF(?=\'SIGNED\',UTC_TIMESTAMP(),NULL) WHERE id=?')->execute([$status,$status,$agreement['id']]);if($status==='SIGNED')db()->prepare("UPDATE marketplace_transactions SET status='PAYMENT_PENDING' WHERE id=? AND status IN ('OFFER_ACCEPTED','AGREEMENT')")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'AGREEMENT_SIGNED',['organization_id'=>$user['owner_id'],'status'=>$status]);
}
function marketplace_confirm_payment(array $user,string $transactionId,string $paymentId,string $provider,string $reference):void
{
    $transaction=marketplace_transaction($user,$transactionId,true);if($user['owner_id']!==$transaction['supplier_organization_id'])throw new DomainException('Only the supplier organization can record a provider confirmation.',403);
    $payment=rows('SELECT * FROM marketplace_payments WHERE id=? AND transaction_id=? FOR UPDATE',[$paymentId,$transactionId])[0]??null;if(!$payment)throw new DomainException('Payment obligation not found.',404);if($payment['status']==='CONFIRMED')return;
    db()->prepare("UPDATE marketplace_payments SET payment_provider=?,provider_reference=?,status='CONFIRMED',confirmed_at=UTC_TIMESTAMP() WHERE id=?")->execute([$provider,$reference,$paymentId]);db()->prepare("UPDATE marketplace_transactions t SET t.status='PREMOBILIZATION' WHERE t.id=? AND t.status='PAYMENT_PENDING' AND EXISTS(SELECT 1 FROM marketplace_agreements a WHERE a.transaction_id=t.id AND a.status='SIGNED')")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'PAYMENT_CONFIRMED',['payment_id'=>$paymentId,'provider'=>$provider,'reference'=>$reference]);
}
function marketplace_fund_escrow(array $user,string $transactionId,string $provider,string $reference):void
{
    $transaction=marketplace_transaction($user,$transactionId,true);if($user['owner_id']!==$transaction['supplier_organization_id'])throw new DomainException('Only the supplier organization can record escrow funding.',403);$escrow=rows('SELECT * FROM marketplace_escrow_records WHERE transaction_id=? ORDER BY created_at DESC LIMIT 1 FOR UPDATE',[$transactionId])[0]??null;if(!$escrow)throw new DomainException('Escrow record not found.',404);if($escrow['status']==='FUNDED')return;db()->prepare("UPDATE marketplace_escrow_records SET provider=?,external_reference=?,status='FUNDED',funded_at=UTC_TIMESTAMP() WHERE id=?")->execute([$provider,$reference,$escrow['id']]);marketplace_transaction_activity($user,$transactionId,'ESCROW_FUNDED',['escrow_id'=>$escrow['id'],'provider'=>$provider,'reference'=>$reference]);
}
function marketplace_save_insurance(array $user,string $transactionId,array $input):void
{
    marketplace_transaction($user,$transactionId);$provider=marketplace_text($input,'provider',255,true);$reference=marketplace_text($input,'policy_reference',255,true);$start=marketplace_text($input,'coverage_start',10,true);$end=marketplace_text($input,'coverage_end',10,true);if($end<$start)throw new DomainException('Insurance coverage end must follow its start date.',422);
    db()->prepare("INSERT INTO marketplace_insurance_records(id,transaction_id,provider,policy_reference,coverage_start,coverage_end,status,notes) VALUES(?,?,?,?,?,?,'ACTIVE',?)")->execute([uuid(),$transactionId,$provider,$reference,$start.' 00:00:00',$end.' 23:59:59',marketplace_text($input,'notes',5000)]);marketplace_transaction_activity($user,$transactionId,'INSURANCE_ACTIVATED',['provider'=>$provider,'policy_reference'=>$reference]);
}
function marketplace_premobilization_gate(array $user,string $transactionId):array
{
    $t=marketplace_transaction($user,$transactionId);$terms=json_decode($t['frozen_terms'],true)?:[];$checks=[];
    $agreement=rows("SELECT status FROM marketplace_agreements WHERE transaction_id=? AND status<>'VOID' ORDER BY generated_at DESC LIMIT 1",[$transactionId])[0]??null;$checks['Agreement']=['ready'=>($agreement['status']??'')==='SIGNED','detail'=>$agreement['status']??'Not generated'];
    $paid=(float)(rows("SELECT COALESCE(SUM(amount),0) total FROM marketplace_payments WHERE transaction_id=? AND status='CONFIRMED'",[$transactionId])[0]['total']??0);$checks['Payment']=['ready'=>$paid>=(float)$t['gross_value'],'detail'=>$t['currency'].' '.number_format($paid,2).' confirmed'];
    $reservation=rows("SELECT status FROM marketplace_reservations WHERE offer_id=?",[$t['accepted_offer_id']])[0]??null;$checks['Equipment availability']=['ready'=>($reservation['status']??'')==='CONFIRMED'&&!$t['archived_at'],'detail'=>$reservation['status']??'No reservation'];
    $maintenance=(int)(rows("SELECT COUNT(*) n FROM maintenance_records WHERE equipment_id=? AND status IN ('SCHEDULED','IN_PROGRESS') AND due_at<=UTC_TIMESTAMP()",[$t['asset_id']])[0]['n']??0);$checks['Maintenance blockers']=['ready'=>$maintenance===0&&$t['equipment_status']==='OPERATIONAL','detail'=>$maintenance?'Outstanding maintenance':'Operational'];
    $listing=rows('SELECT compliance_status,certification_valid_until FROM marketplace_listings WHERE id=?',[$t['listing_id']])[0];$cert=$listing['compliance_status']==='VALID'&&(!$listing['certification_valid_until']||$listing['certification_valid_until']>=gmdate('Y-m-d'));$checks['Certification']=['ready'=>$cert,'detail'=>$listing['compliance_status']];
    $insurance=rows("SELECT status FROM marketplace_insurance_records WHERE transaction_id=? AND status='ACTIVE' AND coverage_start<=UTC_TIMESTAMP() AND coverage_end>=UTC_TIMESTAMP() ORDER BY created_at DESC LIMIT 1",[$transactionId])[0]??null;$checks['Insurance']=['ready'=>(bool)$insurance,'detail'=>$insurance?'Active':'No active policy'];
    $packageRequired=trim((string)($terms['additional_requirements']??''))!=='';$checks['Required package / accessories']=['ready'=>!$packageRequired,'detail'=>$packageRequired?'Confirmation required':'No additional package specified'];
    $exceptions=rows('SELECT gate_key FROM marketplace_transaction_exceptions WHERE transaction_id=? AND (expires_at IS NULL OR expires_at>UTC_TIMESTAMP())',[$transactionId]);$excepted=array_column($exceptions,'gate_key');$blocked=[];$hasException=false;foreach($checks as $name=>&$check){$check['exception']=!$check['ready']&&in_array($name,$excepted,true);if($check['exception'])$hasException=true;elseif(!$check['ready'])$blocked[]=$name;}unset($check);
    return ['result'=>$blocked?'NOT_READY':($hasException?'READY_WITH_EXCEPTION':'READY'),'checks'=>$checks,'blocking'=>$blocked];
}
function marketplace_add_gate_exception(array $user,string $transactionId,string $gate,string $reason):void
{
    $t=marketplace_transaction($user,$transactionId);if($user['owner_id']!==$t['supplier_organization_id'])throw new DomainException('Only the supplier can approve a readiness exception.',403);$allowed=['Agreement','Payment','Equipment availability','Maintenance blockers','Certification','Insurance','Required package / accessories'];if(!in_array($gate,$allowed,true))throw new DomainException('Choose a valid readiness gate.',422);db()->prepare('INSERT INTO marketplace_transaction_exceptions(id,transaction_id,gate_key,reason,approved_by) VALUES(?,?,?,?,?)')->execute([uuid(),$transactionId,$gate,$reason,$user['id']]);marketplace_transaction_activity($user,$transactionId,'PREMOBILIZATION_EXCEPTION',['gate'=>$gate,'reason'=>$reason]);
}
function marketplace_complete_handover(array $user,string $transactionId,array $input,array $file=[]):void
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['transaction_type']!=='LEASE'||!$t['lease_id'])throw new DomainException('Handover is available for lease transactions.',409);$event=marketplace_enum($input,'event_type',['HANDOVER','RETURN'],'HANDOVER');if($event==='HANDOVER'){$gate=marketplace_premobilization_gate($user,$transactionId);if($gate['result']==='NOT_READY')throw new DomainException('Resolve the premobilization blockers before handover.',409);}elseif(!in_array($t['status'],['ACTIVE','RETURN_PENDING'],true))throw new DomainException('Begin the return from an active lease first.',409);$id=uuid();$checklist=['identity_verified'=>!empty($input['identity_verified']),'accessories_verified'=>!empty($input['accessories_verified']),'condition_photographed'=>!empty($input['condition_photographed'])];if(in_array(false,$checklist,true))throw new DomainException('Complete every handover checklist item.',422);
    db()->prepare('INSERT INTO marketplace_handover_records(id,lease_id,event_type,inspected_by,location,runtime_reading,mileage_reading,condition_state,checklist,notes,owner_signature,customer_signature) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$id,$t['lease_id'],$event,$user['id'],marketplace_text($input,'location',500,true),marketplace_number($input,'runtime_reading'),marketplace_number($input,'mileage_reading'),marketplace_enum($input,'condition_state',['GOOD','ACCEPTABLE','DAMAGED','CRITICAL']),json_encode($checklist,JSON_THROW_ON_ERROR),marketplace_text($input,'notes',5000),marketplace_text($input,'owner_signature',255,true),marketplace_text($input,'customer_signature',255,true)]);
    if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_OK){$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!in_array($mime,['image/jpeg','image/png','image/webp','video/mp4'],true)||$file['size']>15*1024*1024)throw new DomainException('Upload a JPEG, PNG, WebP, or MP4 up to 15 MB.',422);db()->prepare('INSERT INTO marketplace_handover_media(id,handover_id,file_name,mime_type,file_size,file_data) VALUES(?,?,?,?,?,?)')->execute([uuid(),$id,substr(basename((string)$file['name']),0,255),$mime,$file['size'],file_get_contents($file['tmp_name'])]);}
    $next=$event==='HANDOVER'?'MOBILIZING':'INSPECTION';db()->prepare('UPDATE marketplace_transactions SET status=? WHERE id=?')->execute([$next,$transactionId]);db()->prepare('UPDATE marketplace_leases SET status=?,actual_return_at=IF(?=\'INSPECTION\',UTC_TIMESTAMP(),actual_return_at) WHERE id=?')->execute([$next,$next,$t['lease_id']]);marketplace_transaction_activity($user,$transactionId,$event.'_COMPLETED',['handover_id'=>$id]);
    marketplace_add_document($user,$transactionId,$event,$event==='HANDOVER'?'Equipment handover record':'Equipment return inspection',json_encode(['location'=>$input['location'],'condition'=>$input['condition_state'],'runtime'=>$input['runtime_reading']??null,'mileage'=>$input['mileage_reading']??null,'checklist'=>$checklist],JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR));
}
function marketplace_activate_lease(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId,true);$gate=marketplace_premobilization_gate($user,$transactionId);if($gate['result']==='NOT_READY')throw new DomainException('The lease is not ready for activation: '.implode(', ',$gate['blocking']).'.',409);if(!rows("SELECT id FROM marketplace_handover_records WHERE lease_id=? AND event_type='HANDOVER'",[$t['lease_id']]))throw new DomainException('Complete handover before activating the lease.',409);
    db()->prepare("UPDATE marketplace_transactions SET status='ACTIVE' WHERE id=?")->execute([$transactionId]);db()->prepare("UPDATE marketplace_leases SET status='ACTIVE',actual_start_at=UTC_TIMESTAMP() WHERE id=?")->execute([$t['lease_id']]);db()->prepare("UPDATE equipment SET status='OPERATIONAL' WHERE id=?")->execute([$t['asset_id']]);db()->prepare("UPDATE marketplace_listings SET marketplace_status='IN_USE' WHERE id=?")->execute([$t['listing_id']]);marketplace_transaction_activity($user,$transactionId,'LEASE_ACTIVATED');
}
function marketplace_begin_return(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['status']!=='ACTIVE')throw new DomainException('Only an active lease can begin return.',409);db()->prepare("UPDATE marketplace_transactions SET status='RETURN_PENDING' WHERE id=?")->execute([$transactionId]);db()->prepare("UPDATE marketplace_leases SET status='RETURN_PENDING' WHERE id=?")->execute([$t['lease_id']]);marketplace_transaction_activity($user,$transactionId,'RETURN_INITIATED');
}
function marketplace_complete_transaction(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['status']!=='INSPECTION')throw new DomainException('Complete the return inspection before settlement.',409);$return=rows("SELECT condition_state FROM marketplace_handover_records WHERE lease_id=? AND event_type='RETURN'",[$t['lease_id']])[0]??null;if(!$return)throw new DomainException('Return inspection record is required.',409);$equipmentStatus=in_array($return['condition_state'],['DAMAGED','CRITICAL'],true)?'MAINTENANCE':'OPERATIONAL';db()->prepare("UPDATE marketplace_transactions SET status='COMPLETED',completed_at=UTC_TIMESTAMP() WHERE id=?")->execute([$transactionId]);db()->prepare("UPDATE marketplace_leases SET status='COMPLETED' WHERE id=?")->execute([$t['lease_id']]);db()->prepare("UPDATE marketplace_reservations SET status='RELEASED' WHERE offer_id=?")->execute([$t['accepted_offer_id']]);db()->prepare('UPDATE equipment SET status=? WHERE id=?')->execute([$equipmentStatus,$t['asset_id']]);db()->prepare("UPDATE marketplace_listings SET listing_status='ACTIVE',marketplace_status=? WHERE id=?")->execute([$equipmentStatus==='MAINTENANCE'?'MAINTENANCE':'AVAILABLE',$t['listing_id']]);marketplace_transaction_activity($user,$transactionId,'TRANSACTION_COMPLETED',['equipment_status'=>$equipmentStatus]);
}

function marketplace_report_issue(array $user,string $transactionId,array $input):string
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['transaction_type']!=='LEASE'||$t['status']!=='ACTIVE')throw new DomainException('Issues can only be reported for an active lease.',409);$category=marketplace_enum($input,'category',['BREAKDOWN','DAMAGE','SAFETY','MISSING_COMPONENT','OTHER']);$severity=marketplace_enum($input,'severity',['LOW','MEDIUM','HIGH','CRITICAL']);$title=marketplace_text($input,'title',255,true);$description=marketplace_text($input,'description',5000,true);$incident=uuid();$alert=null;$maintenance=null;
    if(in_array($category,['BREAKDOWN','DAMAGE','SAFETY'],true)){$alert=uuid();$kind=$category==='DAMAGE'?'BREAKDOWN':$category;$erpSeverity=$severity==='LOW'?'MEDIUM':$severity;db()->prepare('INSERT INTO alerts(id,equipment_id,kind,severity,title,status) VALUES(?,?,?,?,?,\'OPEN\')')->execute([$alert,$t['asset_id'],$kind,$erpSeverity,'Lease issue: '.$title]);}
    if($category==='BREAKDOWN'){$maintenance=uuid();db()->prepare("INSERT INTO maintenance_records(id,equipment_id,title,status,due_at) VALUES(?,?,?,'IN_PROGRESS',UTC_TIMESTAMP())")->execute([$maintenance,$t['asset_id'],'Marketplace lease incident: '.$title]);db()->prepare("UPDATE equipment SET status='MAINTENANCE' WHERE id=?")->execute([$t['asset_id']]);}
    db()->prepare('INSERT INTO marketplace_lease_incidents(id,transaction_id,lease_id,reported_by,category,severity,title,description,erp_alert_id,maintenance_id,insurance_claim_reference) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$incident,$transactionId,$t['lease_id'],$user['id'],$category,$severity,$title,$description,$alert,$maintenance,marketplace_text($input,'insurance_claim_reference',255)]);marketplace_transaction_activity($user,$transactionId,'LEASE_ISSUE_REPORTED',['incident_id'=>$incident,'erp_alert_id'=>$alert,'maintenance_id'=>$maintenance]);marketplace_notify_organization($t['supplier_organization_id'],'LEASE_ISSUE','transaction',$transactionId,'Equipment issue reported',$title,$user['id']);marketplace_notify_organization($t['customer_organization_id'],'LEASE_ISSUE','transaction',$transactionId,'Equipment issue reported',$title,$user['id']);return $incident;
}
function marketplace_extension_conflicts(array $t,string $end):array
{
    return rows("SELECT r.id,r.start_date,r.end_date FROM marketplace_reservations r JOIN marketplace_offers o ON o.id=r.offer_id WHERE r.asset_id=? AND r.status='CONFIRMED' AND r.offer_id<>? AND r.start_date<=? AND r.end_date>?",[$t['asset_id'],$t['accepted_offer_id'],$end,$t['contracted_end']]);
}
function marketplace_request_extension(array $user,string $transactionId,array $input):string
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['transaction_type']!=='LEASE'||!in_array($t['status'],['ACTIVE','RETURN_PENDING'],true))throw new DomainException('Extensions are available only during an active lease.',409);$end=marketplace_text($input,'proposed_end',10,true);if($end<=$t['contracted_end'])throw new DomainException('The proposed end date must extend the current lease.',422);if(marketplace_extension_conflicts($t,$end))throw new DomainException('The equipment has a conflicting reservation in the proposed extension period.',409);$amount=marketplace_number($input,'amount');if($amount<=0)throw new DomainException('Enter the extension price.',422);$id=uuid();$version=uuid();db()->prepare('INSERT INTO marketplace_lease_extensions(id,transaction_id,lease_id,requested_by_organization_id) VALUES(?,?,?,?)')->execute([$id,$transactionId,$t['lease_id'],$user['owner_id']]);db()->prepare('INSERT INTO marketplace_lease_extension_versions(id,extension_id,version_number,proposed_by_organization_id,proposed_end,amount,currency,notes,created_by) VALUES(?,?,1,?,?,?,?,?,?)')->execute([$version,$id,$user['owner_id'],$end,$amount,$t['currency'],marketplace_text($input,'notes',5000),$user['id']]);marketplace_transaction_activity($user,$transactionId,'EXTENSION_REQUESTED',['extension_id'=>$id,'proposed_end'=>$end,'amount'=>$amount]);$other=$user['owner_id']===$t['supplier_organization_id']?$t['customer_organization_id']:$t['supplier_organization_id'];marketplace_notify_organization($other,'EXTENSION_REQUESTED','transaction',$transactionId,'Lease extension requested',$t['equipment_name'],$user['id']);return $id;
}
function marketplace_counter_extension(array $user,string $transactionId,string $extensionId,array $input):void
{
    $t=marketplace_transaction($user,$transactionId,true);$ext=rows("SELECT e.*,v.proposed_by_organization_id FROM marketplace_lease_extensions e JOIN marketplace_lease_extension_versions v ON v.extension_id=e.id AND v.version_number=e.current_version WHERE e.id=? AND e.transaction_id=? FOR UPDATE",[$extensionId,$transactionId])[0]??null;if(!$ext||!in_array($ext['status'],['REQUESTED','COUNTERED'],true))throw new DomainException('This extension cannot be countered.',409);if($ext['proposed_by_organization_id']===$user['owner_id'])throw new DomainException('Wait for the other company to respond.',409);$end=marketplace_text($input,'proposed_end',10,true);if($end<=$t['contracted_end']||marketplace_extension_conflicts($t,$end))throw new DomainException('The proposed extension dates are unavailable.',409);$amount=marketplace_number($input,'amount');if($amount<=0)throw new DomainException('Enter the extension price.',422);$number=(int)$ext['current_version']+1;db()->prepare('INSERT INTO marketplace_lease_extension_versions(id,extension_id,version_number,proposed_by_organization_id,proposed_end,amount,currency,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([uuid(),$extensionId,$number,$user['owner_id'],$end,$amount,$t['currency'],marketplace_text($input,'notes',5000),$user['id']]);db()->prepare("UPDATE marketplace_lease_extensions SET current_version=?,status='COUNTERED' WHERE id=?")->execute([$number,$extensionId]);marketplace_transaction_activity($user,$transactionId,'EXTENSION_COUNTERED',['extension_id'=>$extensionId,'version'=>$number]);
}
function marketplace_decide_extension(array $user,string $transactionId,string $extensionId,string $decision):void
{
    $t=marketplace_transaction($user,$transactionId,true);$ext=rows("SELECT e.*,v.id version_id,v.proposed_by_organization_id,v.proposed_end,v.amount,v.currency,v.notes FROM marketplace_lease_extensions e JOIN marketplace_lease_extension_versions v ON v.extension_id=e.id AND v.version_number=e.current_version WHERE e.id=? AND e.transaction_id=? FOR UPDATE",[$extensionId,$transactionId])[0]??null;if(!$ext||!in_array($ext['status'],['REQUESTED','COUNTERED'],true))throw new DomainException('This extension is no longer awaiting a decision.',409);if($ext['proposed_by_organization_id']===$user['owner_id'])throw new DomainException('The proposing company cannot decide its own extension.',403);if($decision==='reject'){db()->prepare("UPDATE marketplace_lease_extensions SET status='REJECTED' WHERE id=?")->execute([$extensionId]);marketplace_transaction_activity($user,$transactionId,'EXTENSION_REJECTED',['extension_id'=>$extensionId]);return;}if($decision!=='accept')throw new DomainException('Choose accept or reject.',422);if(marketplace_extension_conflicts($t,$ext['proposed_end']))throw new DomainException('A reservation now conflicts with this extension.',409);db()->prepare("UPDATE marketplace_lease_extensions SET status='ACCEPTED',accepted_version_id=? WHERE id=?")->execute([$ext['version_id'],$extensionId]);db()->prepare('UPDATE marketplace_leases SET contracted_end=? WHERE id=?')->execute([$ext['proposed_end'],$t['lease_id']]);db()->prepare('UPDATE marketplace_reservations SET end_date=? WHERE offer_id=?')->execute([$ext['proposed_end'],$t['accepted_offer_id']]);db()->prepare("INSERT INTO marketplace_payments(id,transaction_id,idempotency_key,amount,currency,payment_type,status,due_at) VALUES(?,?,?,?,?,'EXTENSION','PENDING',DATE_ADD(UTC_TIMESTAMP(),INTERVAL 3 DAY))")->execute([uuid(),$transactionId,'extension-'.$extensionId,$ext['amount'],$ext['currency']]);$addendum="LEASE EXTENSION ADDENDUM\n\nNew contracted end: {$ext['proposed_end']}\nAdditional amount: {$ext['currency']} ".number_format((float)$ext['amount'],2)."\n\n".$ext['notes'];marketplace_add_document($user,$transactionId,'ADDENDUM','Lease extension addendum',$addendum);marketplace_transaction_activity($user,$transactionId,'EXTENSION_ACCEPTED',['extension_id'=>$extensionId,'new_end'=>$ext['proposed_end'],'amount'=>$ext['amount']]);
}
function marketplace_add_return_exception(array $user,string $transactionId,array $input):void
{
    $t=marketplace_transaction($user,$transactionId);if($t['status']!=='INSPECTION'||$user['owner_id']!==$t['supplier_organization_id'])throw new DomainException('Only the supplier can record return exceptions during inspection.',403);$handover=rows("SELECT id FROM marketplace_handover_records WHERE lease_id=? AND event_type='RETURN'",[$t['lease_id']])[0]['id']??null;if(!$handover)throw new DomainException('Complete the return inspection first.',409);$type=marketplace_enum($input,'exception_type',['DAMAGE','MISSING_COMPONENT','EXCESS_RUNTIME','EXCESS_MILEAGE','CLEANING','LATE_RETURN','OTHER']);$amount=marketplace_number($input,'amount');db()->prepare('INSERT INTO marketplace_return_exceptions(id,transaction_id,handover_id,exception_type,description,amount,currency,insurance_claim_reference,created_by) VALUES(?,?,?,?,?,?,?,?,?)')->execute([uuid(),$transactionId,$handover,$type,marketplace_text($input,'description',5000,true),$amount,$t['currency'],marketplace_text($input,'insurance_claim_reference',255),$user['id']]);marketplace_transaction_activity($user,$transactionId,'RETURN_EXCEPTION_RECORDED',['type'=>$type,'amount'=>$amount]);
}
function marketplace_decide_return_exception(array $user,string $transactionId,string $exceptionId,string $decision):void
{
    $t=marketplace_transaction($user,$transactionId);if($user['owner_id']!==$t['customer_organization_id'])throw new DomainException('Only the customer can respond to a return exception.',403);$status=$decision==='accept'?'ACCEPTED':($decision==='dispute'?'DISPUTED':null);if(!$status)throw new DomainException('Choose accept or dispute.',422);db()->prepare("UPDATE marketplace_return_exceptions SET status=? WHERE id=? AND transaction_id=? AND status='OPEN'")->execute([$status,$exceptionId,$transactionId]);if(!db()->lastInsertId()&&false){}marketplace_transaction_activity($user,$transactionId,'RETURN_EXCEPTION_'.$status,['exception_id'=>$exceptionId]);if($status==='DISPUTED')db()->prepare("UPDATE marketplace_transactions SET status='DISPUTED' WHERE id=?")->execute([$transactionId]);
}
function marketplace_resolve_return_exception(array $user,string $transactionId,string $exceptionId,string $resolution):void
{
    $t=marketplace_transaction($user,$transactionId);if($user['owner_id']!==$t['supplier_organization_id']||$t['status']!=='DISPUTED')throw new DomainException('Only the supplier can resolve a disputed return exception.',403);$status=$resolution==='waive'?'WAIVED':($resolution==='accept'?'ACCEPTED':null);if(!$status)throw new DomainException('Choose a valid dispute resolution.',422);$stmt=db()->prepare("UPDATE marketplace_return_exceptions SET status=? WHERE id=? AND transaction_id=? AND status='DISPUTED'");$stmt->execute([$status,$exceptionId,$transactionId]);if(!$stmt->rowCount())throw new DomainException('Disputed exception not found.',404);if(!(int)(rows("SELECT COUNT(*) n FROM marketplace_return_exceptions WHERE transaction_id=? AND status='DISPUTED'",[$transactionId])[0]['n']??0))db()->prepare("UPDATE marketplace_transactions SET status='INSPECTION' WHERE id=?")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'RETURN_DISPUTE_RESOLVED',['exception_id'=>$exceptionId,'resolution'=>$status]);
}
function marketplace_settle_transaction(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId,true);if($user['owner_id']!==$t['supplier_organization_id'])throw new DomainException('Only the supplier can approve settlement.',403);if(!in_array($t['status'],['INSPECTION','SETTLEMENT'],true))throw new DomainException('Return inspection must be complete before settlement.',409);$open=(int)(rows("SELECT COUNT(*) n FROM marketplace_return_exceptions WHERE transaction_id=? AND status IN ('OPEN','DISPUTED')",[$transactionId])[0]['n']??0);if($open)throw new DomainException('Resolve all return exceptions before settlement.',409);$charges=(float)(rows("SELECT COALESCE(SUM(amount),0) total FROM marketplace_return_exceptions WHERE transaction_id=? AND status='ACCEPTED'",[$transactionId])[0]['total']??0);$escrow=rows('SELECT * FROM marketplace_escrow_records WHERE transaction_id=? ORDER BY created_at DESC LIMIT 1 FOR UPDATE',[$transactionId])[0]??null;$secured=(float)($escrow['secured_amount']??0);$fee=round(((float)$t['gross_value']+$charges)*0.025,2);$refund=max(0,$secured-(float)$t['gross_value']-$charges);$payout=max(0,(float)$t['gross_value']+$charges-$fee);db()->prepare("INSERT INTO marketplace_settlements(id,transaction_id,currency,gross_amount,additional_charges,deposit_applied,refund_amount,platform_fee,supplier_payout,status,approved_by,settled_at) VALUES(?,?,?,?,?,?,?,?,?,'SETTLED',?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE additional_charges=VALUES(additional_charges),deposit_applied=VALUES(deposit_applied),refund_amount=VALUES(refund_amount),platform_fee=VALUES(platform_fee),supplier_payout=VALUES(supplier_payout),status='SETTLED',approved_by=VALUES(approved_by),settled_at=UTC_TIMESTAMP()")->execute([uuid(),$transactionId,$t['currency'],$t['gross_value'],$charges,min($secured,(float)$t['gross_value']+$charges),$refund,$fee,$payout,$user['id']]);if($escrow)db()->prepare("UPDATE marketplace_escrow_records SET status='RELEASED',released_at=UTC_TIMESTAMP() WHERE id=?")->execute([$escrow['id']]);db()->prepare("UPDATE marketplace_return_exceptions SET status='SETTLED' WHERE transaction_id=? AND status='ACCEPTED'")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'SETTLEMENT_COMPLETED',['charges'=>$charges,'refund'=>$refund,'platform_fee'=>$fee,'supplier_payout'=>$payout]);marketplace_complete_transaction($user,$transactionId);
}
function marketplace_complete_sale(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId,true);if($t['transaction_type']!=='SALE'||$user['owner_id']!==$t['supplier_organization_id'])throw new DomainException('Only the seller can complete this sale.',403);$signed=(bool)rows("SELECT 1 FROM marketplace_agreements WHERE transaction_id=? AND status='SIGNED'",[$transactionId]);$paid=(float)(rows("SELECT COALESCE(SUM(amount),0) total FROM marketplace_payments WHERE transaction_id=? AND status='CONFIRMED'",[$transactionId])[0]['total']??0);if(!$signed||$paid<(float)$t['gross_value'])throw new DomainException('The sale must be signed and fully paid before ownership transfer.',409);$customerUser=rows("SELECT * FROM users WHERE owner_id=? AND is_active=1 ORDER BY role='OWNER_ADMIN' DESC LIMIT 1",[$t['customer_organization_id']])[0]??null;if(!$customerUser)throw new DomainException('The buyer organization has no active account for ownership transfer.',409);$unit=equipment_default_unit($customerUser);equipment_seed_statuses($t['customer_organization_id']);$statusId=rows('SELECT id FROM equipment_statuses WHERE owner_id=? AND operational_state=? AND is_default=1 LIMIT 1',[$t['customer_organization_id'],$t['equipment_status']])[0]['id']??null;db()->prepare('INSERT INTO equipment_ownership_history(id,equipment_id,previous_owner_id,new_owner_id,transaction_id,transferred_by) VALUES(?,?,?,?,?,?)')->execute([uuid(),$t['asset_id'],$t['supplier_organization_id'],$t['customer_organization_id'],$transactionId,$user['id']]);db()->prepare('UPDATE equipment SET owner_id=?,unit_id=?,operator_id=NULL,status_id=? WHERE id=?')->execute([$t['customer_organization_id'],$unit,$statusId,$t['asset_id']]);db()->prepare("UPDATE marketplace_listings SET listing_status='CLOSED',marketplace_status='OFFLINE' WHERE id=?")->execute([$t['listing_id']]);db()->prepare("UPDATE marketplace_transactions SET status='COMPLETED',completed_at=UTC_TIMESTAMP() WHERE id=?")->execute([$transactionId]);marketplace_transaction_activity($user,$transactionId,'SALE_COMPLETED',['new_owner_id'=>$t['customer_organization_id']]);marketplace_notify_organization($t['customer_organization_id'],'SALE_COMPLETED','transaction',$transactionId,'Equipment ownership transferred',$t['equipment_name'],$user['id']);
}
function marketplace_add_review(array $user,string $transactionId,int $rating,string $text):void
{
    $t=marketplace_transaction($user,$transactionId);if($t['status']!=='COMPLETED')throw new DomainException('Reviews are available after transaction completion.',409);if($rating<1||$rating>5)throw new DomainException('Choose a rating from 1 to 5.',422);$reviewed=$user['owner_id']===$t['supplier_organization_id']?$t['customer_organization_id']:$t['supplier_organization_id'];try{db()->prepare('INSERT INTO marketplace_reviews(id,transaction_id,reviewer_organization_id,reviewed_organization_id,rating,review_text,created_by) VALUES(?,?,?,?,?,?,?)')->execute([uuid(),$transactionId,$user['owner_id'],$reviewed,$rating,mb_substr(trim($text),0,5000),$user['id']]);}catch(PDOException $e){if(($e->errorInfo[1]??0)===1062)throw new DomainException('Your company has already reviewed this transaction.',409);throw $e;}marketplace_transaction_activity($user,$transactionId,'REVIEW_SUBMITTED',['rating'=>$rating,'reviewed_organization_id'=>$reviewed]);
}
function marketplace_send_expiry_notifications(array $user,string $transactionId):void
{
    $t=marketplace_transaction($user,$transactionId);if($t['transaction_type']!=='LEASE'||$t['status']!=='ACTIVE'||!$t['contracted_end'])return;$days=(int)floor((strtotime($t['contracted_end'].' 23:59:59 UTC')-time())/86400);if($days<0||$days>7)return;$event='LEASE_EXPIRY_'.$t['contracted_end'];$exists=rows('SELECT 1 FROM marketplace_transaction_activity WHERE transaction_id=? AND event_type=?',[$transactionId,$event]);if($exists)return;db()->prepare('INSERT INTO marketplace_transaction_activity(transaction_id,event_type,event_data) VALUES(?,?,?)')->execute([$transactionId,$event,json_encode(['days_remaining'=>$days],JSON_THROW_ON_ERROR)]);marketplace_commercial_audit($transactionId,null,$event,['days_remaining'=>$days]);foreach([$t['supplier_organization_id'],$t['customer_organization_id']] as $owner)marketplace_notify_organization($owner,'LEASE_EXPIRY','transaction',$transactionId,'Lease expiry approaching',$t['equipment_name'].' ends '.$t['contracted_end']);
}
