<?php
declare(strict_types=1);
require __DIR__ . '/equipment-catalog.php';
$user=require_verified();$active=$module;$pageTitle=ucfirst($module);$problem=null;$record=null;$items=[];$total=0;$locations=[];
$id=is_string($_GET['id']??'')?($_GET['id']??''):'';
$create=$module==='equipment'&&isset($_GET['create'])&&operation_can_manage($user);
$page=max(1,min(100000,(int)($_GET['page']??1)));$offset=($page-1)*25;
$filters=['site'=>'','unit'=>''];$status=is_string($_GET['status']??'')?($_GET['status']??''):'';
$severity=is_string($_GET['severity']??'')?($_GET['severity']??''):'';
try {
    $filters=operation_filters($user,$_GET);
    [$scope,$params]=operation_scope($user,'e',$filters);
    $locations=operation_locations($user);
    if($id!=='') {
        if($module==='equipment')$record=operation_equipment($user,$id);
        elseif($module==='alerts')$record=operation_alert($user,$id);
        elseif($module==='maintenance')$record=rows("SELECT m.*,e.name AS equipment_name,e.asset_code,e.site_name,e.unit_name FROM maintenance_records m JOIN equipment_status_view e ON e.id=m.equipment_id WHERE {$scope} AND m.id=?",[...$params,$id])[0]??null;
        else {[$sql,$arguments]=operation_operator_query($user,$filters);$record=rows("SELECT * FROM ({$sql}) operators WHERE id=?",[...$arguments,$id])[0]??null;}
        if(!$record)throw new DomainException('Record not found in your access scope.',404);
        $pageTitle=$record['name']??$record['full_name']??$record['title'];
    } elseif(!$create) {
        if($module==='equipment') {
            $sql="SELECT e.* FROM equipment_status_view e WHERE {$scope}";
            if($status!==''){if(!in_array($status,['OPERATIONAL','MAINTENANCE','DOWN'],true))throw new DomainException('Invalid equipment status.',422);$sql.=' AND e.status=?';$params[]=$status;}
            $order=" ORDER BY FIELD(status,'DOWN','MAINTENANCE','OPERATIONAL'),name,id";
        } elseif($module==='maintenance') {
            $sql="SELECT m.*,e.name AS equipment_name,e.asset_code,e.site_name,e.unit_name,(m.due_at<UTC_TIMESTAMP() AND m.status IN ('SCHEDULED','IN_PROGRESS')) AS overdue FROM maintenance_records m JOIN equipment_status_view e ON e.id=m.equipment_id WHERE {$scope}";
            if($status==='overdue')$sql.=" AND m.due_at<UTC_TIMESTAMP() AND m.status IN ('SCHEDULED','IN_PROGRESS')";
            elseif($status!==''){if(!in_array($status,['SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED'],true))throw new DomainException('Invalid maintenance status.',422);$sql.=' AND m.status=?';$params[]=$status;}
            $order=' ORDER BY overdue DESC,due_at,id';
        } elseif($module==='alerts') {
            operation_sync_risks($user,$filters);
            [$scope,$params]=operation_scope($user,'e',$filters,'equipment_id');
            $sql="SELECT e.* FROM alert_priority_view e WHERE {$scope}";
            if($status!=='all')$sql.=" AND e.status<>'RESOLVED'";
            if($severity!==''){if(!in_array($severity,['CRITICAL','HIGH','MEDIUM'],true))throw new DomainException('Invalid severity.',422);$sql.=' AND e.severity=?';$params[]=$severity;}
            $order=' ORDER BY priority,triggered_at,id';
        } else {[$sql,$params]=operation_operator_query($user,$filters);$order=' ORDER BY full_name,id';}
        $total=(int)rows("SELECT COUNT(*) AS n FROM ({$sql}) result",$params)[0]['n'];
        $items=rows($sql.$order." LIMIT 25 OFFSET {$offset}",$params);
    }
} catch(Throwable $error) {
    http_response_code($error instanceof DomainException?$error->getCode():503);
    $problem=$error instanceof DomainException?$error->getMessage():'Operational records are temporarily unavailable.';
    if(!$error instanceof DomainException)error_log('Operational page: '.$error->getMessage());
}
require APP_ROOT.'/includes/operations-header.php';
?>
<section class="page-heading"><div><p class="eyebrow">OPERATIONS / <?= e(strtoupper($module)) ?></p><h1><?= e($create?'Register equipment':$pageTitle) ?></h1><p><?= $id?'Current record and operational context.':'Records within your organization and assigned location access.' ?></p></div><?php if($module==='equipment'&&!$id&&!$create&&operation_can_manage($user)):?><div class="page-actions"><a class="secondary" href="equipment-import">Import equipment</a><a class="primary" href="equipment?create=1">Register equipment</a></div><?php endif;?></section>
<?php if($problem):?><div class="notice error" role="alert"><?= e($problem) ?></div>
<?php elseif($create):?><section class="panel form-panel"><form action="operations-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="equipment.create"><label>Equipment name<input name="name" maxlength="255" required></label><label>Asset ID<input name="asset_code" maxlength="100" required></label><label class="full">Assigned unit<select name="unit_id" required><option value="">Choose an accessible unit</option><?php foreach($locations as $l):?><option value="<?= e($l['unit_id']) ?>"><?= e($l['site_name'].' / '.$l['unit_name']) ?></option><?php endforeach;?></select></label><p class="full">New equipment starts as Operational. Update its status and operator from the equipment record.</p><div class="full"><button class="primary" <?= !$locations?'disabled':'' ?>>Register equipment</button> <a href="equipment">Cancel</a></div><?php if(!$locations):?><p class="full">No units are assigned to your account. Contact your administrator.</p><?php endif;?></form></section>
<?php elseif($record):?>
<div class="detail-grid"><div><section class="panel detail-content"><h2>Record details</h2><dl>
<?php foreach(['sequence_no'=>'S/N','asset_code'=>'Equipment ID','serial_no'=>'Serial Number','equipment_name'=>'Equipment','full_name'=>'Name','owner_name'=>'Owner','condition_remarks'=>'Condition / Remarks','position'=>'Position','site_name'=>'Site','unit_name'=>'Unit','operator_name'=>'Assigned operator','status'=>'Status','severity'=>'Severity','kind'=>'Risk type','utilization_percent'=>'Utilization (%)','last_activity_at'=>'Last activity (UTC)','due_at'=>'Due (UTC)','triggered_at'=>'Triggered (UTC)','acknowledged_at'=>'Acknowledged (UTC)','escalation_reason'=>'Escalation reason'] as $key=>$label):if(!array_key_exists($key,$record))continue;?><dt><?= e($label) ?></dt><dd><?= in_array($key,['status','severity'],true)?operation_badge((string)$record[$key]):e((string)($record[$key]??'Not recorded')) ?></dd><?php endforeach;?></dl><?php if(isset($record['equipment_id'])):?><a href="equipment?id=<?= e($record['equipment_id']) ?>">View equipment →</a><?php endif;?></section>
<?php if($module==='equipment'):
    require APP_ROOT.'/includes/equipment-detail.php';
    $work=rows('SELECT id,title,status,due_at FROM maintenance_records WHERE equipment_id=? ORDER BY due_at DESC LIMIT 25',[$record['id']]);
    $risks=rows("SELECT id,title,severity,status FROM alerts WHERE equipment_id=? ORDER BY triggered_at DESC LIMIT 25",[$record['id']]);?>
<section class="panel section-gap" id="maintenance-records"><header class="panel-heading"><h2>Maintenance records</h2></header><?php if(!$work):?><div class="detail-content"><p>No work orders recorded for this asset.</p></div><?php endif;foreach($work as $row):?><div class="detail-content"><a href="maintenance?id=<?= e($row['id']) ?>"><?= e($row['title']) ?></a> <?= operation_badge($row['status']) ?><p>Due <?= e($row['due_at']) ?> UTC</p></div><?php endforeach;?></section>
<section class="panel section-gap"><header class="panel-heading"><h2>Risk alerts</h2></header><?php if(!$risks):?><div class="detail-content"><p>No risk alerts recorded for this asset.</p></div><?php endif;foreach($risks as $row):?><div class="detail-content"><a href="alert?id=<?= e($row['id']) ?>"><?= e($row['title']) ?></a> <?= operation_badge($row['severity']) ?> <?= operation_badge($row['status']) ?></div><?php endforeach;?></section>
<?php elseif($module==='operators'):
    [$scope,$params]=operation_scope($user);$assigned=rows("SELECT e.id,e.name,e.status FROM equipment_status_view e WHERE {$scope} AND e.operator_id=? ORDER BY e.name LIMIT 25",[...$params,$record['id']]);?>
<section class="panel section-gap"><header class="panel-heading"><h2>Assigned equipment</h2></header><div class="detail-content"><?php if(!$assigned):?><p>No equipment assigned within your scope.</p><?php endif;foreach($assigned as $row):?><p><a href="equipment?id=<?= e($row['id']) ?>"><?= e($row['name']) ?></a> <?= operation_badge($row['status']) ?></p><?php endforeach;?></div></section>
<?php endif;
$type=['equipment'=>'equipment','maintenance'=>'maintenance','alerts'=>'alert','operators'=>'user'][$module];
$audit=rows('SELECT a.action,a.created_at,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id AND u.owner_id=a.owner_id WHERE a.owner_id=? AND a.entity_type=? AND a.entity_id=? ORDER BY a.id DESC LIMIT 20',[$user['owner_id'],$type,$id]);?>
<section class="panel section-gap"><header class="panel-heading"><h2>Recent audit activity</h2></header><div class="detail-content"><?php if(!$audit):?><p>No dashboard actions recorded yet.</p><?php endif;foreach($audit as $entry):?><p><strong><?= e($entry['action']) ?></strong><br><small><?= e(($entry['full_name']??'Former user').' · '.$entry['created_at']) ?> UTC</small></p><?php endforeach;?></div></section></div>
<div class="action-forms"><?php if(!operation_can_manage($user)):?><section class="panel"><h2>Read-only access</h2><p>Your role can inspect operational records. Contact your supervisor to request changes.</p></section>
<?php elseif($module==='alerts'&&$record['status']!=='RESOLVED'):
$people=rows("SELECT u.id,u.full_name FROM users u WHERE u.owner_id=? AND u.is_active=1 AND (u.is_email_verified=1 OR ?=1) AND (u.role='OWNER_ADMIN' OR EXISTS(SELECT 1 FROM user_scopes us WHERE us.user_id=u.id AND us.site_id=? AND us.unit_id=?)) ORDER BY u.full_name",[$user['owner_id'],(int)development_verification_bypass(),$record['site_id'],$record['unit_id']]);?>
<?php if(!$record['acknowledged_at']):?><section class="panel"><h2>Acknowledge alert</h2><p>Record that you have seen and accepted this risk for follow-up.</p><form action="operations-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="acknowledge"><input type="hidden" name="id" value="<?= e($id) ?>"><button class="primary">Acknowledge</button></form></section><?php endif;?>
<section class="panel" id="assign"><h2>Assign responsibility</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="assign"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Responsible person<select name="assigned_to" required><option value="">Choose a person</option><?php foreach($people as $person):?><option value="<?= e($person['id']) ?>" <?= $record['assigned_to']===$person['id']?'selected':'' ?>><?= e($person['full_name']) ?></option><?php endforeach;?></select></label><button class="primary">Assign</button></form></section>
<?php if($record['status']!=='ESCALATED'):?><section class="panel" id="escalate"><h2>Escalate risk</h2><p>Raise this alert to Critical and record the reason for escalation.</p><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="escalate"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Reason<textarea name="reason" maxlength="500" required></textarea></label><button class="primary">Escalate</button></form></section><?php endif;?>
<?php elseif($module==='equipment'):
[$sql,$params]=operation_operator_query($user,['site'=>$record['site_id'],'unit'=>$record['unit_id']]);$operators=rows($sql.' ORDER BY full_name',$params);?>
<?php if(equipment_can_action($user,'change_status')):?><section class="panel" id="change-status"><h2>Update operational status</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="equipment.status"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Status<select name="status"><?php foreach(['OPERATIONAL'=>'Operational','MAINTENANCE'=>'Maintenance','DOWN'=>'Critical / Down'] as $value=>$label):?><option value="<?= $value ?>" <?= $record['status']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><button class="primary">Save status</button></form></section>
<?php endif;?><?php if(equipment_can_action($user,'operators')):?><section class="panel" id="assign-operator"><h2>Assign operator</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="equipment.operator"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Operator<select name="operator_id"><option value="">Unassigned</option><?php foreach($operators as $person):?><option value="<?= e($person['id']) ?>" <?= $record['operator_id']===$person['id']?'selected':'' ?>><?= e($person['full_name']) ?></option><?php endforeach;?></select></label><button class="primary">Save assignment</button></form></section>
<?php endif;?><section class="panel" id="schedule-maintenance"><h2>Schedule maintenance</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="maintenance.create"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Work order title<input name="title" maxlength="255" required></label><label>Due date and time (UTC)<input name="due_at" type="datetime-local" required></label><button class="primary">Create work order</button></form></section>
<section class="panel"><h2>Report a risk</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="alert.create"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Risk title<input name="title" maxlength="255" required></label><label>Type<select name="kind"><option value="SAFETY">Safety</option><option value="COMPLIANCE">Compliance</option></select></label><label>Severity<select name="severity"><option value="HIGH">High</option><option value="CRITICAL">Critical</option><option value="MEDIUM">Medium</option></select></label><button class="primary">Record risk</button></form></section>
<?php elseif($module==='maintenance'&&in_array($record['status'],['SCHEDULED','IN_PROGRESS'],true)):?><section class="panel"><h2>Update work order</h2><form action="operations-action" method="post" class="stack"><?= csrf_field() ?><input type="hidden" name="action" value="maintenance.status"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Next state<select name="status"><?php if($record['status']==='SCHEDULED'):?><option value="IN_PROGRESS">Start work</option><?php else:?><option value="COMPLETED">Complete work</option><?php endif;?><option value="CANCELLED">Cancel work order</option></select></label><button class="primary">Save work order</button></form></section><?php endif;?></div></div>
<?php else:?>
<form method="get" class="filterbar"><div><label for="site">Site</label><select id="site" name="site"><option value="">All accessible sites</option><?php $seen=[];foreach($locations as $l):if(isset($seen[$l['site_id']]))continue;$seen[$l['site_id']]=true;?><option value="<?= e($l['site_id']) ?>" <?= $filters['site']===$l['site_id']?'selected':'' ?>><?= e($l['site_name']) ?></option><?php endforeach;?></select></div><div><label for="unit">Unit</label><select id="unit" name="unit"><option value="">All accessible units</option><?php foreach($locations as $l):?><option value="<?= e($l['unit_id']) ?>" <?= $filters['unit']===$l['unit_id']?'selected':'' ?>><?= e($l['unit_name']) ?></option><?php endforeach;?></select></div>
<?php if($module==='equipment'||$module==='maintenance'):$choices=$module==='equipment'?['OPERATIONAL'=>'Operational','MAINTENANCE'=>'Maintenance','DOWN'=>'Critical / Down']:['overdue'=>'Overdue','SCHEDULED'=>'Scheduled','IN_PROGRESS'=>'In progress','COMPLETED'=>'Completed','CANCELLED'=>'Cancelled'];?><div><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option><?php foreach($choices as $value=>$label):?><option value="<?= $value ?>" <?= $status===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></div><?php endif;?>
<?php if($module==='alerts'):?><div><label for="severity">Severity</label><select id="severity" name="severity"><option value="">All severities</option><?php foreach(['CRITICAL','HIGH','MEDIUM'] as $value):?><option <?= $severity===$value?'selected':'' ?>><?= $value ?></option><?php endforeach;?></select></div><div><label for="status">State</label><select name="status" id="status"><option value="">Active alerts</option><option value="all" <?= $status==='all'?'selected':'' ?>>Include resolved</option></select></div><?php endif;?><button class="secondary">Apply</button><a href="<?= e($module) ?>">Reset</a></form>
<section class="panel"><header class="panel-heading"><h2><?= number_format($total) ?> <?= e($module==='equipment'?'assets':$module) ?></h2><span class="muted">25 per page</span></header><?php if(!$items):?><div class="empty-state"><h3>No matching records</h3><p>Try another filter or ask your administrator to review your assigned units.</p></div><?php else:?><div class="table-wrap"><table><thead><tr><th><?= $module==='operators'?'Operator':'Record' ?></th><th><?= $module==='operators'?'Position':'Status' ?></th><?php if($module!=='operators'):?><th>Location</th><th><?= $module==='equipment'?'Operator':($module==='maintenance'?'Due (UTC)':'Severity') ?></th><?php endif;?></tr></thead><tbody><?php foreach($items as $item):?><tr><td><a class="record-link" href="<?= $module==='alerts'?'alert':$module ?>?id=<?= e($item['id']) ?>"><?= e($item['name']??$item['full_name']??$item['title']) ?></a><?php if(isset($item['asset_code'])):?><small><?= e($item['asset_code']) ?></small><?php endif;?></td><td><?= $module==='operators'?e($item['position']?:'Not recorded'):operation_badge($item['status']) ?><?php if(!empty($item['overdue'])):?> <?= operation_badge('HIGH') ?> Overdue<?php endif;?></td><?php if($module!=='operators'):?><td><?= e($item['site_name'].' / '.$item['unit_name']) ?></td><td><?= $module==='equipment'?e($item['operator_name']??'Unassigned'):($module==='maintenance'?e($item['due_at']):operation_badge($item['severity'])) ?></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<footer class="pagination"><?php $args=array_merge($filters,['status'=>$status,'severity'=>$severity]);?><span>Page <?= $page ?> of <?= max(1,(int)ceil($total/25)) ?></span><div><?php if($page>1):?><a href="<?= e($module.'?'.http_build_query([...$args,'page'=>$page-1])) ?>">← Previous</a><?php endif;?> <?php if($offset+25<$total):?><a href="<?= e($module.'?'.http_build_query([...$args,'page'=>$page+1])) ?>">Next →</a><?php endif;?></div></footer></section>
<?php endif;require APP_ROOT.'/includes/operations-footer.php'; ?>
