CREATE DATABASE IF NOT EXISTS nonagon CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE nonagon;

CREATE TABLE owners (
  id CHAR(36) PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL, address VARCHAR(500) NULL, is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE users (
  id CHAR(36) PRIMARY KEY, owner_id CHAR(36) NOT NULL, full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE, phone VARCHAR(30) NOT NULL, position VARCHAR(255) NULL,
  role ENUM('OWNER_ADMIN','OPERATOR','SUPERVISOR','ADMIN') NOT NULL DEFAULT 'OWNER_ADMIN',
  password_hash VARCHAR(255) NOT NULL, auth_provider ENUM('LOCAL','GOOGLE') NOT NULL DEFAULT 'LOCAL',
  is_email_verified BOOLEAN NOT NULL DEFAULT FALSE, is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_owner FOREIGN KEY (owner_id) REFERENCES owners(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE spaces (id CHAR(36) PRIMARY KEY,owner_id CHAR(36) NOT NULL,name VARCHAR(255) NOT NULL,is_default BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES owners(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE sites (id CHAR(36) PRIMARY KEY,space_id CHAR(36) NOT NULL,name VARCHAR(255) NOT NULL,is_default BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(space_id) REFERENCES spaces(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE plants (id CHAR(36) PRIMARY KEY,site_id CHAR(36) NOT NULL,name VARCHAR(255) NOT NULL,is_default BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE units (id CHAR(36) PRIMARY KEY,plant_id CHAR(36) NOT NULL,name VARCHAR(255) NOT NULL,is_default BOOLEAN DEFAULT FALSE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(plant_id) REFERENCES plants(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE verification_tokens (id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,used_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE invitations (
 id CHAR(36) PRIMARY KEY,owner_id CHAR(36) NOT NULL,email VARCHAR(255) NOT NULL,role ENUM('OPERATOR','SUPERVISOR','ADMIN') NOT NULL,
 site_id CHAR(36) NOT NULL,unit_id CHAR(36) NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expires_at DATETIME NOT NULL,accepted_at DATETIME NULL,
 created_by CHAR(36) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES owners(id) ON DELETE CASCADE,FOREIGN KEY(site_id) REFERENCES sites(id),FOREIGN KEY(unit_id) REFERENCES units(id),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE user_scopes (
 id CHAR(36) PRIMARY KEY,user_id CHAR(36) NOT NULL,site_id CHAR(36) NOT NULL,unit_id CHAR(36) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY unique_scope(user_id,site_id,unit_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(site_id) REFERENCES sites(id),FOREIGN KEY(unit_id) REFERENCES units(id)
) ENGINE=InnoDB;
CREATE TABLE login_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) NOT NULL,ip_address VARCHAR(45) NOT NULL,
  attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX login_throttle(email,ip_address,attempted_at)
) ENGINE=InnoDB;
