<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require __DIR__.'/../app/investment-participation.php';

$targets=[];foreach(['euniceebelike@gmail.com','aqqute.dev@gmail.com'] as $email){$target=rows('SELECT u.*,o.name company_name FROM users u JOIN owners o ON o.id=u.owner_id WHERE LOWER(u.email)=? LIMIT 1',[$email])[0]??null;if(!$target)throw new RuntimeException("Demo owner account {$email} was not found.");$targets[]=$target;}
$items=[
 ['71000000-0000-4000-8000-000000000001','3-inch Hunting PCE','Oil & Gas Services','Well-control pressure-control equipment for intervention and pressure operations.','3-inch pressure-control equipment package with lubricator sections, stuffing box, tool trap, quick unions and rated pressure-control accessories.','Hunting','3-inch PCE Package','NEW',1,'Port Harcourt, Nigeria',185000000,5000000,24,'Hunting-authorized distributor',142000000,18000000,160000000,6500000,62,12,246000000,118000000,15.8],
 ['71000000-0000-4000-8000-000000000002','30-ton HOWO Truck','Construction & Logistics','Heavy-duty haulage capacity for construction, mining and industrial logistics demand.','30-ton HOWO heavy-duty truck configured for industrial haulage, with operator safety package, warranty and local parts support.','SINOTRUK HOWO','30-ton Heavy Duty Truck','NEW',2,'Lagos, Nigeria',320000000,5000000,30,'Authorized HOWO distributor',252000000,28000000,280000000,4800000,70,10,410000000,206000000,14.4],
 ['71000000-0000-4000-8000-000000000003','Water Pump','Water & Civil Infrastructure','Mobile dewatering and water-transfer capacity for civil works, facilities and emergency response.','Industrial diesel-driven water pump package with suction/discharge hoses, control panel, skid, commissioning kit and service spares.','To be selected','Industrial Dewatering Pump','NEW',4,'Nigeria',48000000,1000000,18,'Industrial pump supplier',35000000,5000000,40000000,750000,58,9,69000000,31000000,13.2],
 ['71000000-0000-4000-8000-000000000004','10-ton Liebherr Crane','Construction & Industrial Lifting','Compact lifting capacity for plants, construction sites and industrial maintenance projects.','10-ton Liebherr mobile crane configuration with certified lifting accessories, load chart, operator aids and commissioning inspection.','Liebherr','10-ton Mobile Crane','USED',1,'Rivers State, Nigeria',265000000,5000000,30,'Verified heavy-equipment supplier',205000000,25000000,230000000,3800000,66,14,352000000,154000000,14.9],
];
$pdo=db();$pdo->beginTransaction();try{
 foreach($items as $index=>$x){$user=$targets[$index<2?0:1];$promoterId=rows('SELECT id FROM investment_promoters WHERE organization_id=?',[$user['owner_id']])[0]['id']??null;[$id,$title,$industry,$rationale,$spec,$oem,$model,$condition,$quantity,$geography,$target,$minimum,$term,$supplier,$purchase,$logistics,$landed,$rate,$utilization,$downtime,$revenue,$opex,$return]=$x;$targetDays=$term*30;$minimumDays=90;$usefulLifeDays=max(3650,$targetDays);
  $type=rows('SELECT id FROM equipment_types WHERE LOWER(name) LIKE ? ORDER BY owner_id IS NULL DESC LIMIT 1',['%'.strtolower(str_contains($title,'Truck')?'truck':(str_contains($title,'Pump')?'pump':(str_contains($title,'Crane')?'crane':'pressure'))).'%'])[0]['id']??null;
  db()->prepare("INSERT INTO investment_opportunities(id,organization_id,promoter_id,created_by,title,source_type,status,publication_mode,funding_status,funding_opens_at,funding_closes_at,current_version,equipment_type_id,industry,quantity,target_geography,deployment_state,opportunity_rationale,target_funding_amount,minimum_participation,currency,target_term_months,asset_useful_life_days,minimum_term_days,target_term_days,investment_structure,ownership_vehicle,finance_security_partner,controlled_account_details,recovery_rights,distribution_waterfall,primary_risks,disclosure_statement,submitted_at,approved_at,published_at) VALUES(?,?,?, ?,?,'PROMOTER','PUBLISHED','INVESTABLE','OPEN',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 90 DAY),1,?,?,?,?,'PLANNED',?,?,?,'NGN',?,?,?,?,'Economic participation in the equipment investment deal','Equipment.ng/Nonagon controlled asset-holding vehicle','Approved demo Finance/Security Partner','Investor funds are received only into the designated controlled account.','Contractual recovery, refinancing, redeployment and liquidation rights apply.','Approved costs and secured obligations, taxes and liabilities, investor entitlements, then residual balance.','Demand, utilization, downtime, maintenance, counterparty, logistics, FX, certification and regulatory risks.','DEMO OPPORTUNITY. Scenario projections are illustrative and are not guaranteed. Participation does not confer legal title.',UTC_TIMESTAMP(),UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE title=VALUES(title),status='PUBLISHED',publication_mode='INVESTABLE',funding_status='OPEN',equipment_type_id=VALUES(equipment_type_id),industry=VALUES(industry),quantity=VALUES(quantity),target_geography=VALUES(target_geography),opportunity_rationale=VALUES(opportunity_rationale),target_funding_amount=VALUES(target_funding_amount),minimum_participation=VALUES(minimum_participation),target_term_months=VALUES(target_term_months),asset_useful_life_days=VALUES(asset_useful_life_days),minimum_term_days=VALUES(minimum_term_days),target_term_days=VALUES(target_term_days),updated_at=UTC_TIMESTAMP()")
   ->execute([$id,$user['owner_id'],$promoterId,$user['id'],$title,$type,$industry,$quantity,$geography,$rationale,$target,$minimum,$term,$usefulLifeDays,$minimumDays,$targetDays]);
  db()->prepare("INSERT INTO investment_technical_profiles(opportunity_id,specification,oem_name,model_name,equipment_condition,subassemblies,commissioning_requirements,certification_requirements,serviceability,parts_support) VALUES(?,?,?,?,?,'Supplier standard package','Pre-delivery inspection, receiving inspection and site commissioning required.','Current inspection, test and operating certificates required before deployment.','Maintainable through approved workshop and field-support arrangements.','Initial critical spares and documented parts-support plan required.') ON DUPLICATE KEY UPDATE specification=VALUES(specification),oem_name=VALUES(oem_name),model_name=VALUES(model_name),equipment_condition=VALUES(equipment_condition)")->execute([$id,$spec,$oem,$model,$condition]);
  db()->prepare("INSERT INTO investment_acquisition_profiles(opportunity_id,supplier_name,supplier_relationship,purchase_cost,logistics_cost,landed_cost,lead_time_days,warranty_terms,payment_terms,inspection_requirements,commissioning_requirements) VALUES(?,?,?,?,?,?,60,'Supplier warranty subject to final quotation.','Milestone payment through approved controlled process.','Independent pre-delivery and receiving inspection.','Commissioning and acceptance record required.') ON DUPLICATE KEY UPDATE supplier_name=VALUES(supplier_name),purchase_cost=VALUES(purchase_cost),logistics_cost=VALUES(logistics_cost),landed_cost=VALUES(landed_cost)")->execute([$id,$supplier,'Verified supplier relationship',$purchase,$logistics,$landed]);
  foreach([['DOWNSIDE',.72,.82,-4],['BASE',1,1,0],['UPSIDE',1.18,1.09,3.5]] as [$scenario,$revFactor,$costFactor,$returnDelta]){db()->prepare("INSERT INTO investment_financial_scenarios(id,opportunity_id,scenario_type,currency,purchase_cost,landed_cost,insurance_cost,initial_spares,contingency,lease_rate,utilization_percent,downtime_percent,projected_revenue,operating_expense,maintenance_cost,management_fee,reserve_amount,residual_value,projected_return_percent,assumptions) VALUES(?,?,?,'NGN',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE purchase_cost=VALUES(purchase_cost),landed_cost=VALUES(landed_cost),insurance_cost=VALUES(insurance_cost),initial_spares=VALUES(initial_spares),contingency=VALUES(contingency),lease_rate=VALUES(lease_rate),utilization_percent=VALUES(utilization_percent),downtime_percent=VALUES(downtime_percent),projected_revenue=VALUES(projected_revenue),operating_expense=VALUES(operating_expense),maintenance_cost=VALUES(maintenance_cost),management_fee=VALUES(management_fee),reserve_amount=VALUES(reserve_amount),residual_value=VALUES(residual_value),projected_return_percent=VALUES(projected_return_percent),assumptions=VALUES(assumptions)")->execute([uuid(),$id,$scenario,$purchase,$landed,$target*.025,$target*.02,$target*.04,$rate,max(0,min(100,$utilization+($scenario==='DOWNSIDE'?-18:($scenario==='UPSIDE'?10:0)))),min(100,$downtime+($scenario==='DOWNSIDE'?12:($scenario==='UPSIDE'?-4:0))),$revenue*$revFactor,$opex*$costFactor,$opex*.18*$costFactor,$revenue*$revFactor*.05,$revenue*$revFactor*.08,$purchase*.55,(float)$return+$returnDelta,$scenario.' demo assumptions; not guaranteed.']);}
  db()->prepare("INSERT INTO investment_demand_evidence(id,opportunity_id,evidence_type,evidence_strength,title,notes,created_by) VALUES(?,?,'SUPPLY_SHORTAGE','SOFT_INTEREST','Demo market-demand hypothesis','Demo evidence for product testing; replace with verified commercial evidence before real capital deployment.',?) ON DUPLICATE KEY UPDATE title=VALUES(title),notes=VALUES(notes),created_by=VALUES(created_by)")->execute([str_replace('71000000','72000000',$id),$id,$user['id']]);
  db()->prepare("INSERT INTO investment_funding_instructions(opportunity_id,finance_partner,account_name,bank_name,account_reference,instructions,approved_by) VALUES(?,'Approved demo Finance/Security Partner','NONAGON DEMO CONTROLLED ACCOUNT','Demo Bank',?,'DEMO ONLY — do not transfer real funds. Replace with approved live instructions before launch.',?) ON DUPLICATE KEY UPDATE account_reference=VALUES(account_reference),instructions=VALUES(instructions),approved_by=VALUES(approved_by)")->execute([$id,'DEMO-'.substr($id,-4),$user['id']]);
 }
 $pdo->commit();echo "Seeded 4 demo investment opportunities.\n";
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
