<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
require dirname(__DIR__).'/app/qhse.php';require_once dirname(__DIR__).'/app/equipment-catalog.php';
$owner=uuid();$userId=uuid();$customer=uuid();$asset=uuid();$checks=0;$failed=false;
function cert_check(bool $condition,string $message):void{global $checks;if(!$condition)throw new RuntimeException($message);$checks++;}
foreach(rows("SELECT id FROM owners WHERE name='Certificate Fixture' AND email LIKE '%@example.invalid'") as $stale){$staleId=$stale['id'];db()->prepare('DELETE FROM qhse_reusable_values WHERE owner_id=?')->execute([$staleId]);db()->prepare('DELETE FROM equipment_statuses WHERE owner_id=?')->execute([$staleId]);db()->prepare('DELETE FROM user_scopes WHERE user_id IN (SELECT id FROM users WHERE owner_id=?)')->execute([$staleId]);db()->prepare('DELETE FROM units WHERE plant_id IN (SELECT id FROM plants WHERE site_id IN (SELECT id FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?)))')->execute([$staleId]);db()->prepare('DELETE FROM plants WHERE site_id IN (SELECT id FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?))')->execute([$staleId]);db()->prepare('DELETE FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?)')->execute([$staleId]);db()->prepare('DELETE FROM spaces WHERE owner_id=?')->execute([$staleId]);db()->prepare('DELETE FROM users WHERE owner_id=?')->execute([$staleId]);db()->prepare('DELETE FROM owners WHERE id=?')->execute([$staleId]);}
try{
 db()->prepare("INSERT INTO owners(id,name,email,phone) VALUES(?,?,?,'0')")->execute([$owner,'Certificate Fixture',$owner.'@example.invalid']);
 db()->prepare("INSERT INTO users(id,owner_id,full_name,email,phone,password_hash,is_email_verified,role) VALUES(?,?,?,?,'0','unused',1,'OWNER_ADMIN')")->execute([$userId,$owner,'Quality Approver',$userId.'@example.invalid']);$user=rows('SELECT * FROM users WHERE id=?',[$userId])[0];$user['company_name']='Certificate Fixture';
 $unit=equipment_default_unit($user);equipment_seed_statuses($owner);
 db()->prepare("INSERT INTO equipment(id,owner_id,unit_id,asset_code,name,status,serial_no) VALUES(?,?,?,?,?,'OPERATIONAL',?)")->execute([$asset,$owner,$unit,'CERT-ASSET-1','Pressure test pump','SN-001']);
 db()->prepare("INSERT INTO commercial_customers(id,organization_id,name,created_by) VALUES(?,?,?,?)")->execute([$customer,$owner,'Certificate Customer',$userId]);
 $quickEquipment=qhse_quick_create($user,'equipment',['name'=>'Quick pressure gauge','asset_code'=>'QHSE-QUICK-1','serial_no'=>'QSN-1','unit_id'=>$unit]);
 $quickCustomer=qhse_quick_create($user,'customer',['name'=>'Quick Customer','customer_code'=>'QC-1']);
 $quickBrand=qhse_quick_create($user,'brand',['brand_name'=>'Quick Quality','company_name'=>'Certificate Fixture']);
 $quickTemplate=qhse_quick_create($user,'template',['name'=>'Site Hydro Test','certificate_type'=>'HYDROSTATIC_PRESSURE_TEST']);
 $quickPerson=qhse_quick_create($user,'personnel',['full_name'=>'Quick Technician','email'=>'quick-'.$owner.'@example.invalid']);
 cert_check((int)rows("SELECT COUNT(*) n FROM equipment WHERE owner_id=? AND id=?",[$owner,$quickEquipment['id']])[0]['n']===1,'Quick equipment was not added to the canonical register.');
 cert_check((int)rows("SELECT COUNT(*) n FROM users WHERE owner_id=? AND id=? AND role='OPERATOR'",[$owner,$quickPerson['id']])[0]['n']===1,'Quick operator was not added to the operational team.');
 cert_check((int)rows("SELECT COUNT(*) n FROM qhse_completion_alerts WHERE owner_id=? AND status='OPEN'",[$owner])[0]['n']===5,'Quick records were not flagged for completion.');
 $technical=['test_pump'=>'Manual pressure pump','reference_range'=>'0-300 bar','test_medium'=>'Water','proof_pressure'=>['value'=>'225','unit'=>'bar'],'final_hold_time'=>['value'=>'30','unit'=>'minutes'],'working_pressure'=>['value'=>'150','unit'=>'bar'],'visual_inspection'=>'PASS','leakage_detected'=>'NO','pressure_drop_detected'=>'NO','overall_result'=>'PASS','result_statement'=>'No leakage or pressure loss observed.'];
 $input=['template_id'=>'10000000-0000-4000-8000-000000000001','customer_id'=>$customer,'inspection_test_type'=>'Hydrostatic proof test','test_date'=>gmdate('Y-m-d'),'certificate_description'=>'Pressure equipment assembly','location'=>'Test bay 1','procedure_reference'=>'QCP-HYD-01','standard_reference'=>'API 6A','validity_duration'=>'12','validity_unit'=>'MONTH','result'=>'PASS','technical_json'=>json_encode($technical),'equipment_ids'=>[$asset],'reference_equipment_ids'=>[$asset],'technician_id'=>$userId,'inspector_id'=>$userId,'reviewer_id'=>$userId,'approver_id'=>$userId];
 $id=qhse_certificate_save($user,$input);$draft=qhse_certificate($user,$id);cert_check($draft['status']==='DRAFT'&&count($draft['equipment'])===1,'Draft did not retain canonical equipment.');
 qhse_certificate_transition($user,$id,'publish');$issued=qhse_certificate($user,$id);
 cert_check($issued['status']==='ISSUED'&&$issued['display_status']==='VALID','Approved certificate did not become valid.');
 $expectedExpiry=(new DateTimeImmutable($issued['test_date'],new DateTimeZone('UTC')))->modify('+12 months')->format('Y-m-d');cert_check($issued['expiry_date']===$expectedExpiry,'Pressure-test due date was not calculated from test date plus duration.');
 cert_check(!empty($issued['issued_snapshot']),'Issued presentation was not frozen.');
 cert_check(!empty($issued['equipment'][0]['equipment_snapshot']),'Issued equipment identity was not frozen.');
 cert_check(count($issued['events'])===2,'Certificate timeline is incomplete.');
 cert_check((int)rows("SELECT COUNT(*) n FROM qhse_activity_events WHERE owner_id=? AND source_id=? AND event_type='CERTIFICATE_PUBLISHED'",[$owner,$id])[0]['n']===1,'Publish event did not reach QHSE activity.');
 cert_check(qhse_overview($user)['metrics']['certificates_issued']===1,'Issued certificate did not update the QHSE overview.');
 cert_check(qhse_certificate_display_status(array_merge($issued,['expiry_date'=>gmdate('Y-m-d',time()-86400)]))==='EXPIRED','Expiry is not date-derived.');
 $gauge=qhse_technical_payload(['technical_json'=>json_encode(['accuracy'=>'1%','range_min'=>'0','range_max'=>'100','pressure_unit'=>'bar','calibration_method'=>'Comparison','acceptance_tolerance'=>'0.5','overall_result'=>'PASS','calibration_points'=>[['point'=>'50%','reference'=>'50','instrument'=>'50.4']]])],'PRESSURE_GAUGE_CALIBRATION');cert_check($gauge['calibration_points'][0]['error']===0.4&&$gauge['calibration_points'][0]['result']==='PASS','Calibration error and tolerance were not calculated deterministically.');
 $prv=qhse_technical_payload(['technical_json'=>json_encode(['previous_set_pressure'=>['value'=>'100','unit'=>'bar'],'required_set_pressure'=>['value'=>'100','unit'=>'bar'],'prepop_performed'=>'YES','test_medium'=>'Air','overhaul_performed'=>'NO','certification_pressure'=>['value'=>'100','unit'=>'bar'],'leakage_test_performed'=>'YES','leakage_test_pressure'=>['value'=>'90','unit'=>'bar'],'final_set_pressure'=>['value'=>'100','unit'=>'bar'],'leakage_result'=>'PASS','calibration_result'=>'PASS','overall_result'=>'PASS'])],'PRESSURE_RELIEF_VALVE_CALIBRATION');cert_check($prv['test_pressure_percentage']===90.0,'PRV leakage percentage was not calculated deterministically.');
 $revision=qhse_certificate_supersede($user,$id,'Correct customer reference.');cert_check(qhse_certificate($user,$id)['status']==='SUPERSEDED'&&qhse_certificate($user,$revision)['status']==='DRAFT','Issued correction did not preserve the original and create a revision draft.');
 echo "PASS: {$checks} QHSE certificate checks.\n";
}catch(Throwable $error){fwrite(STDERR,'FAIL: '.$error->getMessage()."\n");$failed=true;}finally{
 try{db()->prepare('DELETE FROM qhse_activity_events WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM audit_logs WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM qhse_certificates WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM qhse_completion_alerts WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM qhse_certificate_templates WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM commercial_customers WHERE organization_id=?')->execute([$owner]);db()->prepare('DELETE FROM commercial_brands WHERE organization_id=?')->execute([$owner]);db()->prepare('DELETE FROM equipment WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM equipment_statuses WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM user_scopes WHERE user_id IN (SELECT id FROM users WHERE owner_id=?)')->execute([$owner]);db()->prepare('DELETE FROM units WHERE plant_id IN (SELECT id FROM plants WHERE site_id IN (SELECT id FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?)))')->execute([$owner]);db()->prepare('DELETE FROM plants WHERE site_id IN (SELECT id FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?))')->execute([$owner]);db()->prepare('DELETE FROM sites WHERE space_id IN (SELECT id FROM spaces WHERE owner_id=?)')->execute([$owner]);db()->prepare('DELETE FROM spaces WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM users WHERE owner_id=?')->execute([$owner]);db()->prepare('DELETE FROM owners WHERE id=?')->execute([$owner]);}catch(Throwable $cleanup){fwrite(STDERR,'Cleanup warning: '.$cleanup->getMessage()."\n");}
}
exit($failed?1:0);
