<?php
declare(strict_types=1);if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require dirname(__DIR__).'/app/marketplace-negotiation.php';
$pdo=db();$checks=0;$owners=[];
function negotiation_check(bool $ok,string $message):void{global $checks;if(!$ok)throw new RuntimeException($message);$checks++;}
function negotiation_denied(callable $call,int $code):void{try{$call();}catch(DomainException $e){negotiation_check($e->getCode()===$code,'Wrong denial status: '.$e->getMessage());return;}throw new RuntimeException('Expected denial');}
function negotiation_user(string $name):array{global $owners;$owner=uuid();$user=uuid();$owners[]=$owner;db()->prepare("INSERT INTO owners(id,name,email,phone) VALUES(?,?,?,'0')")->execute([$owner,$name,$owner.'@example.invalid']);db()->prepare("INSERT INTO users(id,owner_id,full_name,email,phone,role,password_hash,is_email_verified) VALUES(?,?,?,?,'0','OWNER_ADMIN','unused',1)")->execute([$user,$owner,$name,$user.'@example.invalid']);return rows('SELECT * FROM users WHERE id=?',[$user])[0];}
function negotiation_tx(callable $call):mixed{$pdo=db();$pdo->beginTransaction();try{$result=$call();$pdo->commit();return $result;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
try{
 $seller=negotiation_user('Negotiation supplier');$buyer=negotiation_user('Negotiation buyer');$outsider=negotiation_user('Negotiation outsider');$unit=equipment_default_unit($seller);equipment_seed_statuses($seller['owner_id']);$asset=marketplace_create_standard_asset($seller,$unit,'NEG-001','Negotiation excavator');$listing=uuid();
 $pdo->prepare("INSERT INTO marketplace_listings(id,asset_id,organization_id,created_by,purpose,title,description,listing_status,visibility,country,state_region,city) VALUES(?,?,?,?,?,'Negotiation excavator','Commercial negotiation fixture','ACTIVE','PUBLIC','Nigeria','Rivers','Port Harcourt')")->execute([$listing,$asset,$seller['owner_id'],$seller['id'],'LEASE_OR_SALE']);
 $pdo->prepare("INSERT INTO marketplace_lease_terms(listing_id,currency,rate,minimum_duration,duration_unit) VALUES(?,'NGN',100000,1,'DAY')")->execute([$listing]);$pdo->prepare("INSERT INTO marketplace_sale_terms(listing_id,asking_price,currency) VALUES(?,25000000,'NGN')")->execute([$listing]);
 negotiation_check(negotiation_tx(fn()=>marketplace_toggle_save($buyer,$listing)),'Buyer can save listing');negotiation_check(marketplace_saved($buyer,$listing),'Saved listing is isolated to user');negotiation_check(!marketplace_saved($outsider,$listing),'Other user does not inherit saved listing');negotiation_denied(fn()=>marketplace_toggle_save($seller,$listing),409);
 $enquiry=negotiation_tx(fn()=>marketplace_create_enquiry($buyer,['listing_id'=>$listing,'category'=>'AVAILABILITY','subject'=>'June availability','message'=>'Is the equipment available?']));$row=marketplace_enquiry($seller,$enquiry);negotiation_check($row['buyer_organization_id']===$buyer['owner_id'],'Owner receives buyer enquiry');negotiation_denied(fn()=>marketplace_enquiry($outsider,$enquiry),403);$buyerOperatorId=uuid();$pdo->prepare("INSERT INTO users(id,owner_id,full_name,email,phone,role,password_hash,is_email_verified) VALUES(?,?,?,?,'0','OPERATOR','unused',1)")->execute([$buyerOperatorId,$buyer['owner_id'],'Buyer operator',$buyerOperatorId.'@example.invalid']);$buyerOperator=rows('SELECT * FROM users WHERE id=?',[$buyerOperatorId])[0];negotiation_denied(fn()=>marketplace_enquiry($buyerOperator,$enquiry),403);
 negotiation_tx(fn()=>marketplace_send_message($seller,$enquiry,['message'=>'Yes, please submit dates.']));negotiation_check(rows('SELECT status FROM marketplace_enquiries WHERE id=?',[$enquiry])[0]['status']==='RESPONDED','Owner reply marks enquiry responded');
 $base=['listing_id'=>$listing,'enquiry_id'=>$enquiry,'transaction_type'=>'LEASE','amount'=>'90000','currency'=>'NGN','pricing_basis'=>'DAILY','lease_start_date'=>gmdate('Y-m-d',time()+864000),'lease_end_date'=>gmdate('Y-m-d',time()+1296000),'project_country'=>'Nigeria','project_state'=>'Rivers','project_city'=>'Port Harcourt','intended_use'=>'Civil works','operator_requirement'=>'OWNER_OPERATOR','valid_until'=>gmdate('Y-m-d\TH:i',time()+604800)];
 $offer=negotiation_tx(fn()=>marketplace_create_offer($buyer,$base,true));$v1=rows('SELECT * FROM marketplace_offer_versions WHERE offer_id=? AND version_number=1',[$offer])[0];negotiation_check($v1['amount']==='90000.00','Submitted offer stores version one');
 $counter=$base;$counter['amount']='95000';$counter['commercial_conditions']='Fuel by lessee';negotiation_check(negotiation_tx(fn()=>marketplace_counter_offer($seller,$offer,$counter))===2,'Owner counter creates version two');negotiation_check(rows('SELECT amount FROM marketplace_offer_versions WHERE id=?',[$v1['id']])[0]['amount']==='90000.00','Counter leaves version one unchanged');
 $revision=$base;$revision['amount']='92500';$revision['commercial_conditions']='Fuel shared';negotiation_check(negotiation_tx(fn()=>marketplace_counter_offer($buyer,$offer,$revision))===3,'Buyer revision creates version three');negotiation_check((int)rows('SELECT COUNT(*) n FROM marketplace_offer_versions WHERE offer_id=?',[$offer])[0]['n']===3,'All offer versions remain available');
 negotiation_denied(fn()=>negotiation_tx(fn()=>marketplace_offer_decision($seller,$offer,'accept',2)),409);
 $second=negotiation_tx(fn()=>marketplace_create_offer($buyer,array_merge($base,['amount'=>'91000']),true));negotiation_tx(fn()=>marketplace_offer_decision($seller,$offer,'accept',3));$accepted=marketplace_offer($seller,$offer);negotiation_check($accepted['status']==='ACCEPTED'&&$accepted['accepted_version_id']===$accepted['version_id'],'Acceptance pins exact current version');negotiation_check((int)rows('SELECT COUNT(*) n FROM marketplace_transactions WHERE accepted_offer_id=?',[$offer])[0]['n']===1,'Acceptance freezes a transaction');negotiation_check((int)rows("SELECT COUNT(*) n FROM marketplace_reservations WHERE offer_id=? AND status='CONFIRMED'",[$offer])[0]['n']===1,'Lease acceptance creates confirmed reservation');negotiation_denied(fn()=>negotiation_tx(fn()=>marketplace_offer_decision($seller,$second,'accept',1)),409);
 negotiation_check((int)rows("SELECT COUNT(*) n FROM audit_logs WHERE owner_id=? AND action IN ('marketplace.enquiry_created','marketplace.offer_submitted','marketplace.offer_countered','marketplace.offer_accepted')",[$seller['owner_id']])[0]['n']>=2,'Seller-side negotiation actions are audited');negotiation_check((int)rows('SELECT COUNT(*) n FROM marketplace_notifications WHERE user_id IN (?,?)',[$seller['id'],$buyer['id']])[0]['n']>=4,'Negotiation notifications are generated');
 negotiation_check(marketplace_public_listing($listing)['marketplace_status']==='RESERVED','Reserved equipment remains publicly inspectable with its status');
 negotiation_denied(fn()=>marketplace_create_enquiry($seller,['listing_id'=>$listing,'category'=>'OTHER','subject'=>'Own','message'=>'Own']),409);
 $saleAsset=marketplace_create_standard_asset($seller,$unit,'NEG-SALE-001','Negotiation sale asset');$saleListing=uuid();$pdo->prepare("INSERT INTO marketplace_listings(id,asset_id,organization_id,created_by,purpose,title,description,listing_status,visibility,country,state_region,city) VALUES(?,?,?,?,?,'Sale asset','Sale negotiation fixture','ACTIVE','PUBLIC','Nigeria','Lagos State','Lagos')")->execute([$saleListing,$saleAsset,$seller['owner_id'],$seller['id'],'SALE']);$pdo->prepare("INSERT INTO marketplace_sale_terms(listing_id,asking_price,currency) VALUES(?,5000000,'NGN')")->execute([$saleListing]);$saleBase=['listing_id'=>$saleListing,'transaction_type'=>'SALE','amount'=>'4800000','currency'=>'NGN','project_country'=>'Nigeria','valid_until'=>gmdate('Y-m-d\TH:i',time()+604800)];
 $saleDraft=negotiation_tx(fn()=>marketplace_create_offer($buyer,$saleBase,false));negotiation_check(marketplace_offer($buyer,$saleDraft)['status']==='DRAFT','Sale offer can be saved as draft');negotiation_tx(fn()=>marketplace_submit_draft($buyer,$saleDraft));negotiation_check(marketplace_offer($seller,$saleDraft)['status']==='SUBMITTED','Draft submits without changing its version');$saleSecond=negotiation_tx(fn()=>marketplace_create_offer($buyer,array_merge($saleBase,['amount'=>'4900000']),true));negotiation_tx(fn()=>marketplace_offer_decision($seller,$saleDraft,'accept',1));negotiation_denied(fn()=>negotiation_tx(fn()=>marketplace_offer_decision($seller,$saleSecond,'accept',1)),409);
 echo "PASS: {$checks} marketplace negotiation checks.\n";
}catch(Throwable $error){fwrite(STDERR,'FAIL: '.$error->getMessage()."\n");$failed=true;}
finally{
 foreach($owners as $owner){
  $pdo->prepare('DELETE FROM marketplace_notifications WHERE user_id IN (SELECT id FROM users WHERE owner_id=?)')->execute([$owner]);
 }
 $pdo->exec("DELETE FROM marketplace_message_attachments WHERE message_id IN (SELECT id FROM marketplace_messages WHERE conversation_id IN (SELECT id FROM marketplace_conversations WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR owner_organization_id IN ('".implode("','",$owners)."')))");
 $pdo->exec("DELETE FROM marketplace_messages WHERE conversation_id IN (SELECT id FROM marketplace_conversations WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR owner_organization_id IN ('".implode("','",$owners)."'))");
 $pdo->exec("DELETE FROM marketplace_transactions WHERE supplier_organization_id IN ('".implode("','",$owners)."') OR customer_organization_id IN ('".implode("','",$owners)."')");
 $pdo->exec("DELETE FROM marketplace_reservations WHERE offer_id IN (SELECT id FROM marketplace_offers WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR seller_organization_id IN ('".implode("','",$owners)."'))");
 $pdo->exec("UPDATE marketplace_offers SET accepted_version_id=NULL WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR seller_organization_id IN ('".implode("','",$owners)."')");
 $pdo->exec("UPDATE marketplace_offer_versions SET response_to_version_id=NULL WHERE offer_id IN (SELECT id FROM marketplace_offers WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR seller_organization_id IN ('".implode("','",$owners)."'))");
 $pdo->exec("DELETE FROM marketplace_offer_versions WHERE offer_id IN (SELECT id FROM marketplace_offers WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR seller_organization_id IN ('".implode("','",$owners)."'))");
 $pdo->exec("DELETE FROM marketplace_offers WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR seller_organization_id IN ('".implode("','",$owners)."')");
 $pdo->exec("DELETE FROM marketplace_conversations WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR owner_organization_id IN ('".implode("','",$owners)."')");
 $pdo->exec("DELETE FROM marketplace_enquiries WHERE buyer_organization_id IN ('".implode("','",$owners)."') OR owner_organization_id IN ('".implode("','",$owners)."')");
 foreach($owners as $owner){$pdo->prepare('DELETE s FROM marketplace_saved_listings s JOIN users u ON u.id=s.user_id WHERE u.owner_id=?')->execute([$owner]);$pdo->prepare('DELETE lt FROM marketplace_lease_terms lt JOIN marketplace_listings l ON l.id=lt.listing_id WHERE l.organization_id=?')->execute([$owner]);$pdo->prepare('DELETE st FROM marketplace_sale_terms st JOIN marketplace_listings l ON l.id=st.listing_id WHERE l.organization_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM marketplace_listings WHERE organization_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM audit_logs WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM dashboard_events WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment_statuses WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM owners WHERE id=?')->execute([$owner]);}
 echo "Negotiation fixtures removed.\n";
}
exit(!empty($failed)?1:0);
