<?php
declare(strict_types=1);if(PHP_SAPI!=='cli'){http_response_code(404);exit;}require dirname(__DIR__).'/app/marketplace.php';
$pdo=db();$checks=0;$owners=[];
function market_check(bool $condition,string $message):void{global $checks;if(!$condition)throw new RuntimeException($message);$checks++;}
function market_denied(callable $call,int $code):void{try{$call();}catch(DomainException $e){market_check($e->getCode()===$code,'Wrong denial code for '.$e->getMessage());return;}throw new RuntimeException('Expected marketplace denial');}
function market_owner(string $name):array{global $owners;$owner=uuid();$user=uuid();$owners[]=$owner;db()->prepare('INSERT INTO owners(id,name) VALUES(?,?)')->execute([$owner,$name]);db()->prepare("INSERT INTO users(id,owner_id,full_name,email,phone,password_hash,is_email_verified) VALUES(?,?,?,?,'0','unused',1)")->execute([$user,$owner,$name,$user.'@example.invalid']);return rows('SELECT * FROM users WHERE id=?',[$user])[0];}
try{
 $user=market_owner('Marketplace test supplier');$buyer=market_owner('Marketplace test buyer');$unit=equipment_default_unit($user);equipment_seed_statuses($user['owner_id']);
 $category=catalog_create($user,'category',['name'=>'Marketplace pumps','industry'=>'Energy']);$sub=catalog_create($user,'subcategory',['name'=>'Injection pumps','category_id'=>$category]);$type=catalog_create($user,'type',['name'=>'Chemical injection pump','subcategory_id'=>$sub]);
 $standardAsset=marketplace_create_standard_asset($user,$unit,'MKT-STANDARD-001','Marketplace standard asset');$standardRow=rows('SELECT marketplace_only,status,status_id FROM equipment_list_view WHERE id=? AND owner_id=?',[$standardAsset,$user['owner_id']])[0]??null;market_check($standardRow!==null&&!(bool)$standardRow['marketplace_only'],'Marketplace-created asset appears in Equipment as standard');market_check($standardRow['status']==='OPERATIONAL'&&$standardRow['status_id']!==null,'Marketplace-created asset receives operational status');
 $oem=marketplace_oem($user,['new_oem'=>'Marketplace Test OEM']);$model=marketplace_model($user,['new_model'=>'MP-15000'],$oem,$type);
 market_check(marketplace_specs("Pressure: 15,000 PSI")['Pressure']==='15,000 PSI','Labelled specifications parse');market_check(marketplace_specs("15,000 PSI")['Specification 1']==='15,000 PSI','Plain specification lines remain saveable');
 market_check(rows('SELECT verification_status FROM marketplace_oems WHERE id=?',[$oem])[0]['verification_status']==='PENDING','Suggested OEM is pending');
 market_check(marketplace_oem($user,['new_oem'=>'Marketplace Test OEM'])===$oem,'Canonical OEM slug avoids duplicate spelling');
 $asset=uuid();$pdo->prepare("INSERT INTO equipment(id,owner_id,unit_id,asset_code,name,type_id,subcategory_id,category_id,serial_no,operator_id,condition_remarks,marketplace_oem_id,marketplace_oem_model_id,marketplace_specifications) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$asset,$user['owner_id'],$unit,'MKT-TEST-001','15K Chemical Injection Pump',$type,$sub,$category,'PRIVATE-SERIAL',$user['id'],'PRIVATE INTERNAL NOTE',$oem,$model,json_encode(['Maximum pressure'=>'15,000 PSI'])]);
 $listing=uuid();$pdo->prepare("INSERT INTO marketplace_listings(id,asset_id,organization_id,created_by,purpose,title,description,country,state_region,city,price_visibility,public_specifications) VALUES(?,?,?,?,?,'15K Injection Pump','Configured for pressure testing','Nigeria','Rivers','Port Harcourt','PUBLIC',?)")->execute([$listing,$asset,$user['owner_id'],$user['id'],'LEASE_OR_SALE',json_encode(['Maximum pressure'=>'15,000 PSI','Pump action'=>'Double acting'])]);
 $pdo->prepare("INSERT INTO marketplace_lease_terms(listing_id,daily_rate,monthly_rate,currency,rate,minimum_duration,duration_unit,negotiable,operator_included,operator_rate,consumables_included,mobilization_option,demobilization_option,maintenance_option,insurance_option) VALUES(?,100000,2000000,'NGN',100000,1,'DAY',1,1,25000,1,'OWNER_DELIVERS','OWNER_COLLECTS','OWNER_FULL','LESSEE_PROVIDES')")->execute([$listing]);$pdo->prepare("INSERT INTO marketplace_sale_terms(listing_id,asking_price,currency,negotiable,payment_terms,`condition`,taxes_fees) VALUES(?,25000000,'NGN',1,'DEPOSIT_BALANCE','AS_IS','BUYER')")->execute([$listing]);
 $nigeria=rows("SELECT id FROM marketplace_locations WHERE country_code='NG' AND location_type='COUNTRY'")[0]['id'];$borno=rows("SELECT id FROM marketplace_locations WHERE country_code='NG' AND location_type='REGION' AND canonical_name='Borno'")[0]['id'];marketplace_save_location_rules($user,$listing,json_encode([['id'=>$nigeria,'rule'=>'ALLOW'],['id'=>$borno,'rule'=>'RESTRICT']]));market_check(count(marketplace_location_rules($listing))===2,'Structured geographic rules saved');market_denied(fn()=>marketplace_save_location_rules($user,$listing,json_encode([['id'=>$nigeria,'rule'=>'ALLOW'],['id'=>$nigeria,'rule'=>'RESTRICT']])),422);
 $pdo->beginTransaction();market_denied(fn()=>marketplace_publish($user,$listing),422);$pdo->rollBack();
 $media=uuid();$png=base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=');$pdo->prepare("INSERT INTO marketplace_listing_media(id,listing_id,media_type,title,mime_type,file_data,visibility,is_primary) VALUES(?,?,'IMAGE','Public equipment image','image/png',?,'PUBLIC',1)")->execute([$media,$listing,$png]);
 $pdo->beginTransaction();marketplace_publish($user,$listing);$pdo->commit();
 $public=marketplace_public_listing($listing);market_check($public['title']==='15K Injection Pump','Published listing is publicly readable');
 market_check(!array_key_exists('serial_no',$public)&&!array_key_exists('operator_id',$public)&&!array_key_exists('condition_remarks',$public)&&!array_key_exists('unit_id',$public),'Public projection excludes ERP-private fields');
 market_denied(fn()=>marketplace_owned_listing($buyer,$listing),404);
 foreach([['q'=>'15K pump'],['purpose'=>'LEASE_OR_SALE'],['city'=>'Port Harcourt'],['available_now'=>'1'],['certified'=>'1'],['max_daily'=>'100000'],['negotiable'=>'1'],['operator_included'=>'1']] as $filter){[$where,$arguments]=marketplace_public_scope($filter);$count=(int)rows("SELECT COUNT(*) n FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id LEFT JOIN equipment_categories c ON c.id=e.category_id LEFT JOIN equipment_types t ON t.id=e.type_id LEFT JOIN marketplace_oems o ON o.id=e.marketplace_oem_id LEFT JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id LEFT JOIN marketplace_lease_terms lt ON lt.listing_id=l.id LEFT JOIN marketplace_sale_terms st ON st.listing_id=l.id WHERE {$where} AND l.id=?",[...$arguments,$listing])[0]['n'];market_check($count===($filter===['certified'=>'1']?0:1),'Marketplace filter '.array_key_first($filter));}
 $pdo->prepare("UPDATE marketplace_listings SET compliance_status='VALID',certification_type='Pressure test',certification_valid_until=DATE_ADD(UTC_DATE(),INTERVAL 1 YEAR),last_inspected_on=UTC_DATE() WHERE id=?")->execute([$listing]);
 foreach([['certified'=>'1'],['certification_type'=>'Pressure'],['recently_inspected'=>'1']] as $filter){[$where,$arguments]=marketplace_public_scope($filter);market_check((int)rows("SELECT COUNT(*) n FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id LEFT JOIN equipment_categories c ON c.id=e.category_id LEFT JOIN equipment_types t ON t.id=e.type_id LEFT JOIN marketplace_oems o ON o.id=e.marketplace_oem_id LEFT JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id LEFT JOIN marketplace_lease_terms lt ON lt.listing_id=l.id LEFT JOIN marketplace_sale_terms st ON st.listing_id=l.id WHERE {$where} AND l.id=?",[...$arguments,$listing])[0]['n']===1,'Compliance filter '.array_key_first($filter));}
 $pdo->prepare("INSERT INTO marketplace_availability_periods(id,listing_id,start_date,end_date,availability,note) VALUES(?,?,UTC_DATE(),DATE_ADD(UTC_DATE(),INTERVAL 2 DAY),'UNAVAILABLE','Booked')")->execute([uuid(),$listing]);[$where,$arguments]=marketplace_public_scope(['available_now'=>'1']);market_check((int)rows("SELECT COUNT(*) n FROM marketplace_listings l JOIN equipment e ON e.id=l.asset_id LEFT JOIN equipment_categories c ON c.id=e.category_id LEFT JOIN equipment_types t ON t.id=e.type_id LEFT JOIN marketplace_oems o ON o.id=e.marketplace_oem_id LEFT JOIN marketplace_oem_models m ON m.id=e.marketplace_oem_model_id LEFT JOIN marketplace_lease_terms lt ON lt.listing_id=l.id LEFT JOIN marketplace_sale_terms st ON st.listing_id=l.id WHERE {$where} AND l.id=?",[...$arguments,$listing])[0]['n']===0,'Availability calendar blocks unavailable date');
 $pdo->beginTransaction();$pdo->prepare("UPDATE equipment SET status='MAINTENANCE' WHERE id=?")->execute([$asset]);marketplace_apply_operational_status($user,$asset);$pdo->commit();market_check(rows('SELECT marketplace_status FROM marketplace_listings WHERE id=?',[$listing])[0]['marketplace_status']==='MAINTENANCE','ERP maintenance overrides availability');
 $pdo->beginTransaction();$pdo->prepare("UPDATE equipment SET status='OPERATIONAL' WHERE id=?")->execute([$asset]);marketplace_apply_operational_status($user,$asset);$pdo->commit();market_check(rows('SELECT marketplace_status FROM marketplace_listings WHERE id=?',[$listing])[0]['marketplace_status']==='AVAILABLE','ERP clearance restores marketplace availability');
 $pdo->beginTransaction();marketplace_transition($user,$listing,'PAUSED');$pdo->commit();market_denied(fn()=>marketplace_public_listing($listing),404);$pdo->beginTransaction();market_denied(fn()=>marketplace_transition($user,$listing,'ACTIVE'),409);$pdo->rollBack();$pdo->prepare('UPDATE equipment SET type_id=NULL WHERE id=?')->execute([$asset]);market_check(marketplace_publish_issues($user,$listing)===[],'Category classification can publish without a specific equipment type');$pdo->beginTransaction();marketplace_publish($user,$listing);$pdo->commit();
 if(function_exists('curl_init')){foreach(['','marketplace','marketplace?q=15K+pump','marketplace?purpose=LEASE_OR_SALE&city=Port+Harcourt','marketplace-listing?id='.$listing,'marketplace-company?id='.$user['owner_id'],'marketplace-media?id='.$media] as $route){$curl=curl_init('http://localhost/nonagon/'.$route);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>10]);$body=curl_exec($curl);$status=curl_getinfo($curl,CURLINFO_HTTP_CODE);curl_close($curl);market_check($status===200&&$body!==false,'Public route '.$route);if(!str_starts_with($route,'marketplace-media')){market_check(str_contains((string)$body,'class="public-header header wrap"')&&str_contains((string)$body,'class="public-footer footer wrap"'),'Shared public shell '.$route);market_check(str_contains((string)$body,'>Tools</a>')&&str_contains((string)$body,'assets/images/logo-dark.svg'),'Nonagon public navigation '.$route);market_check(!str_contains((string)$body,'PRIVATE-SERIAL'),'Private serial absent from '.$route);}}}
 echo "PASS: {$checks} marketplace checks.\n";
}catch(Throwable $error){fwrite(STDERR,'FAIL: '.$error->getMessage()."\n");$failed=true;}
finally{foreach($owners as $owner){$pdo->prepare('DELETE m FROM marketplace_listing_media m JOIN marketplace_listings l ON l.id=m.listing_id WHERE l.organization_id=?')->execute([$owner]);$pdo->prepare('DELETE lt FROM marketplace_lease_terms lt JOIN marketplace_listings l ON l.id=lt.listing_id WHERE l.organization_id=?')->execute([$owner]);$pdo->prepare('DELETE st FROM marketplace_sale_terms st JOIN marketplace_listings l ON l.id=st.listing_id WHERE l.organization_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM marketplace_listings WHERE organization_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM audit_logs WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM dashboard_events WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment_statuses WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM marketplace_oem_models WHERE oem_id IN (SELECT id FROM marketplace_oems WHERE suggested_by_owner_id=?)')->execute([$owner]);$pdo->prepare('DELETE FROM marketplace_oems WHERE suggested_by_owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment_types WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment_subcategories WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM equipment_categories WHERE owner_id=?')->execute([$owner]);$pdo->prepare('DELETE FROM owners WHERE id=?')->execute([$owner]);}echo "Marketplace fixtures removed.\n";}
exit(!empty($failed)?1:0);
