ALTER TABLE marketplace_lease_terms
  MODIFY duration_unit ENUM('HOUR','DAY','WEEK','MONTH') NULL,
  ADD COLUMN rate DECIMAL(15,2) NULL AFTER currency,
  ADD COLUMN operator_rate DECIMAL(15,2) NULL AFTER operator_included,
  ADD COLUMN consumables_included TINYINT(1) NOT NULL DEFAULT 0 AFTER fuel_included,
  ADD COLUMN consumables_details VARCHAR(500) NULL AFTER consumables_included,
  ADD COLUMN mobilization_option VARCHAR(60) NULL AFTER mobilization_terms,
  ADD COLUMN mobilization_custom TEXT NULL AFTER mobilization_option,
  ADD COLUMN demobilization_option VARCHAR(60) NULL AFTER demobilization_terms,
  ADD COLUMN demobilization_custom TEXT NULL AFTER demobilization_option,
  ADD COLUMN maintenance_option VARCHAR(80) NULL AFTER maintenance_responsibility,
  ADD COLUMN maintenance_details TEXT NULL AFTER maintenance_option,
  ADD COLUMN insurance_option VARCHAR(80) NULL AFTER insurance_requirement,
  ADD COLUMN insurance_details TEXT NULL AFTER insurance_option;

UPDATE marketplace_lease_terms
SET rate=CASE duration_unit WHEN 'WEEK' THEN weekly_rate WHEN 'MONTH' THEN monthly_rate ELSE daily_rate END,
    consumables_included=fuel_included
WHERE rate IS NULL;

ALTER TABLE marketplace_sale_terms
  MODIFY `condition` ENUM('NEW','EXCELLENT','GOOD','FAIR','AS_IS','INSPECTED','SERVICED_BEFORE_HANDOVER','TO_BE_AGREED') NOT NULL DEFAULT 'AS_IS',
  ADD COLUMN payment_terms VARCHAR(40) NULL AFTER negotiable,
  ADD COLUMN payment_terms_custom TEXT NULL AFTER payment_terms,
  ADD COLUMN taxes_fees VARCHAR(40) NULL AFTER `condition`;

CREATE TABLE marketplace_locations (
  id CHAR(36) PRIMARY KEY,
  canonical_name VARCHAR(180) NOT NULL,
  location_type ENUM('COUNTRY','REGION','CITY') NOT NULL,
  country_code CHAR(2) NOT NULL,
  country_name VARCHAR(100) NULL,
  parent_id CHAR(36) NULL,
  search_name VARCHAR(350) GENERATED ALWAYS AS (LOWER(CONCAT_WS(' ',canonical_name,country_name,country_code))) STORED,
  UNIQUE KEY marketplace_location_identity(country_code,location_type,canonical_name),
  KEY marketplace_location_search(search_name(150)),
  KEY marketplace_location_parent(parent_id),
  CONSTRAINT marketplace_location_parent_fk FOREIGN KEY(parent_id) REFERENCES marketplace_locations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE marketplace_listing_location_rules (
  id CHAR(36) PRIMARY KEY,
  listing_id CHAR(36) NOT NULL,
  location_id CHAR(36) NOT NULL,
  rule_type ENUM('ALLOW','RESTRICT') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY marketplace_listing_location_unique(listing_id,location_id),
  KEY marketplace_listing_location_location(location_id,rule_type),
  CONSTRAINT marketplace_listing_location_listing_fk FOREIGN KEY(listing_id) REFERENCES marketplace_listings(id) ON DELETE CASCADE,
  CONSTRAINT marketplace_listing_location_location_fk FOREIGN KEY(location_id) REFERENCES marketplace_locations(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO marketplace_locations(id,canonical_name,location_type,country_code,country_name,parent_id) VALUES
(UUID(),'Afghanistan','COUNTRY','AF',NULL,NULL),
(UUID(),'Albania','COUNTRY','AL',NULL,NULL),
(UUID(),'Algeria','COUNTRY','DZ',NULL,NULL),
(UUID(),'Andorra','COUNTRY','AD',NULL,NULL),
(UUID(),'Angola','COUNTRY','AO',NULL,NULL),
(UUID(),'Antigua and Barbuda','COUNTRY','AG',NULL,NULL),
(UUID(),'Argentina','COUNTRY','AR',NULL,NULL),
(UUID(),'Armenia','COUNTRY','AM',NULL,NULL),
(UUID(),'Australia','COUNTRY','AU',NULL,NULL),
(UUID(),'Austria','COUNTRY','AT',NULL,NULL),
(UUID(),'Azerbaijan','COUNTRY','AZ',NULL,NULL),
(UUID(),'Bahamas','COUNTRY','BS',NULL,NULL),
(UUID(),'Bahrain','COUNTRY','BH',NULL,NULL),
(UUID(),'Bangladesh','COUNTRY','BD',NULL,NULL),
(UUID(),'Barbados','COUNTRY','BB',NULL,NULL),
(UUID(),'Belarus','COUNTRY','BY',NULL,NULL),
(UUID(),'Belgium','COUNTRY','BE',NULL,NULL),
(UUID(),'Belize','COUNTRY','BZ',NULL,NULL),
(UUID(),'Benin','COUNTRY','BJ',NULL,NULL),
(UUID(),'Bhutan','COUNTRY','BT',NULL,NULL),
(UUID(),'Bolivia','COUNTRY','BO',NULL,NULL),
(UUID(),'Bosnia and Herzegovina','COUNTRY','BA',NULL,NULL),
(UUID(),'Botswana','COUNTRY','BW',NULL,NULL),
(UUID(),'Brazil','COUNTRY','BR',NULL,NULL),
(UUID(),'Brunei','COUNTRY','BN',NULL,NULL),
(UUID(),'Bulgaria','COUNTRY','BG',NULL,NULL),
(UUID(),'Burkina Faso','COUNTRY','BF',NULL,NULL),
(UUID(),'Burundi','COUNTRY','BI',NULL,NULL),
(UUID(),'Cabo Verde','COUNTRY','CV',NULL,NULL),
(UUID(),'Cambodia','COUNTRY','KH',NULL,NULL),
(UUID(),'Cameroon','COUNTRY','CM',NULL,NULL),
(UUID(),'Canada','COUNTRY','CA',NULL,NULL),
(UUID(),'Central African Republic','COUNTRY','CF',NULL,NULL),
(UUID(),'Chad','COUNTRY','TD',NULL,NULL),
(UUID(),'Chile','COUNTRY','CL',NULL,NULL),
(UUID(),'China','COUNTRY','CN',NULL,NULL),
(UUID(),'Colombia','COUNTRY','CO',NULL,NULL),
(UUID(),'Comoros','COUNTRY','KM',NULL,NULL),
(UUID(),'Congo','COUNTRY','CG',NULL,NULL),
(UUID(),'Congo, Democratic Republic','COUNTRY','CD',NULL,NULL),
(UUID(),'Costa Rica','COUNTRY','CR',NULL,NULL),
(UUID(),'Cote d''Ivoire','COUNTRY','CI',NULL,NULL),
(UUID(),'Croatia','COUNTRY','HR',NULL,NULL),
(UUID(),'Cuba','COUNTRY','CU',NULL,NULL),
(UUID(),'Cyprus','COUNTRY','CY',NULL,NULL),
(UUID(),'Czechia','COUNTRY','CZ',NULL,NULL),
(UUID(),'Denmark','COUNTRY','DK',NULL,NULL),
(UUID(),'Djibouti','COUNTRY','DJ',NULL,NULL),
(UUID(),'Dominica','COUNTRY','DM',NULL,NULL),
(UUID(),'Dominican Republic','COUNTRY','DO',NULL,NULL),
(UUID(),'Ecuador','COUNTRY','EC',NULL,NULL),
(UUID(),'Egypt','COUNTRY','EG',NULL,NULL),
(UUID(),'El Salvador','COUNTRY','SV',NULL,NULL),
(UUID(),'Equatorial Guinea','COUNTRY','GQ',NULL,NULL),
(UUID(),'Eritrea','COUNTRY','ER',NULL,NULL),
(UUID(),'Estonia','COUNTRY','EE',NULL,NULL),
(UUID(),'Eswatini','COUNTRY','SZ',NULL,NULL),
(UUID(),'Ethiopia','COUNTRY','ET',NULL,NULL),
(UUID(),'Fiji','COUNTRY','FJ',NULL,NULL),
(UUID(),'Finland','COUNTRY','FI',NULL,NULL),
(UUID(),'France','COUNTRY','FR',NULL,NULL),
(UUID(),'Gabon','COUNTRY','GA',NULL,NULL),
(UUID(),'Gambia','COUNTRY','GM',NULL,NULL),
(UUID(),'Georgia','COUNTRY','GE',NULL,NULL),
(UUID(),'Germany','COUNTRY','DE',NULL,NULL),
(UUID(),'Ghana','COUNTRY','GH',NULL,NULL),
(UUID(),'Greece','COUNTRY','GR',NULL,NULL),
(UUID(),'Grenada','COUNTRY','GD',NULL,NULL),
(UUID(),'Guatemala','COUNTRY','GT',NULL,NULL),
(UUID(),'Guinea','COUNTRY','GN',NULL,NULL),
(UUID(),'Guinea-Bissau','COUNTRY','GW',NULL,NULL),
(UUID(),'Guyana','COUNTRY','GY',NULL,NULL),
(UUID(),'Haiti','COUNTRY','HT',NULL,NULL),
(UUID(),'Honduras','COUNTRY','HN',NULL,NULL),
(UUID(),'Hungary','COUNTRY','HU',NULL,NULL),
(UUID(),'Iceland','COUNTRY','IS',NULL,NULL),
(UUID(),'India','COUNTRY','IN',NULL,NULL),
(UUID(),'Indonesia','COUNTRY','ID',NULL,NULL),
(UUID(),'Iran','COUNTRY','IR',NULL,NULL),
(UUID(),'Iraq','COUNTRY','IQ',NULL,NULL),
(UUID(),'Ireland','COUNTRY','IE',NULL,NULL),
(UUID(),'Israel','COUNTRY','IL',NULL,NULL),
(UUID(),'Italy','COUNTRY','IT',NULL,NULL),
(UUID(),'Jamaica','COUNTRY','JM',NULL,NULL),
(UUID(),'Japan','COUNTRY','JP',NULL,NULL),
(UUID(),'Jordan','COUNTRY','JO',NULL,NULL),
(UUID(),'Kazakhstan','COUNTRY','KZ',NULL,NULL),
(UUID(),'Kenya','COUNTRY','KE',NULL,NULL),
(UUID(),'Kiribati','COUNTRY','KI',NULL,NULL),
(UUID(),'North Korea','COUNTRY','KP',NULL,NULL),
(UUID(),'South Korea','COUNTRY','KR',NULL,NULL),
(UUID(),'Kuwait','COUNTRY','KW',NULL,NULL),
(UUID(),'Kyrgyzstan','COUNTRY','KG',NULL,NULL),
(UUID(),'Laos','COUNTRY','LA',NULL,NULL),
(UUID(),'Latvia','COUNTRY','LV',NULL,NULL),
(UUID(),'Lebanon','COUNTRY','LB',NULL,NULL),
(UUID(),'Lesotho','COUNTRY','LS',NULL,NULL),
(UUID(),'Liberia','COUNTRY','LR',NULL,NULL),
(UUID(),'Libya','COUNTRY','LY',NULL,NULL),
(UUID(),'Liechtenstein','COUNTRY','LI',NULL,NULL),
(UUID(),'Lithuania','COUNTRY','LT',NULL,NULL),
(UUID(),'Luxembourg','COUNTRY','LU',NULL,NULL),
(UUID(),'Madagascar','COUNTRY','MG',NULL,NULL),
(UUID(),'Malawi','COUNTRY','MW',NULL,NULL),
(UUID(),'Malaysia','COUNTRY','MY',NULL,NULL),
(UUID(),'Maldives','COUNTRY','MV',NULL,NULL),
(UUID(),'Mali','COUNTRY','ML',NULL,NULL),
(UUID(),'Malta','COUNTRY','MT',NULL,NULL),
(UUID(),'Marshall Islands','COUNTRY','MH',NULL,NULL),
(UUID(),'Mauritania','COUNTRY','MR',NULL,NULL),
(UUID(),'Mauritius','COUNTRY','MU',NULL,NULL),
(UUID(),'Mexico','COUNTRY','MX',NULL,NULL),
(UUID(),'Micronesia','COUNTRY','FM',NULL,NULL),
(UUID(),'Moldova','COUNTRY','MD',NULL,NULL),
(UUID(),'Monaco','COUNTRY','MC',NULL,NULL),
(UUID(),'Mongolia','COUNTRY','MN',NULL,NULL),
(UUID(),'Montenegro','COUNTRY','ME',NULL,NULL),
(UUID(),'Morocco','COUNTRY','MA',NULL,NULL),
(UUID(),'Mozambique','COUNTRY','MZ',NULL,NULL),
(UUID(),'Myanmar','COUNTRY','MM',NULL,NULL),
(UUID(),'Namibia','COUNTRY','NA',NULL,NULL),
(UUID(),'Nauru','COUNTRY','NR',NULL,NULL),
(UUID(),'Nepal','COUNTRY','NP',NULL,NULL),
(UUID(),'Netherlands','COUNTRY','NL',NULL,NULL),
(UUID(),'New Zealand','COUNTRY','NZ',NULL,NULL),
(UUID(),'Nicaragua','COUNTRY','NI',NULL,NULL),
(UUID(),'Niger','COUNTRY','NE',NULL,NULL),
(UUID(),'Nigeria','COUNTRY','NG',NULL,NULL),
(UUID(),'North Macedonia','COUNTRY','MK',NULL,NULL),
(UUID(),'Norway','COUNTRY','NO',NULL,NULL),
(UUID(),'Oman','COUNTRY','OM',NULL,NULL),
(UUID(),'Pakistan','COUNTRY','PK',NULL,NULL),
(UUID(),'Palau','COUNTRY','PW',NULL,NULL),
(UUID(),'Palestine','COUNTRY','PS',NULL,NULL),
(UUID(),'Panama','COUNTRY','PA',NULL,NULL),
(UUID(),'Papua New Guinea','COUNTRY','PG',NULL,NULL),
(UUID(),'Paraguay','COUNTRY','PY',NULL,NULL),
(UUID(),'Peru','COUNTRY','PE',NULL,NULL),
(UUID(),'Philippines','COUNTRY','PH',NULL,NULL),
(UUID(),'Poland','COUNTRY','PL',NULL,NULL),
(UUID(),'Portugal','COUNTRY','PT',NULL,NULL),
(UUID(),'Qatar','COUNTRY','QA',NULL,NULL),
(UUID(),'Romania','COUNTRY','RO',NULL,NULL),
(UUID(),'Russia','COUNTRY','RU',NULL,NULL),
(UUID(),'Rwanda','COUNTRY','RW',NULL,NULL),
(UUID(),'Saint Kitts and Nevis','COUNTRY','KN',NULL,NULL),
(UUID(),'Saint Lucia','COUNTRY','LC',NULL,NULL),
(UUID(),'Saint Vincent and the Grenadines','COUNTRY','VC',NULL,NULL),
(UUID(),'Samoa','COUNTRY','WS',NULL,NULL),
(UUID(),'San Marino','COUNTRY','SM',NULL,NULL),
(UUID(),'Sao Tome and Principe','COUNTRY','ST',NULL,NULL),
(UUID(),'Saudi Arabia','COUNTRY','SA',NULL,NULL),
(UUID(),'Senegal','COUNTRY','SN',NULL,NULL),
(UUID(),'Serbia','COUNTRY','RS',NULL,NULL),
(UUID(),'Seychelles','COUNTRY','SC',NULL,NULL),
(UUID(),'Sierra Leone','COUNTRY','SL',NULL,NULL),
(UUID(),'Singapore','COUNTRY','SG',NULL,NULL),
(UUID(),'Slovakia','COUNTRY','SK',NULL,NULL),
(UUID(),'Slovenia','COUNTRY','SI',NULL,NULL),
(UUID(),'Solomon Islands','COUNTRY','SB',NULL,NULL),
(UUID(),'Somalia','COUNTRY','SO',NULL,NULL),
(UUID(),'South Africa','COUNTRY','ZA',NULL,NULL),
(UUID(),'South Sudan','COUNTRY','SS',NULL,NULL),
(UUID(),'Spain','COUNTRY','ES',NULL,NULL),
(UUID(),'Sri Lanka','COUNTRY','LK',NULL,NULL),
(UUID(),'Sudan','COUNTRY','SD',NULL,NULL),
(UUID(),'Suriname','COUNTRY','SR',NULL,NULL),
(UUID(),'Sweden','COUNTRY','SE',NULL,NULL),
(UUID(),'Switzerland','COUNTRY','CH',NULL,NULL),
(UUID(),'Syria','COUNTRY','SY',NULL,NULL),
(UUID(),'Taiwan','COUNTRY','TW',NULL,NULL),
(UUID(),'Tajikistan','COUNTRY','TJ',NULL,NULL),
(UUID(),'Tanzania','COUNTRY','TZ',NULL,NULL),
(UUID(),'Thailand','COUNTRY','TH',NULL,NULL),
(UUID(),'Timor-Leste','COUNTRY','TL',NULL,NULL),
(UUID(),'Togo','COUNTRY','TG',NULL,NULL),
(UUID(),'Tonga','COUNTRY','TO',NULL,NULL),
(UUID(),'Trinidad and Tobago','COUNTRY','TT',NULL,NULL),
(UUID(),'Tunisia','COUNTRY','TN',NULL,NULL),
(UUID(),'Turkiye','COUNTRY','TR',NULL,NULL),
(UUID(),'Turkmenistan','COUNTRY','TM',NULL,NULL),
(UUID(),'Tuvalu','COUNTRY','TV',NULL,NULL),
(UUID(),'Uganda','COUNTRY','UG',NULL,NULL),
(UUID(),'Ukraine','COUNTRY','UA',NULL,NULL),
(UUID(),'United Arab Emirates','COUNTRY','AE',NULL,NULL),
(UUID(),'United Kingdom','COUNTRY','GB',NULL,NULL),
(UUID(),'United States','COUNTRY','US',NULL,NULL),
(UUID(),'Uruguay','COUNTRY','UY',NULL,NULL),
(UUID(),'Uzbekistan','COUNTRY','UZ',NULL,NULL),
(UUID(),'Vanuatu','COUNTRY','VU',NULL,NULL),
(UUID(),'Vatican City','COUNTRY','VA',NULL,NULL),
(UUID(),'Venezuela','COUNTRY','VE',NULL,NULL),
(UUID(),'Vietnam','COUNTRY','VN',NULL,NULL),
(UUID(),'Yemen','COUNTRY','YE',NULL,NULL),
(UUID(),'Zambia','COUNTRY','ZM',NULL,NULL),
(UUID(),'Zimbabwe','COUNTRY','ZW',NULL,NULL);

INSERT INTO marketplace_locations(id,canonical_name,location_type,country_code,country_name,parent_id)
SELECT UUID(),x.name,'REGION','NG','Nigeria',ng.id
FROM marketplace_locations ng
JOIN (
 SELECT 'Abia' name UNION ALL SELECT 'Abuja Federal Capital Territory' UNION ALL SELECT 'Adamawa' UNION ALL SELECT 'Akwa Ibom' UNION ALL SELECT 'Anambra' UNION ALL SELECT 'Bauchi' UNION ALL SELECT 'Bayelsa' UNION ALL SELECT 'Benue' UNION ALL SELECT 'Borno' UNION ALL SELECT 'Cross River' UNION ALL SELECT 'Delta' UNION ALL SELECT 'Ebonyi' UNION ALL SELECT 'Edo' UNION ALL SELECT 'Ekiti' UNION ALL SELECT 'Enugu' UNION ALL SELECT 'Gombe' UNION ALL SELECT 'Imo' UNION ALL SELECT 'Jigawa' UNION ALL SELECT 'Kaduna' UNION ALL SELECT 'Kano' UNION ALL SELECT 'Katsina' UNION ALL SELECT 'Kebbi' UNION ALL SELECT 'Kogi' UNION ALL SELECT 'Kwara' UNION ALL SELECT 'Lagos State' UNION ALL SELECT 'Nasarawa' UNION ALL SELECT 'Niger State' UNION ALL SELECT 'Ogun' UNION ALL SELECT 'Ondo' UNION ALL SELECT 'Osun' UNION ALL SELECT 'Oyo' UNION ALL SELECT 'Plateau' UNION ALL SELECT 'Rivers' UNION ALL SELECT 'Sokoto' UNION ALL SELECT 'Taraba' UNION ALL SELECT 'Yobe' UNION ALL SELECT 'Zamfara'
) x
WHERE ng.country_code='NG' AND ng.location_type='COUNTRY';

INSERT INTO marketplace_locations(id,canonical_name,location_type,country_code,country_name,parent_id)
SELECT UUID(),x.city,'CITY',x.code,x.country,l.id
FROM (
 SELECT 'Lagos' city,'NG' code,'Nigeria' country,'Lagos State' region UNION ALL
 SELECT 'Port Harcourt','NG','Nigeria','Rivers' UNION ALL
 SELECT 'Abuja','NG','Nigeria','Abuja Federal Capital Territory' UNION ALL
 SELECT 'Kano','NG','Nigeria','Kano' UNION ALL
 SELECT 'Accra','GH','Ghana','Ghana' UNION ALL
 SELECT 'Kumasi','GH','Ghana','Ghana' UNION ALL
 SELECT 'London','GB','United Kingdom','United Kingdom' UNION ALL
 SELECT 'Dubai','AE','United Arab Emirates','United Arab Emirates' UNION ALL
 SELECT 'Houston','US','United States','United States'
) x
JOIN marketplace_locations l ON l.country_code=x.code AND ((l.location_type='REGION' AND l.canonical_name=x.region) OR (l.location_type='COUNTRY' AND l.canonical_name=x.region));
