<?php
require_once APP_ROOT.'/app/xinng.php';
$catalog=equipment_catalog($user);$canEdit=operation_can_manage($user);require_once APP_ROOT.'/app/marketplace.php';$marketListing=$canEdit?marketplace_listing_for_equipment($user,$id):null;$marketReadiness=$canEdit?marketplace_equipment_readiness($user,$id):null;
$tax=[];foreach(['category','subcategory','type','brand','model','status'] as $kind)$tax[$kind]=array_column($catalog[$kind],null,'id');
$valuation=equipment_refresh_values($id);$profile=$valuation['profile'];$calculation=$valuation['calculation'];$currency=$valuation['currency'];
$photos=rows('SELECT id,url,caption,is_primary FROM equipment_photos WHERE equipment_id=? ORDER BY created_at,id',[$id]);
$assemblies=rows('SELECT * FROM equipment_assemblies WHERE equipment_id=? ORDER BY sequence,name,id',[$id]);
$history=rows('SELECT * FROM (SELECT * FROM equipment_value_snapshot WHERE equipment_id=? AND currency=? ORDER BY as_of_date DESC,created_at DESC,id DESC LIMIT 200) recent ORDER BY as_of_date,created_at,id',[$id,$currency]);
$money=fn($value)=>$value===null?'Not recorded':$currency.' '.number_format((float)$value,2);
$record['xinng_short_url']=isset($record['xinng_short_url'])?xinng_strip_xinngqr_path((string)$record['xinng_short_url']):null;
$hasValidEquipmentShortLink=!empty($record['xinng_short_url'])&&xinng_short_url_has_back_half((string)$record['xinng_short_url'],isset($record['xinng_back_half'])?(string)$record['xinng_back_half']:null);
$qrDestination=!empty($record['public_qr_token'])?base_url('equipment-public?token='.rawurlencode($record['public_qr_token'])):'';
$shareUrl=$hasValidEquipmentShortLink?$record['xinng_short_url']:$qrDestination;
$qrImage=null;
if($hasValidEquipmentShortLink&&$qrDestination!==''){try{$qrImage=xinng_qr_image_url($qrDestination,$user['owner_id'],(string)$record['name'],'equipment',(string)$record['id'],(string)$record['xinng_short_url']);}catch(Throwable $error){error_log('Equipment QR display fallback: '.$error->getMessage());}}
?>
<link rel="stylesheet" href="assets/css/equipment-detail.css">
<link rel="stylesheet" href="assets/css/xinng-qr.css">
<?php $location=rows('SELECT sp.id block_id,sp.name block_name,p.id plant_id,p.name plant_name FROM units u JOIN plants p ON p.id=u.plant_id JOIN sites s ON s.id=p.site_id JOIN spaces sp ON sp.id=s.space_id WHERE u.id=?',[$record['unit_id']])[0]; ?>
<header class="asset-heading"><nav aria-label="Equipment location" class="asset-breadcrumbs"><?php foreach(['block'=>$location['block_name'],'site'=>$record['site_name'],'plant'=>$location['plant_name'],'unit'=>$record['unit_name']] as $level=>$name):?><a href="equipment?<?= $level ?>=<?= e($location[$level.'_id']??$record[$level.'_id']) ?>"><?= e($name) ?></a><?php endforeach;?></nav><div class="asset-title-row"><h1><?= e($record['name']) ?><?php if($canEdit):?><a href="#asset-edit" aria-label="Edit equipment">&#9998;</a><?php endif;?></h1><div class="asset-toolbar"><?php if($canEdit):?><a href="#schedule-maintenance">Schedule Maintenance</a><a href="#equipment-assemblies">+ Add Part</a><a href="#asset-edit">Edit Equipment</a><a href="#equipment-archive">Archive</a><?php endif;?><button type="button" id="asset-share">Share</button><button type="button" onclick="window.print()">Print</button></div></div><span id="asset-share-status" role="status"></span></header>
<?php if($canEdit||$hasValidEquipmentShortLink):?>
<section class="asset-qr-panel" aria-labelledby="equipment-qr-title" data-equipment-qr-panel>
	<div class="equipment-qr-copy">
		<h2 id="equipment-qr-title">Equipment QR</h2>
		<p>Scan to open this asset's public Nonagon equipment page.</p>
		<?php if(!empty($record['xinng_short_url'])&&!$hasValidEquipmentShortLink&&$canEdit):?>
			<p class="equipment-qr-note">The saved short link is not using the required four-letter code. Replacing it may use an Xinng credit; the existing link will remain until replacement succeeds.</p>
		<?php endif;?>
		<div class="equipment-qr-ready" data-equipment-qr-ready <?= $shareUrl===''?'hidden':'' ?>>
			<label class="sr-only" for="equipment-short-url">Equipment short link</label>
			<div class="equipment-qr-link-row">
				<input id="equipment-short-url" type="url" value="<?= e($shareUrl) ?>" readonly data-equipment-short-url>
				<button type="button" class="secondary" data-copy-equipment-qr>Copy link</button>
			</div>
			<a class="equipment-qr-open" href="<?= e($shareUrl) ?>" rel="noopener" target="_blank" data-equipment-qr-open>Open equipment link</a>
			<p class="equipment-qr-success" role="status" data-equipment-qr-success><?= $qrImage?'Saved short link and QR code ready. This link will be reused.':($shareUrl!==''?'QR service unavailable; use the direct equipment link. No QR code or short code was created.':'') ?></p>
			<img class="asset-qr-image" src="<?= e($qrImage??'') ?>" alt="QR code for <?= e($record['name']) ?>" width="176" height="176" data-equipment-qr-image <?= !$qrImage?'hidden':'' ?>>
		</div>
		<?php if((!$hasValidEquipmentShortLink||empty($record['xinng_short_url']))&&$canEdit):?>
			<?php if(empty($record['xinng_short_url'])):?><p class="equipment-qr-note">The saved short link and QR will be reused when you return to this equipment.</p><?php endif;?>
			<form action="operations-action" method="post" data-equipment-qr-form>
				<?= csrf_field() ?>
				<input type="hidden" name="action" value="equipment.qr.create">
				<input type="hidden" name="id" value="<?= e($id) ?>">
				<input type="hidden" name="confirm_destination_change" value="0" data-equipment-qr-confirm>
				<button class="primary" type="submit" data-equipment-qr-submit><?= !empty($record['xinng_short_url'])?'Replace with four-letter link':'Generate QR link' ?></button>
				<p class="equipment-qr-message" role="status" aria-live="polite" data-equipment-qr-message></p>
			</form>
		<?php endif;?>
	</div>
</section>
<?php endif;?>
<?php if($canEdit):?><section class="asset-facts equipment-marketplace-state"><div><span>Marketplace</span><strong><?= e($marketListing?ucfirst(strtolower($marketListing['listing_status'])):'Not listed') ?></strong><?php if($marketReadiness&&!$marketReadiness['ready']):?><small><?= e(implode(' · ',array_merge($marketReadiness['missing_fields'],$marketReadiness['blocking_issues']))) ?></small><?php endif;?></div><div class="marketplace-state-actions"><?php if(!$marketListing):?><form action="marketplace-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="listing.start"><input type="hidden" name="asset_id" value="<?= e($id) ?>"><button class="primary">List on Marketplace</button></form><?php elseif($marketListing['listing_status']==='DRAFT'):?><a class="primary" href="marketplace-manage?view=edit&id=<?= e($marketListing['id']) ?>">Continue listing</a><?php elseif(in_array($marketListing['listing_status'],['ACTIVE','RESERVED'],true)):?><a href="marketplace-listing?id=<?= e($marketListing['id']) ?>">View listing</a><form action="marketplace-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="listing.pause"><input type="hidden" name="id" value="<?= e($marketListing['id']) ?>"><button class="secondary">Pause listing</button></form><?php elseif($marketListing['listing_status']==='PAUSED'):?><form action="marketplace-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="listing.publish"><input type="hidden" name="id" value="<?= e($marketListing['id']) ?>"><button class="primary">Resume listing</button></form><a href="marketplace-manage?view=edit&id=<?= e($marketListing['id']) ?>">Review configuration</a><?php endif;?></div></section><?php endif;?>
<nav class="asset-tabs" aria-label="Equipment sections"><a href="#equipment-profile">Overview</a><a href="#asset-status-pane">Status &amp; Activity</a><a href="#equipment-assemblies">Assemblies &amp; Parts</a><a href="#equipment-values">Value &amp; Depreciation</a><a href="#asset-maintenance-pane">Maintenance &amp; Utilization</a><a href="#equipment-documentation">Documentation &amp; Certification</a><a href="#equipment-lease">Lease</a><a href="#equipment-activity">Activity Log</a></nav>
<section class="asset-pane" id="equipment-profile"><div class="asset-overview-columns"><div class="asset-left">
<div class="equipment-gallery"><img class="asset-primary" id="asset-main-photo" src="equipment-photo?equipment_id=<?= e($id) ?>" alt="<?= e($record['name']) ?>"><?php if($photos):?><div class="asset-thumbnails" aria-label="Equipment photos"><?php foreach($photos as $photo):?><button type="button" data-photo="equipment-photo?id=<?= e($photo['id']) ?>" data-caption="<?= e($photo['caption']??$record['name']) ?>" aria-label="View <?= e($photo['caption']??'equipment photo') ?>" aria-pressed="<?= $photo['is_primary']?'true':'false' ?>"><img src="equipment-photo?id=<?= e($photo['id']) ?>" alt="" loading="lazy"></button><?php endforeach;?></div><?php endif;?></div>
<section class="asset-facts asset-description"><h2>Description</h2><p><?= e($record['short_description']??'No description recorded.') ?></p><?= nl2br(e($record['long_description']??'')) ?></section>
<section class="asset-facts"><h2>Status</h2><dl><dt>Operational status</dt><dd><?= operation_badge($record['status']) ?></dd><dt>Company status</dt><dd><?= e($tax['status'][$record['status_id']??'']['name']??'Not specified') ?></dd></dl></section>
<section class="asset-facts"><h2>Operator &amp; Ownership</h2><dl><dt>Assigned operator</dt><dd><?= e($record['operator_name']??'Unassigned') ?></dd><dt>Owner</dt><dd><?= e($record['owner_name']?:$user['company_name']) ?></dd></dl></section>
</div><div class="asset-right"><section class="asset-facts"><h2>Identification</h2><dl><dt>Company asset ID</dt><dd><?= e($record['asset_code']) ?></dd><dt>Serial number / VIN</dt><dd><?= e($record['serial_no']??'Not recorded') ?></dd><dt>Company serial number</dt><dd><?= e($record['sequence_no']??'Not recorded') ?></dd><dt>Internal ID</dt><dd><?= e($id) ?></dd></dl></section>
<section class="asset-facts"><h2>Classification</h2><dl><?php foreach(['category_id'=>['category','Category'],'subcategory_id'=>['subcategory','Subcategory'],'type_id'=>['type','Type']] as $field=>[$kind,$label]):?><dt><?= $label ?></dt><dd><?= e($tax[$kind][$record[$field]??'']['name']??'Not specified') ?></dd><?php endforeach;?></dl></section>
<section class="asset-facts"><h2>Model</h2><dl><dt>Brand</dt><dd><?= e($tax['brand'][$record['brand_id']??'']['name']??'Not recorded') ?></dd><dt>Model</dt><dd><?= e($tax['model'][$record['model_id']??'']['name']??'Not recorded') ?></dd><dt>Make year</dt><dd><?= e((string)($record['manufacture_year']??'Not recorded')) ?></dd></dl></section>
<section class="asset-facts"><h2>Cost</h2><dl><dt>Purchase cost</dt><dd><?= e($money($profile['acquisition_cost']??null)) ?></dd><dt>Current book value</dt><dd><?= e($money($calculation['book_value']??null)) ?></dd><dt>Market value</dt><dd><?= e($money($valuation['market']['amount']??null)) ?></dd></dl></section>
<section class="asset-facts"><h2>Technical specifications</h2><p class="muted">No technical specifications recorded.</p></section></div></div>
<section class="asset-custom"><h2>Custom Fields</h2><p class="muted">No custom fields recorded.</p><h2>Custom Features</h2><div class="asset-facts"><p class="muted">No custom features recorded.</p></div></section>
<?php if($canEdit):?><details class="settings-form" id="asset-edit"><summary>Edit equipment identity and classification</summary><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="details"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Equipment name<input name="name" maxlength="255" value="<?= e($record['name']) ?>" required></label><label>Asset ID (AID)<input name="asset_code" maxlength="100" value="<?= e($record['asset_code']) ?>" required></label><?php $values=$record;$bulk=false;$prefix='edit';require __DIR__.'/equipment-fields.php';?><div class="full"><button class="primary">Save equipment profile</button></div></form></details><?php endif;?>
<details class="settings-form equipment-photo-manager" open><summary>Photos (<?= count($photos) ?>) and primary selection</summary><div class="photo-manager-grid"><?php foreach($photos as $photo):?><figure class="photo-manager-card <?= $photo['is_primary']?'is-primary':'' ?>"><button type="button" class="photo-view" data-photo="equipment-photo?id=<?= e($photo['id']) ?>" data-caption="<?= e($photo['caption']??$record['name']) ?>" aria-label="View <?= e($photo['caption']??'equipment photo') ?>"><img src="equipment-photo?id=<?= e($photo['id']) ?>" alt="<?= e($photo['caption']??$record['name']) ?>" loading="lazy"></button><figcaption><span><?= e($photo['caption']??'Equipment photo') ?></span><?php if($photo['is_primary']):?><strong>Primary</strong><?php endif;?></figcaption><?php if($canEdit):?><div class="photo-card-actions"><?php if(!$photo['is_primary']):?><form action="equipment-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="photo.primary"><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="photo_id" value="<?= e($photo['id']) ?>"><button>Set primary</button></form><?php endif;?><form action="equipment-action" method="post" data-photo-delete-form><?= csrf_field() ?><input type="hidden" name="action" value="photo.delete"><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="photo_id" value="<?= e($photo['id']) ?>"><button class="photo-delete" <?= count($photos)<=1?'disabled title="Equipment must keep at least one photo."':'' ?>>Delete</button></form></div><?php endif;?></figure><?php endforeach;?><?php if($canEdit):?><form action="equipment-action" method="post" enctype="multipart/form-data" class="photo-add-card photo-upload-card" data-photo-upload-form><?= csrf_field() ?><input type="hidden" name="action" value="photo.upload"><input type="hidden" name="id" value="<?= e($id) ?>"><label><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple data-photo-auto-submit><span class="photo-add-icon" aria-hidden="true">+</span><strong>Add photos</strong><small>JPEG, PNG or WebP · 2 MB each</small></label></form><?php endif;?></div><?php if(!$photos):?><p class="photo-manager-help">Add equipment photos to replace the category artwork. The first uploaded photo becomes primary automatically.</p><?php elseif(count($photos)===1):?><p class="photo-manager-help">Add another photo before deleting this one. Equipment with photos must always retain at least one.</p><?php else:?><p class="photo-manager-help">Choose Set primary on any photo. You can delete photos while at least one remains.</p><?php endif;?></details></section>
<section class="panel settings-section" id="equipment-values"><h2>Value & depreciation</h2><p>Current book value follows the straight-line profile. External and AI estimates remain separately labeled with their sources.</p>
<div class="value-grid"><article><span>Purchase value</span><strong><?= e($money($profile['acquisition_cost']??null)) ?></strong><small><?= e($profile['acquisition_date']??'No acquisition date') ?></small></article><article><span>Years of active use</span><strong><?= $calculation?e((string)$calculation['years_active']):'Not calculated' ?></strong><small>Elapsed days ÷ 365 · no meter data</small></article><article><span>Current book value</span><strong><?= e($money($calculation['book_value']??null)) ?></strong><small><?= $calculation&&$calculation['change_percent']!==null?e((string)$calculation['change_percent']).'% vs acquisition':'No percentage baseline' ?> · System formula</small></article><article><span>Current new market value</span><strong><?= e($money($valuation['market']['amount']??null)) ?></strong><small><?= e($valuation['market']?($valuation['market']['source_type'].' · '.$valuation['market']['as_of_date']):'No external valuation recorded') ?></small></article></div>
<?php if($valuation['market']):?><p class="source-note">Market source: <?= e($valuation['market']['source_detail']) ?></p><?php endif;?>
<?php if($valuation['ai_book']):?><p class="source-note"><strong>AI book value estimate: <?= e($money($valuation['ai_book']['amount'])) ?></strong><br><?= e($valuation['ai_book']['source_detail'].' · '.$valuation['ai_book']['as_of_date']) ?></p><?php endif;?>
<?php if($history):
$chartRows=$history;if($calculation)$chartRows[]=['as_of_date'=>gmdate('Y-m-d'),'amount'=>$calculation['book_value'],'value_type'=>'BOOK'];
$dates=array_map(fn($r)=>strtotime($r['as_of_date'].' UTC'),$chartRows);$minDate=min($dates);$maxDate=max($dates);$maxAmount=max(1,...array_map(fn($r)=>(float)$r['amount'],$chartRows));
$series=['PURCHASE'=>'#60758a','BOOK'=>'#0a6fb8','MARKET'=>'#168260','BOOK_ESTIMATE_AI'=>'#8c61b5','MARKET_ESTIMATE_AI'=>'#b27423'];
?><figure class="value-chart"><figcaption>Value over time · <?= e($currency) ?> <small>Actual recorded observations; formula book value is also shown for today.</small></figcaption><svg viewBox="0 0 640 220" role="img" aria-label="Equipment valuation history. Exact values and sources are listed below."><path d="M80 20V175H625" fill="none" stroke="#cbd5e1"/><text x="3" y="28" fill="#526477" font-size="11"><?= e(number_format($maxAmount,0)) ?></text><text x="52" y="179" fill="#526477" font-size="11">0</text><text x="80" y="203" fill="#526477" font-size="11"><?= gmdate('Y-m-d',$minDate) ?></text><text x="550" y="203" fill="#526477" font-size="11"><?= gmdate('Y-m-d',$maxDate) ?></text>
<?php foreach($series as $type=>$color):$points=[];foreach($chartRows as $row){if($row['value_type']!==$type)continue;$x=80+535*(strtotime($row['as_of_date'].' UTC')-$minDate)/max(86400,$maxDate-$minDate);$y=175-150*(float)$row['amount']/$maxAmount;$points[]=round($x,2).','.round($y,2);}if(!$points)continue;?><polyline points="<?= implode(' ',$points) ?>" fill="none" stroke="<?= $color ?>" stroke-width="2"/><?php foreach($points as $point):[$x,$y]=explode(',',$point);?><circle cx="<?= $x ?>" cy="<?= $y ?>" r="3" fill="<?= $color ?>"/><?php endforeach;endforeach;?></svg><div class="chart-legend"><?php foreach($series as $type=>$color):?><span><i style="background:<?= $color ?>"></i><?= e(str_replace('_',' ',$type)) ?></span><?php endforeach;?></div></figure>
<details class="settings-form"><summary>Value observations and sources (<?= count($history) ?>)</summary><div class="table-wrap"><table><thead><tr><th>Date</th><th>Value type</th><th>Amount</th><th>Source</th></tr></thead><tbody><?php foreach(array_reverse($history) as $snapshot):?><tr><td><?= e($snapshot['as_of_date']) ?></td><td><?= e($snapshot['value_type']) ?></td><td><?= e($money($snapshot['amount'])) ?></td><td><?= e($snapshot['source_type']) ?><small><?= e($snapshot['source_detail']) ?></small></td></tr><?php endforeach;?></tbody></table></div></details><?php else:?><p class="empty-inline">Save a depreciation profile or record an external value to start the history.</p><?php endif;?>
<?php if($canEdit):?><details class="settings-form"><summary><?= $profile?'Edit':'Set up' ?> straight-line depreciation</summary><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="depreciation"><input type="hidden" name="id" value="<?= e($id) ?>"><?php foreach(['acquisition_cost'=>'Acquisition cost','salvage_value'=>'Salvage value','useful_life_years'=>'Useful life (years)'] as $key=>$label):?><label><?= $label ?><input name="<?= $key ?>" type="number" min="<?= $key==='useful_life_years'?'0.001':'0' ?>" step="<?= $key==='useful_life_years'?'0.001':'0.01' ?>" value="<?= e((string)($profile[$key]??($key==='salvage_value'?'0':''))) ?>" required></label><?php endforeach;?><label>Currency<input name="currency" value="<?= e($currency) ?>" pattern="[A-Za-z]{3}" maxlength="3" required></label><label>Acquisition date<input type="date" name="acquisition_date" value="<?= e($profile['acquisition_date']??'') ?>" required></label><label>Depreciation start date <small>Defaults to acquisition date</small><input type="date" name="start_date" value="<?= e($profile['start_date']??'') ?>"></label><label class="check-label full"><input type="checkbox" name="is_active" <?= !$profile||$profile['is_active']?'checked':'' ?>> Active depreciation profile</label><label class="full">Notes<textarea name="notes" maxlength="20000"><?= e($profile['notes']??'') ?></textarea></label><p class="full">Annual depreciation = (cost − salvage) ÷ useful life. Book value never falls below salvage. Turning off the profile pauses calculations; prior snapshots remain intact.</p><div class="full"><button class="primary">Save depreciation profile</button></div></form></details>
<details class="settings-form"><summary>Record a market value or externally supplied AI estimate</summary><p>Enter a value you already obtained. This form does not generate an AI valuation.</p><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="value"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Value type<select name="value_type"><option value="MARKET">Market value</option><option value="MARKET_ESTIMATE_AI">AI market estimate</option><option value="BOOK_ESTIMATE_AI">AI book estimate</option></select></label><label>Source type<select name="source_type"><option value="USER">User observation</option><option value="EXTERNAL_API">External API</option><option value="AI_AGENT">AI agent</option></select></label><label>Amount (<?= e($currency) ?>)<input name="amount" type="number" min="0" step="0.01" required></label><label>As-of date<input name="as_of_date" type="date" max="<?= gmdate('Y-m-d') ?>" value="<?= gmdate('Y-m-d') ?>" required></label><label class="full">Source details / model / reference<textarea name="source_detail" maxlength="20000" required></textarea></label><div class="full"><button class="primary">Record value observation</button></div></form></details><?php endif;?></section>
<section class="panel settings-section" id="equipment-assemblies"><h2>Assemblies & installed parts</h2><p>Asset-level construction, cloned templates, and custom add-ons. Removed parts remain in the installation history.</p>
<?php if(!$assemblies):?><p class="empty-inline">No assemblies have been installed. Classify this asset by equipment type to load matching templates, or add a custom assembly.</p><?php endif;?>
<?php $assemblyNames=array_column($assemblies,'name','id');foreach($assemblies as $assembly):$installed=rows('SELECT i.*,p.name AS part_name,p.unit_of_measure FROM equipment_assembly_items i LEFT JOIN part_master p ON p.id=i.part_id WHERE i.equipment_assembly_id=? ORDER BY i.sequence,i.installed_at,i.id',[$assembly['id']]);?><details class="settings-form" open><summary><?= e(($assembly['parent_assembly_id']?($assemblyNames[$assembly['parent_assembly_id']].' / '):'').$assembly['name']) ?> <span class="muted"><?= $assembly['is_custom_addon']?'Custom add-on':'From template' ?></span></summary><p><?= e($assembly['description']??'') ?></p><div class="table-wrap"><table><thead><tr><th>Part / slot</th><th>Quantity</th><th>Installation</th><th></th></tr></thead><tbody><?php foreach($installed as $item):?><tr><td><?= e($item['part_name']??$item['custom_name']) ?><small><?= $item['is_custom_addon']?'Custom / asset-specific':'Template part' ?></small></td><td><?= e($item['quantity'].' '.($item['unit_of_measure']??'')) ?></td><td><?= e($item['status']??'Not recorded') ?><small><?= e($item['installed_at']??'Not installed') ?><?= $item['removed_at']?' · Removed '.e($item['removed_at']):'' ?></small></td><td><?php if($canEdit&&!$item['removed_at']&&$item['installed_at']):?><form action="equipment-action" method="post"><?= csrf_field() ?><input type="hidden" name="action" value="part.remove"><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="item_id" value="<?= e($item['id']) ?>"><button class="text-button">Mark removed</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
<?php if($canEdit):?><form action="equipment-action" method="post" class="form-grid mini-form"><?= csrf_field() ?><input type="hidden" name="action" value="part.add"><input type="hidden" name="id" value="<?= e($id) ?>"><input type="hidden" name="equipment_assembly_id" value="<?= e($assembly['id']) ?>"><label>Canonical part<select name="part_id"><option value="">Use a custom name</option><?php foreach($catalog['part'] as $part):?><option value="<?= e($part['id']) ?>"><?= e($part['name']) ?></option><?php endforeach;?></select></label><label>Custom part name <small>Required if no canonical part</small><input name="custom_name" maxlength="255"></label><label>Quantity<input type="number" name="quantity" min="0.001" step="0.001" value="1" required></label><label>Display order<input type="number" name="sequence" value="0"></label><div class="full"><button class="secondary">Install part / add-on</button></div></form><?php endif;?></details><?php endforeach;?>
<?php if($canEdit):?><details class="settings-form"><summary>Add custom assembly</summary><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="assembly.add"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Assembly name<input name="name" maxlength="255" required></label><label>Display order<input name="sequence" type="number" value="0"></label><label class="full">Description<textarea name="description" maxlength="20000"></textarea></label><div class="full"><button class="primary">Add assembly</button></div></form></details><form action="equipment-action" method="post" class="section-gap"><?= csrf_field() ?><input type="hidden" name="action" value="templates.load"><input type="hidden" name="id" value="<?= e($id) ?>"><button class="secondary">Load missing matching templates</button><p>Existing assemblies and installed quantities are preserved.</p></form><?php endif;?></section>
<section class="panel settings-section" id="equipment-documentation"><h2>Documentation &amp; certification</h2><p>No document management integration is available for this equipment yet.</p></section>
<section class="panel settings-section" id="equipment-lease"><h2>Lease</h2><p>No lease records are available for this equipment.</p></section>
<?php if($canEdit):?><section class="panel settings-section" id="equipment-archive"><h2>Archive equipment</h2><p>Remove this asset from the active register and KPI totals. Its photos, maintenance records, values, and audit history will be retained. Open maintenance and active alerts must be resolved first.</p><form action="equipment-action" method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="<?= e($id) ?>"><label>Type the asset ID to confirm: <?= e($record['asset_code']) ?><input name="confirmation" maxlength="100" autocomplete="off" required></label><div class="full"><button class="secondary">Archive equipment</button></div></form></section><?php endif;?>
<script src="assets/js/equipment-detail.js?v=<?= filemtime(APP_ROOT.'/assets/js/equipment-detail.js') ?>" defer></script>
<script src="assets/js/equipment-photos.js?v=<?= filemtime(APP_ROOT.'/assets/js/equipment-photos.js') ?>" defer></script>
<script src="assets/js/equipment-catalog.js?v=<?= filemtime(APP_ROOT.'/assets/js/equipment-catalog.js') ?>" defer></script>
