<?php
header('Cache-Control: no-store, private');
require_once __DIR__.'/operations-icons.php';
$active = $active ?? 'dashboard';
$pageTitle = $pageTitle ?? 'Overview';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0e70b5"><title><?= e($pageTitle) ?> · Nonagon</title><link rel="icon" href="assets/images/favicon.ico" type="image/x-icon"><link rel="stylesheet" href="assets/css/operations.css"><link rel="stylesheet" href="assets/css/operations-design.css?v=<?= filemtime(APP_ROOT.'/assets/css/operations-design.css') ?>"><link rel="stylesheet" href="assets/css/equipment-catalog.css"><link rel="stylesheet" href="assets/css/equipment-detail.css"><link rel="stylesheet" href="assets/css/equipment-photos.css"><link rel="stylesheet" href="assets/css/creation-card-preview.css"><?php if($active==='marketplace'):?><link rel="stylesheet" href="assets/css/marketplace.css"><link rel="stylesheet" href="assets/css/marketplace-negotiation.css"><link rel="stylesheet" href="assets/css/request-supply.css"><link rel="stylesheet" href="assets/css/request-card-listing.css?v=<?= filemtime(APP_ROOT.'/assets/css/request-card-listing.css') ?>"><link rel="stylesheet" href="assets/css/request-distribution.css"><?php endif;?><?php if($active==='commercial'):?><link rel="stylesheet" href="assets/css/commercial.css?v=<?= filemtime(APP_ROOT.'/assets/css/commercial.css') ?>"><?php endif;?><link rel="stylesheet" href="assets/css/lease-workspace.css"><script src="assets/js/creation-card-preview.js" defer></script><?php if($active==='commercial'):?><script src="assets/js/commercial.js?v=<?= filemtime(APP_ROOT.'/assets/js/commercial.js') ?>" defer></script><?php endif;?></head>
<?php if($active==='qms'):?><link rel="stylesheet" href="assets/css/qhse.css?v=<?= filemtime(APP_ROOT.'/assets/css/qhse.css') ?>"><link rel="stylesheet" href="assets/css/qhse-certificates.css?v=<?= filemtime(APP_ROOT.'/assets/css/qhse-certificates.css') ?>"><link rel="stylesheet" href="assets/css/qhse-quick-create.css?v=<?= filemtime(APP_ROOT.'/assets/css/qhse-quick-create.css') ?>"><link rel="stylesheet" href="assets/css/qhse-dynamic-certificate.css?v=<?= filemtime(APP_ROOT.'/assets/css/qhse-dynamic-certificate.css') ?>"><?php endif;?><body class="<?= $active==='dashboard'?'overview-page':'record-page' ?>"><a class="skip" href="#main">Skip to content</a>
<aside class="sidebar"><a class="brand" href="dashboard"><img src="assets/images/nonagon-logo-white.png" width="168" alt="Nonagon"></a>
<nav aria-label="Main navigation"><?php foreach(['dashboard'=>['home','Overview'],'equipment'=>['equipment','Equipment'],'marketplace'=>['equipment','Lease'],'requests'=>['equipment','Procurement'],'commercial'=>['invoice','Commercial'],'maintenance'=>['maintenance','Maintenance'],'qms'=>['shield','QHSE'],'operators'=>['users','Operators'],'alerts'=>['alert','Alerts & risks'],'equipment-settings'=>['settings','Equipment Settings'],'profile'=>['settings','Your profile']] as $route=>$item):?><a href="<?= $route==='marketplace'?'marketplace-manage?view=listings':$route ?>" aria-label="<?= e($item[1]) ?>" <?= $active===$route?'aria-current="page"':'' ?>><?= operation_icon($item[0]) ?><span class="nav-label"><?= $item[1] ?></span></a><?php endforeach;?></nav>
<div class="sidebar-bottom"><?php if(in_array($user['role'],['OWNER_ADMIN','ADMIN'],true)):?><a class="invite-link" href="invite"><?= operation_icon('users') ?> Invite team member</a><?php endif;?><div class="sidebar-account"><a class="identity" href="profile"><span class="avatar"><?= e(strtoupper(substr($user['full_name'],0,1))) ?></span><span class="account-copy"><strong><?= e($user['full_name']) ?></strong><small><?= e($user['email']) ?></small></span></a><form action="logout" method="post" id="sign-out"><?= csrf_field() ?><button class="signout-icon" title="Sign out" aria-label="Sign out"><?= operation_icon('logout') ?></button></form></div></div></aside>
<div class="app-shell"><header class="topbar"><div class="topbar-title"><span><?= e($pageTitle) ?></span><small><?= $active==='dashboard'?'Overview of your Equipment Management System':e($user['company_name']).' · Equipment Management System' ?></small></div><div class="topbar-actions"><a class="back-to-marketplace" href="marketplace"><span aria-hidden="true">←</span> Back to Marketplace</a><a class="notification-link" href="alerts" aria-label="View operational alerts"><?= operation_icon('bell') ?></a></div></header>
<main id="main"><?php if($active!=='dashboard'):?><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="dashboard">Overview</a><span>/</span><a href="<?= $active==='marketplace'?'marketplace-manage?view=listings':e($active) ?>"><?= $active==='marketplace'?'Lease':e(ucfirst($active)) ?></a><span>/</span><span aria-current="page"><?= e($pageTitle) ?></span></nav><?php endif;?>
<?php foreach(['success','error'] as $kind):if($message=flash($kind)):?><div class="notice <?= $kind ?>" role="<?= $kind==='error'?'alert':'status' ?>"><?= e($message) ?></div><?php endif;endforeach;?>
