<?php $requestPhotos=isset($request)?rows('SELECT id,file_name,caption,is_primary FROM request_photos WHERE request_id=? ORDER BY is_primary DESC,sequence,created_at',[$request['id']]):[];?>
<div class="equipment-register-grid">
<section class="panel form-panel"><h2><?= isset($request)?'Update requirement':'Add a requirement' ?></h2>
<form action="request-action" method="post" enctype="multipart/form-data" class="form-grid" data-safe-draft="request-<?= e($request['id']??'new') ?>">
<?= csrf_field() ?><input type="hidden" name="action" value="request.<?= isset($request)?'update':'create' ?>"><?php if(isset($request)):?><input type="hidden" name="id" value="<?= e($request['id']) ?>"><?php endif;?>
<label>Request title<input name="title" value="<?= e($request['title']??'') ?>" required maxlength="255"><small>Use a clear name suppliers will recognize.</small></label>
<label>Quantity<input type="number" min="1" name="quantity_required" value="<?= (int)($request['quantity_required']??1) ?>" required></label>
<fieldset class="catalog-fields full"><legend>Equipment classification <small>What equipment do you need?</small></legend><div class="form-grid">
<label>Category<select name="category_id"><option value="">Choose category</option><?php foreach($categories as $option):?><option value="<?= e($option['id']) ?>" <?= ($request['category_id']??'')===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select></label>
<label>Subcategory<select name="subcategory_id"><option value="">Choose subcategory</option><?php foreach($subcategories as $option):?><option value="<?= e($option['id']) ?>" <?= ($request['subcategory_id']??'')===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select></label>
<label class="full">Equipment type<select name="equipment_type_id" required><option value="">Choose equipment type</option><?php foreach($types as $option):?><option value="<?= e($option['id']) ?>" <?= ($request['equipment_type_id']??'')===$option['id']?'selected':'' ?>><?= e($option['name']) ?></option><?php endforeach;?></select></label>
</div></fieldset>
<fieldset class="catalog-fields full"><legend>Commercial requirement</legend><div class="form-grid">
<label>Commercial intent<select name="intent"><?php foreach(['LEASE'=>'Lease','PURCHASE'=>'Purchase','EITHER'=>'Lease or purchase'] as $value=>$label):?><option value="<?= $value ?>" <?= ($request['intent']??'LEASE')===$value?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
<label>Visibility<select name="visibility"><option value="PUBLIC" <?= ($request['visibility']??'PUBLIC')==='PUBLIC'?'selected':'' ?>>Public Marketplace</option><option value="PRIVATE" <?= ($request['visibility']??'')==='PRIVATE'?'selected':'' ?>>Private</option></select></label>
<label class="full">Required location<select name="required_location_id" required><option value="">Choose location</option><?php foreach($locations as $option):?><option value="<?= e($option['id']) ?>" <?= ($request['required_location_id']??'')===$option['id']?'selected':'' ?>><?= e($option['canonical_name'].($option['country_name']?' · '.$option['country_name']:'')) ?></option><?php endforeach;?></select></label>
<label>Required from<input type="date" name="required_from" value="<?= e($request['required_from']??'') ?>" required></label><label>Required until<input type="date" name="required_until" value="<?= e($request['required_until']??'') ?>"></label>
<label class="full">Response deadline<input type="datetime-local" name="response_deadline" value="<?= e(isset($request)?date('Y-m-d\TH:i',strtotime($request['response_deadline'])):'') ?>" required><small>The request automatically leaves active marketplace discovery after this time.</small></label>
</div></fieldset>
<fieldset class="catalog-fields full"><legend>Requirement details</legend><div class="form-grid">
<label class="full">Short description<textarea name="description" rows="4" required><?= e($request['description']??'') ?></textarea></label>
<label class="full">Core specifications <small>One per line, for example: Capacity: 20 tonnes</small><textarea name="core_specifications" rows="5"><?php foreach(json_decode($request['core_specifications']??'{}',true)?:[] as $key=>$value)echo e($key.': '.$value)."\n";?></textarea></label>
<label>OEM preference<input name="oem_preference" value="<?= e($request['oem_preference']??'') ?>"></label><label>Model preference<input name="model_preference" value="<?= e($request['model_preference']??'') ?>"></label>
<label class="full">Required certifications/documents<textarea name="required_documents" rows="3"><?= e($request['required_documents']??'') ?></textarea></label>
<label class="check-label full"><input type="checkbox" name="alternatives_accepted" value="1" <?= !isset($request)||!empty($request['alternatives_accepted'])?'checked':'' ?>> Alternatives accepted</label>
</div></fieldset>
<section class="equipment-photo-manager registration-photo-manager full" data-registration-photos><div class="photo-manager-heading"><div><h3>Request photos</h3><p>Add reference photos, equipment examples, or site images. JPEG, PNG, or WebP; maximum 2 MB each.</p></div><span data-photo-count><?= count($requestPhotos??[]) ?> photo<?= count($requestPhotos??[])===1?'':'s' ?></span></div><div class="photo-manager-grid" data-photo-preview><?php foreach($requestPhotos??[] as $photo):?><figure class="photo-manager-card <?= $photo['is_primary']?'is-primary':'' ?>"><img src="request-photo?id=<?= e($photo['id']) ?>" alt="<?= e($photo['caption']?:'Request photo') ?>"><figcaption><span><?= e($photo['caption']?:$photo['file_name']) ?></span><?php if($photo['is_primary']):?><strong>Primary</strong><?php endif;?></figcaption></figure><?php endforeach;?><label class="photo-add-card"><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple><span class="photo-add-icon" aria-hidden="true">+</span><strong>Add photos</strong><small>Select multiple files</small></label></div><input type="hidden" name="primary_photo_index" value="0" data-primary-photo-index><p class="photo-manager-help">The first newly selected photo is primary by default. Select another preview to change it before saving.</p></section>
<div class="full form-actions"><?php if(isset($request)):?><button class="primary">Save changes</button><?php else:?><button name="review" value="1" class="primary">Save and review</button><button name="save_draft" value="1">Save as draft</button><?php endif;?> <a href="requests">Cancel</a></div>
</form></section>
<?php $previewKind='request';$previewImage=($requestPhotos[0]['id']??null)?'request-photo?id='.rawurlencode($requestPhotos[0]['id']):'assets/images/equipment-placeholder.svg';require __DIR__.'/creation-card-preview.php';?>
</div>
<script src="assets/js/equipment-photos.js?v=<?= filemtime(APP_ROOT.'/assets/js/equipment-photos.js') ?>" defer></script>
